In [2]:
import pandas as pd

In [107]:
### prep AnnoTinder data for merging

In [3]:
file_names = [
    "annotations_95_AnnoBias job final, set 1.csv.csv",
    "annotations_96_AnnoBias job final, set 2.csv.csv",
    "annotations_97_AnnoBias job final, set 3.csv.csv",
    "annotations_98_AnnoBias job final, set 4.csv.csv",
    "annotations_99_AnnoBias job final, set 5.csv.csv",
    "annotations_100_AnnoBias job final, set 6.csv.csv"
]

dataframes = []

for idx, file in enumerate(file_names, start=1):
    df = pd.read_csv(f"data/AnnoTinder_data_exports/{file}")  
    
    # Add a "condition" column based on the file number
    
    df['condition_AT'] = idx    
    dataframes.append(df)  # Append the DataFrame to the list

annotinder_df = pd.concat(dataframes, ignore_index=True)
annotinder_df['uid'] = annotinder_df['coder']

In [4]:
len(set(annotinder_df['uid']))

1461

In [200]:
#X_data = pd.read_csv('data/X_data/final_stratified_immigration.csv')
#print(list(X_data['tweet_id']))

In [221]:
#annotinder_df[annotinder_df['coder']== 266019]

In [166]:
# Step 1: Ensure 'unit_id_digits' is a string type in both DataFrames
annotinder_df['unit_id_digits'] = annotinder_df['unit_id_digits'].astype(str)
X_data['unit_id_digits'] = X_data['unit_id_digits'].astype(str)

# Create a subset for merging with long lines of numbers
min_length = 10  # Define your minimum length for the digits
valid_entries = annotinder_df[annotinder_df['unit_id_digits'].str.len() >= min_length]

# Debug: Check the valid entries DataFrame
print("Valid entries for merging:")
print(valid_entries)

# Merge using only valid entries and ensure we are selecting 'full_text'
merged_data = pd.merge(valid_entries, X_data[['unit_id_digits', 'full_text']], 
                        on='unit_id_digits', how='left')

# Debug: Check the merged_data DataFrame
print("Merged DataFrame:")
print(merged_data)

# Update the original DataFrame with the merged information
# Ensure the full_text is present in merged_data before proceeding
if 'full_text' in merged_data.columns:
    annotinder_df = annotinder_df.merge(merged_data[['unit_id_digits', 'full_text']], 
                                         on='unit_id_digits', 
                                         how='left', 
                                         suffixes=('', '_from_merge'))
else:
    print("The 'full_text' column was not found in merged_data.")

# Display the final DataFrame
print("\nFinal DataFrame with additional full_text info:")

Valid entries for merging:
        coder_id   coder    jobset              unit_id unit_status  \
3          12149  266019   batch_2         test vraag 1        DONE
4          12149  266019   batch_2         test vraag 1        DONE
5          12149  266019   batch_2         test vraag 1        DONE
6          12149  266019   batch_2         test vraag 1        DONE
7          12149  266019   batch_2         test vraag 1        DONE
...          ...     ...       ...                  ...         ...
904500     12274  266180  batch_23  1629180709255479296        DONE
904501     12274  266180  batch_23  1629180709255479296        DONE
904502     12274  266180  batch_23  1629180709255479296        DONE
904503     12274  266180  batch_23  1629180709255479296        DONE
904504     12274  266180  batch_23  1629180709255479296        DONE

                         variable     value             time_question  \
3       political_stance_training      Waar  2024-10-14T09:27:36.448Z
4       political_stance_training      Waar  2024-10-14T09:27:36.448Z
5       political_stance_training      Waar  2024-10-14T09:27:36.448Z
6       political_stance_training      Waar  2024-10-14T09:27:36.448Z
7       political_stance_training      Waar  2024-10-14T09:27:36.448Z
...                           ...       ...                       ...
904500  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904501  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904502  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904503  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904504  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z

                     time_answer  field  ...  period  Location  Age  \
3       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
4       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
5       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
6       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
7       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
...                          ...    ...  ...     ...       ...  ...
904500  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904501  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904502  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904503  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904504  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN

        Seniority  Image_URL Political_Party normalized_party Ideology  \
3             NaN        NaN             NaN              NaN      NaN
4             NaN        NaN             NaN              NaN      NaN
5             NaN        NaN             NaN              NaN      NaN
6             NaN        NaN             NaN              NaN      NaN
7             NaN        NaN             NaN              NaN      NaN
...           ...        ...             ...              ...      ...
904500        NaN        NaN             NaN              NaN      NaN
904501        NaN        NaN             NaN              NaN      NaN
904502        NaN        NaN             NaN              NaN      NaN
904503        NaN        NaN             NaN              NaN      NaN
904504        NaN        NaN             NaN              NaN      NaN

       Ideology_Group immigration
3                 NaN         NaN
4                 NaN         NaN
5                 NaN         NaN
6                 NaN         NaN
7                 NaN         NaN
...               ...         ...
904500            NaN         NaN
904501            NaN         NaN
904502            NaN         NaN
904503            NaN         NaN
904504            NaN         NaN

[904097 rows x 59 columns]
Merged DataFrame:
        coder_id   coder    jobset              unit_id unit_status  \
0          12149  266019   batch_2         test vraag 1        DONE
1          12149  266019   batch_2         test vraag 1        DONE
2          12149  266019   batch_2         test vraag 1        DONE
3          12149  266019   batch_2         test vraag 1        DONE
4          12149  266019   batch_2         test vraag 1        DONE
...          ...     ...       ...                  ...         ...
904092     12274  266180  batch_23  1629180709255479296        DONE
904093     12274  266180  batch_23  1629180709255479296        DONE
904094     12274  266180  batch_23  1629180709255479296        DONE
904095     12274  266180  batch_23  1629180709255479296        DONE
904096     12274  266180  batch_23  1629180709255479296        DONE

                         variable     value             time_question  \
0       political_stance_training      Waar  2024-10-14T09:27:36.448Z
1       political_stance_training      Waar  2024-10-14T09:27:36.448Z
2       political_stance_training      Waar  2024-10-14T09:27:36.448Z
3       political_stance_training      Waar  2024-10-14T09:27:36.448Z
4       political_stance_training      Waar  2024-10-14T09:27:36.448Z
...                           ...       ...                       ...
904092  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904093  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904094  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904095  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z
904096  stellingen.misinformation  Neutraal  2024-10-14T10:49:36.539Z

                     time_answer  field  ...  Location  Age Seniority  \
0       2024-10-14T09:27:56.518Z    NaN  ...       NaN  NaN       NaN
1       2024-10-14T09:27:56.518Z    NaN  ...       NaN  NaN       NaN
2       2024-10-14T09:27:56.518Z    NaN  ...       NaN  NaN       NaN
3       2024-10-14T09:27:56.518Z    NaN  ...       NaN  NaN       NaN
4       2024-10-14T09:27:56.518Z    NaN  ...       NaN  NaN       NaN
...                          ...    ...  ...       ...  ...       ...
904092  2024-10-14T10:50:06.875Z    NaN  ...       NaN  NaN       NaN
904093  2024-10-14T10:50:06.875Z    NaN  ...       NaN  NaN       NaN
904094  2024-10-14T10:50:06.875Z    NaN  ...       NaN  NaN       NaN
904095  2024-10-14T10:50:06.875Z    NaN  ...       NaN  NaN       NaN
904096  2024-10-14T10:50:06.875Z    NaN  ...       NaN  NaN       NaN

        Image_URL  Political_Party normalized_party Ideology Ideology_Group  \
0             NaN              NaN              NaN      NaN            NaN
1             NaN              NaN              NaN      NaN            NaN
2             NaN              NaN              NaN      NaN            NaN
3             NaN              NaN              NaN      NaN            NaN
4             NaN              NaN              NaN      NaN            NaN
...           ...              ...              ...      ...            ...
904092        NaN              NaN              NaN      NaN            NaN
904093        NaN              NaN              NaN      NaN            NaN
904094        NaN              NaN              NaN      NaN            NaN
904095        NaN              NaN              NaN      NaN            NaN
904096        NaN              NaN              NaN      NaN            NaN

       immigration full_text_y
0              NaN         NaN
1              NaN         NaN
2              NaN         NaN
3              NaN         NaN
4              NaN         NaN
...            ...         ...
904092         NaN         NaN
904093         NaN         NaN
904094         NaN         NaN
904095         NaN         NaN
904096         NaN         NaN

[904097 rows x 60 columns]
The 'full_text' column was not found in merged_data.

Final DataFrame with additional full_text info:
        coder_id   coder    jobset              unit_id unit_status  \
0          12149  266019   batch_2               welkom        DONE
1          12158  265991   batch_3               welkom        DONE
2          12149  266019   batch_2              welkom2        DONE
3          12149  266019   batch_2         test vraag 1        DONE
4          12149  266019   batch_2         test vraag 1        DONE
...          ...     ...       ...                  ...         ...
904500     12274  266180  batch_23  1629180709255479296        DONE
904501     12274  266180  batch_23  1629180709255479296        DONE
904502     12274  266180  batch_23  1629180709255479296        DONE
904503     12274  266180  batch_23  1629180709255479296        DONE
904504     12274  266180  batch_23  1629180709255479296        DONE

                         variable      value             time_question  \
0                         confirm  confirmed  2024-10-14T09:26:10.051Z
1                         confirm  confirmed  2024-10-14T09:27:33.001Z
2                         confirm  confirmed  2024-10-14T09:27:34.676Z
3       political_stance_training       Waar  2024-10-14T09:27:36.448Z
4       political_stance_training       Waar  2024-10-14T09:27:36.448Z
...                           ...        ...                       ...
904500  stellingen.misinformation   Neutraal  2024-10-14T10:49:36.539Z
904501  stellingen.misinformation   Neutraal  2024-10-14T10:49:36.539Z
904502  stellingen.misinformation   Neutraal  2024-10-14T10:49:36.539Z
904503  stellingen.misinformation   Neutraal  2024-10-14T10:49:36.539Z
904504  stellingen.misinformation   Neutraal  2024-10-14T10:49:36.539Z

                     time_answer  field  ...  period  Location  Age  \
0       2024-10-14T09:27:33.757Z    NaN  ...     NaN       NaN  NaN
1       2024-10-14T09:28:10.626Z    NaN  ...     NaN       NaN  NaN
2       2024-10-14T09:27:35.600Z    NaN  ...     NaN       NaN  NaN
3       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
4       2024-10-14T09:27:56.518Z    NaN  ...     NaN       NaN  NaN
...                          ...    ...  ...     ...       ...  ...
904500  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904501  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904502  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904503  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN
904504  2024-10-14T10:50:06.875Z    NaN  ...     NaN       NaN  NaN

        Seniority  Image_URL Political_Party normalized_party Ideology  \
0             NaN        NaN             NaN              NaN      NaN
1             NaN        NaN             NaN              NaN      NaN
2             NaN        NaN             NaN              NaN      NaN
3             NaN        NaN             NaN              NaN      NaN
4             NaN        NaN             NaN              NaN      NaN
...           ...        ...             ...              ...      ...
904500        NaN        NaN             NaN              NaN      NaN
904501        NaN        NaN             NaN              NaN      NaN
904502        NaN        NaN             NaN              NaN      NaN
904503        NaN        NaN             NaN              NaN      NaN
904504        NaN        NaN             NaN              NaN      NaN

       Ideology_Group immigration
0                 NaN         NaN
1                 NaN         NaN
2                 NaN         NaN
3                 NaN         NaN
4                 NaN         NaN
...               ...         ...
904500            NaN         NaN
904501            NaN         NaN
904502            NaN         NaN
904503            NaN         NaN
904504            NaN         NaN

[904505 rows x 59 columns]

In [175]:
value_to_check = 1629180709255479296  # Ensure this is a string if your column is of type string
exists = X_data['tweet_id'].isin([value_to_check]).any()

In [176]:
print(f"Does {value_to_check} exist in 'unit_id_digits'? {exists}")

Does 1629180709255479296 exist in 'unit_id_digits'? False

In [171]:
print(f"Does {value_to_check} exist in 'unit_id_digits'? {exists}")

Does 1629180709255479296 exist in 'unit_id_digits'? False

In [147]:
import pandas as pd


annotinder_df['unit_id_digits'] = annotinder_df['unit_id_digits'].astype(str)

# Step 2: Create a subset for merging with long lines of numbers
min_length = 10  # Define your minimum length for the digits
valid_entries = annotinder_df[annotinder_df['unit_id_digits'].str.len() > min_length]

In [148]:
merged_data = pd.merge(valid_entries, X_data, on='unit_id_digits', how='left')


annotinder_df = annotinder_df.merge(merged_data, 
                                     on='unit_id_digits', 
                                     how='left', 
                                     suffixes=('', '_from_merge'))

# Display the final DataFrame
annotinder

NameError: name 'annotinder' is not defined

In [211]:
#X_data['unit_id']

In [110]:
list(annotinder_df)

annotinder_df['unit_id']

0                     welkom
1                     welkom
2                    welkom2
3               test vraag 1
4               test vraag 1
                ...
16194    1747346979410067712
16195    1629180709255479296
16196    1629180709255479296
16197    1629180709255479296
16198    1629180709255479296
Name: unit_id, Length: 16199, dtype: object

In [5]:
### Prep Qualtrics data for merging

In [7]:
before = pd.read_csv('data/Qualtrics_data_exports/before_October 21, 2024_06.32.csv', skiprows=[1,2])
after = pd.read_csv('data/Qualtrics_data_exports/after_October 21, 2024_06.31.csv', skiprows=[1,2])
before_before = pd.read_csv('data/Qualtrics_data_exports/start_survey_tryout_October 21, 2024_06.30.csv', skiprows=[1,2])
before_after = pd.merge(before, after, on='uid')
before_before['StartDate_First'] = before_before['StartDate']

In [8]:
print(len(before_after))
qualtrics_merged = pd.merge(before_before, before_after, on='psid')
print(len(qualtrics_merged))

1527
1506

In [9]:
df['time_answer'][0]

'2024-10-14T09:25:06.958Z'

In [10]:
annotinder_df['coder_id'].unique()

array([12149, 12158, 12159, ..., 16353, 16395, 16435])

In [31]:
df = pd.merge(annotinder_df, qualtrics_merged, on='uid', how='left')
#df = pd.merge(df_annotinder_qualtrics, X_data, on='unit_id_digits', how='left')

In [12]:
len(df['uid'].unique())

1461

In [13]:
from datetime import datetime, timedelta, timezone

# Function to handle NaN or non-string values and calculate differences
def calculate_time_differences_fixed_mdt(start_dates, time_answers):
    differences = []
    
    for start, answer in zip(start_dates, time_answers):
        # Ensure both start and answer are strings and handle missing values
        if pd.isnull(start) or pd.isnull(answer):
            differences.append(None)  # Skip if any value is missing
            continue
        
        try:
            # Parse StartDate_y (assuming it's in MDT, which is UTC-6)
            start_dt = datetime.strptime(str(start), '%Y-%m-%d %H:%M:%S')
            
            # Convert MDT to UTC by adding 6 hours, and make it timezone-aware (UTC)
            start_dt_utc = (start_dt + timedelta(hours=6)).replace(tzinfo=timezone.utc)
            
            # Parse time_answer (already in UTC, so timezone-aware)
            answer_dt = datetime.strptime(str(answer), '%Y-%m-%dT%H:%M:%S.%fZ').replace(tzinfo=timezone.utc)
            
            # Calculate the time difference in minutes
            time_diff = (answer_dt - start_dt_utc).total_seconds() / 60
            differences.append(time_diff)
        except Exception as e:
            differences.append(None)  # Handle errors and malformed data
    
    return differences


time_differences = calculate_time_differences_fixed_mdt(df['StartDate_First'], df['time_answer'])

In [33]:
import pandas as pd
from datetime import datetime, timedelta, timezone


# Function to handle NaN or non-string values and calculate differences
def calculate_time_differences_fixed_mdt(group):
    start_dates = group['StartDate_First']
    time_answers = group['time_answer']
    
    differences = []
    first_time = None
    end_time = None

    # Loop through each pair of start and answer
    for start, answer in zip(start_dates, time_answers):
        # Ensure both start and answer are strings and handle missing values
        if pd.isnull(start) or pd.isnull(answer):
            differences.append(None)  # Skip if any value is missing
            continue
        
        try:
            # Parse StartDate_y (assuming it's in MDT, which is UTC-6)
            start_dt = datetime.strptime(str(start), '%Y-%m-%d %H:%M:%S')
            
            # Convert MDT to UTC by adding 6 hours, and make it timezone-aware (UTC)
            start_dt_utc = (start_dt + timedelta(hours=6)).replace(tzinfo=timezone.utc)
            
            # Parse time_answer (already in UTC, so timezone-aware)
            answer_dt = datetime.strptime(str(answer), '%Y-%m-%dT%H:%M:%S.%fZ').replace(tzinfo=timezone.utc)
            
            # Calculate the time difference in minutes
            time_diff = (answer_dt - start_dt_utc).total_seconds() / 60
            differences.append(time_diff)
            
            # Update first_time and end_time
            if first_time is None:
                first_time = start_dt_utc
            end_time = answer_dt  # This will keep getting updated
        
        except Exception as e:
            differences.append(None)  # Handle errors and malformed data
    
    # Create a DataFrame for the results
    result_df = pd.DataFrame({
        'psid': group['psid'].iloc[0],  # Use the first psid from the group
        'first_time': first_time,
        'end_time': end_time,
        'time_difference': differences
    })
    
    return result_df

# Apply the function to each psid group and combine results into a single DataFrame
final_results = df.groupby('psid').apply(calculate_time_differences_fixed_mdt).reset_index(drop=True)

# Display the final DataFrame with psid, first_time, end_time, and time_difference

In [76]:
# Keep only the last observation for each psid
final_results = final_results.groupby('psid').last().reset_index()
final_results['psid'].to_csv('final_psid.csv')

In [39]:
final_results[['psid', 'first_time', 'end_time', 'time_difference']]
# Calculate mean, median, and 80th percentile of time_difference for each psid
# Calculate overall mean, median, and 80th percentile of time_difference
overall_statistics = {
    'mean': final_results['time_difference'].mean(),
    'median': final_results['time_difference'].median(),
    '80th_percentile': final_results['time_difference'].quantile(0.8)
}

# Display the overall statistics
print("\nOverall Statistics of Time Differences:")
print(overall_statistics)

Overall Statistics of Time Differences:
{'mean': 42.58804138733706, 'median': 24.624091666666665, '80th_percentile': 38.39157}

In [30]:
final_results['psid']

0    1
1    1
2    1
3    2
4    2
Name: psid, dtype: object

In [14]:
len(time_differences)
df['time_difference'] = time_differences

In [15]:
df[['uid','time_difference']]

           uid  time_difference
0       266019         9.879283
1       265991        12.443767
2       266019         9.910000
3       266019        10.258633
4       266019        10.352917
...        ...              ...
169322  268176       446.474067
169323  268176       446.582183
169324  268176       447.048133
169325  268176       447.082100
169326  268176       447.131867

[169327 rows x 2 columns]

In [47]:
annotinder_df['value'].unique()

array(['confirmed', 'Waar', 'Niet waar', 'Gedeeltelijk waar',
       'Gedeeltelijk niet waar', 'Neutraal', 'Helemaal waar',
       'Helemaal niet waar'], dtype=object)

In [56]:
# Define the mapping for the categorical values
mapping = {
    'Helemaal waar': 5,
    'Gedeeltelijk waar': 4,
    'Neutraal': 3,
    'Gedeeltelijk niet waar':2,
    'Helemaal niet waar': 1,
}

# Map the categorical values to numerical ones
df['value_encoded'] = df['value'].map(mapping)

dsc =  df[df['variable'] == 'stellingen.toxic']['dsc']
toxic = df[df['variable'] == 'stellingen.toxic']['value_encoded']

,coder_id,coder,jobset,unit_id,unit_status,variable,value,time_question,time_answer,field,...,Q6_Last Click,Q6_Page Submit,Q6_Click Count,sid_y,project_y,dsc,dst,Condition,IP_Address_y,value_encoded
0,12149,266019,batch_2,welkom,DONE,confirm,confirmed,2024-10-14T09:26:10.051Z,2024-10-14T09:27:33.757Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.867309,1.0,1.0,89.205.130.4,NaN
1,12158,265991,batch_3,welkom,DONE,confirm,confirmed,2024-10-14T09:27:33.001Z,2024-10-14T09:28:10.626Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.362579,1.0,1.0,95.98.90.232,NaN
2,12149,266019,batch_2,welkom2,DONE,confirm,confirmed,2024-10-14T09:27:34.676Z,2024-10-14T09:27:35.600Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.867309,1.0,1.0,89.205.130.4,NaN
3,12149,266019,batch_2,test vraag 1,DONE,political_stance_training,Waar,2024-10-14T09:27:36.448Z,2024-10-14T09:27:56.518Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.867309,1.0,1.0,89.205.130.4,NaN
4,12149,266019,batch_2,test vraag 1,DONE,sentiment_training,Waar,2024-10-14T09:27:56.985Z,2024-10-14T09:28:02.175Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.867309,1.0,1.0,89.205.130.4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169322,16203,268176,batch_53,1509397498078580736,DONE,stellingen.misinformation,Helemaal niet waar,2024-10-17T20:45:25.481Z,2024-10-17T20:45:48.444Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.640905,1.0,6.0,85.148.147.92,1.0
169323,16203,268176,batch_53,1616458348118810624,DONE,stellingen.political_stance,Neutraal,2024-10-17T20:45:50.683Z,2024-10-17T20:45:54.931Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.640905,1.0,6.0,85.148.147.92,3.0
169324,16203,268176,batch_53,1616458348118810624,DONE,stellingen.sentiment,Helemaal niet waar,2024-10-17T20:45:50.683Z,2024-10-17T20:46:22.888Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.640905,1.0,6.0,85.148.147.92,1.0
169325,16203,268176,batch_53,1616458348118810624,DONE,stellingen.toxic,Helemaal niet waar,2024-10-17T20:45:50.683Z,2024-10-17T20:46:24.926Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.640905,1.0,6.0,85.148.147.92,1.0
169326,16203,268176,batch_53,1616458348118810624,DONE,stellingen.misinformation,Helemaal niet waar,2024-10-17T20:45:50.683Z,2024-10-17T20:46:27.912Z,NaN,...,NaN,NaN,NaN,8554_5150,IAT_2024,0.640905,1.0,6.0,85.148.147.92,1.0

In [69]:
# Drop rows where 'value_encoded' or 'dsc' is NaN (if any NaNs exist)
valid_mask = dsc.notna() & toxic.notna()
dsc_clean = dsc[valid_mask]
toxic_clean = toxic[valid_mask]

# Calculate Pearson correlation
from scipy.stats import pearsonr
pearson_corr, _ = pearsonr(dsc_clean, toxic_clean)
print(f'Pearson correlation: {pearson_corr}')

Pearson correlation: -0.038764031418008535

In [65]:
len(dsc[:500]) == len(toxic[:500])

True

In [ ]:
import numpy as np


# Drop rows where either 'dsc' or 'toxic' contains NaN or Inf values
clean_df = annotinder_df[np.isfinite(annotinder_df['dsc']) & np.isfinite(annotinder_df['toxic'])]

# Now calculate the Pearson correlation
from scipy.stats import pearsonr

pearson_corr, _ = pearsonr(clean_df['dsc'], clean_df['toxic'])
print(f'Pearson correlation: {pearson_corr}')

In [68]:
for i in print(toxic):
    print(i)

26        4.0
31        4.0
35        4.0
40        3.0
52        4.0
         ...
169309    3.0
169313    3.0
169317    3.0
169321    3.0
169325    1.0
Name: value_encoded, Length: 38425, dtype: float64

TypeError: 'NoneType' object is not iterable

In [66]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr

# Calculate Pearson correlation
pearson_corr, _ = pearsonr(dsc[:500], toxic[:500])
print(f'Pearson correlation: {pearson_corr}')

ValueError: array must not contain infs or NaNs

In [16]:
df = df.sort_values(by=['psid', 'time_answer'])
last_observation = df.groupby('psid').last().reset_index()
last_observation[['psid', 'time_difference']]

                          psid  time_difference
0     _1KUVoNGiAg-FXLYMSdwbQ**        26.213683
1     _1KUVoNGiAg-GTXuLE-E1g**       158.219017
2     _1KUVoNGiAg-ODrdbezcMw**        30.623817
3     _1KUVoNGiAg-d35IGIrcEA**        32.588867
4     _1KUVoNGiAg0OjdoLHQ17Q**       228.668833
...                        ...              ...
1427  _1KUVoNGiAjyy-x0jm2qrw**        24.002267
1428  _1KUVoNGiAjz-R_IQlXnww**        16.613133
1429  _1KUVoNGiAjz9z84bgIj8Q**        22.783517
1430  _1KUVoNGiAjzcvail1lDPA**        24.716950
1431  _1KUVoNGiAjzeHozgt9H4w**        10.596833

[1432 rows x 2 columns]

In [ ]:

# Ensure the DataFrame is sorted by psid and time_answer
df['time_answer'] = pd.to_datetime(df['time_answer'])
df = df.sort_values(by=['psid', 'time_answer'])

# Function to calculate the time difference and capture first and last times
def calculate_time_diff(group):
    # Get the first and last time_answer for each group (psid)
    first_time = group['time_answer'].iloc[0]
    last_time = group['time_answer'].iloc[-1]
    
    # Calculate the difference in minutes
    time_difference = (last_time - first_time).total_seconds() / 60
    
    # Create a new DataFrame with the required columns
    result = pd.DataFrame({
        'psid': group['psid'].iloc[0],  # get psid from the group
        'first_time': first_time,
        'end_time': last_time,
        'time_difference': time_difference
    }, index=[0])  # Set index to 0 to return a single row DataFrame
    
    return result

# Apply the function to each psid group and combine results into a single DataFrame
last_observation = df.groupby('psid').apply(calculate_time_diff).reset_index(drop=True)

In [17]:
# Ensure the DataFrame is sorted by psid and time_answer
df = df.sort_values(by=['psid', 'time_answer'])

# Function to calculate the time difference between the latest and first time_answer
def calculate_time_diff(group):
    # Get the first and last time_answer for each group (psid)
    first_time = group['time_answer'].iloc[0]
    print(f"first time: {first_time}")
    last_time = group['time_answer'].iloc[-1]
    print(f"last time: {last_time}")
    # Convert to datetime objects
    first_time = pd.to_datetime(first_time)
    last_time = pd.to_datetime(last_time)
    
    # Calculate the difference in minutes
    group['time_difference'] = (last_time - first_time).total_seconds() / 60
    return group

# Apply the function to each psid group and get the latest observation with time difference
df = df.groupby('psid').apply(calculate_time_diff)
last_observation = df.groupby('psid').last().reset_index()

# Display the final DataFrame with psid and time_difference
last_observation[['psid', 'time_difference']]

first time: 2024-10-16T17:33:13.655Z
last time: 2024-10-16T17:48:58.821Z
first time: 2024-10-15T09:37:12.479Z
last time: 2024-10-15T12:03:48.141Z
first time: 2024-10-16T12:38:05.734Z
last time: 2024-10-16T12:53:27.429Z
first time: 2024-10-16T16:36:58.949Z
last time: 2024-10-16T16:50:38.332Z
first time: 2024-10-16T18:00:13.400Z
last time: 2024-10-16T18:12:45.130Z
first time: 2024-10-16T12:35:08.719Z
last time: 2024-10-16T13:03:57.076Z
first time: 2024-10-16T23:01:15.381Z
last time: 2024-10-16T23:11:59.252Z
first time: 2024-10-16T20:58:10.343Z
last time: 2024-10-16T21:01:55.503Z
first time: 2024-10-17T16:44:48.928Z
last time: 2024-10-17T16:57:29.664Z
first time: 2024-10-16T14:17:59.911Z
last time: 2024-10-16T14:25:24.185Z
first time: 2024-10-17T17:55:34.699Z
last time: 2024-10-17T17:56:52.405Z
first time: 2024-10-17T02:26:12.570Z
last time: 2024-10-17T02:41:04.287Z
first time: 2024-10-14T09:26:07.526Z
last time: 2024-10-14T09:34:08.632Z
first time: 2024-10-16T16:13:12.718Z
last time: 2024-10-16T16:29:53.728Z
first time: 2024-10-16T21:40:46.477Z
last time: 2024-10-16T21:40:49.960Z
first time: 2024-10-16T14:31:39.492Z
last time: 2024-10-16T14:34:44.535Z
first time: 2024-10-16T19:54:33.290Z
last time: 2024-10-16T19:56:04.012Z
first time: 2024-10-14T10:16:12.028Z
last time: 2024-10-14T10:33:53.299Z
first time: 2024-10-14T10:19:52.943Z
last time: 2024-10-14T10:32:12.482Z
first time: 2024-10-16T17:42:52.083Z
last time: 2024-10-16T20:17:51.915Z
first time: 2024-10-16T19:23:11.969Z
last time: 2024-10-16T19:39:22.551Z
first time: 2024-10-16T12:30:24.675Z
last time: 2024-10-16T12:43:52.025Z
first time: 2024-10-16T16:05:18.700Z
last time: 2024-10-16T16:06:21.665Z
first time: 2024-10-15T09:52:23.659Z
last time: 2024-10-15T10:05:39.179Z
first time: 2024-10-17T16:02:44.156Z
last time: 2024-10-17T16:11:22.767Z
first time: 2024-10-16T18:30:05.478Z
last time: 2024-10-16T18:44:18.244Z
first time: 2024-10-16T14:21:55.250Z
last time: 2024-10-16T14:41:56.915Z
first time: 2024-10-16T12:48:17.957Z
last time: 2024-10-16T12:54:05.274Z
first time: 2024-10-16T16:24:00.713Z
last time: 2024-10-16T16:38:52.493Z
first time: 2024-10-14T09:32:19.523Z
last time: 2024-10-14T09:40:35.173Z
first time: 2024-10-14T10:32:52.823Z
last time: 2024-10-14T10:47:26.753Z
first time: 2024-10-16T20:07:16.410Z
last time: 2024-10-16T20:10:28.295Z
first time: 2024-10-16T12:36:21.676Z
last time: 2024-10-16T12:45:26.858Z
first time: 2024-10-16T12:20:35.095Z
last time: 2024-10-16T12:21:58.719Z
first time: 2024-10-16T15:17:17.850Z
last time: 2024-10-16T16:27:34.377Z
first time: 2024-10-16T14:58:47.445Z
last time: 2024-10-16T15:02:51.498Z
first time: 2024-10-17T13:38:38.086Z
last time: 2024-10-17T13:57:35.285Z
first time: 2024-10-16T18:54:01.757Z
last time: 2024-10-16T18:59:16.961Z
first time: 2024-10-16T19:54:59.115Z
last time: 2024-10-16T19:56:12.452Z
first time: 2024-10-16T17:27:56.234Z
last time: 2024-10-16T17:30:39.391Z
first time: 2024-10-16T12:19:36.901Z
last time: 2024-10-16T12:21:06.378Z
first time: 2024-10-17T14:07:24.384Z
last time: 2024-10-17T14:23:54.005Z
first time: 2024-10-16T16:59:02.471Z
last time: 2024-10-16T17:16:06.962Z
first time: 2024-10-14T09:28:13.229Z
last time: 2024-10-14T09:32:44.435Z
first time: 2024-10-16T17:02:29.796Z
last time: 2024-10-16T17:07:27.295Z
first time: 2024-10-16T13:21:23.478Z
last time: 2024-10-16T13:29:11.533Z
first time: 2024-10-17T13:21:53.363Z
last time: 2024-10-17T13:25:33.228Z
first time: 2024-10-17T09:03:02.745Z
last time: 2024-10-17T09:16:27.512Z
first time: 2024-10-17T08:18:56.319Z
last time: 2024-10-17T08:19:43.662Z
first time: 2024-10-16T18:48:30.506Z
last time: 2024-10-16T19:40:34.975Z
first time: 2024-10-16T21:48:25.873Z
last time: 2024-10-16T22:18:00.060Z
first time: 2024-10-16T18:34:27.224Z
last time: 2024-10-16T18:47:27.916Z
first time: 2024-10-16T20:06:25.977Z
last time: 2024-10-16T21:10:42.893Z
first time: 2024-10-16T19:28:54.313Z
last time: 2024-10-16T19:36:09.459Z
first time: 2024-10-16T19:54:46.750Z
last time: 2024-10-16T20:04:06.638Z
first time: 2024-10-16T16:48:50.672Z
last time: 2024-10-16T17:07:11.354Z
first time: 2024-10-16T19:09:34.810Z
last time: 2024-10-16T19:25:25.955Z
first time: 2024-10-16T17:21:25.970Z
last time: 2024-10-16T17:25:21.143Z
first time: 2024-10-16T17:39:43.937Z
last time: 2024-10-16T17:58:54.315Z
first time: 2024-10-17T12:55:36.873Z
last time: 2024-10-17T13:02:20.640Z
first time: 2024-10-16T22:38:35.413Z
last time: 2024-10-16T22:50:33.222Z
first time: 2024-10-16T14:53:31.108Z
last time: 2024-10-16T15:11:39.106Z
first time: 2024-10-17T15:30:58.482Z
last time: 2024-10-17T16:39:01.870Z
first time: 2024-10-16T15:16:58.649Z
last time: 2024-10-16T15:49:37.617Z
first time: 2024-10-16T12:27:49.763Z
last time: 2024-10-16T12:42:15.164Z
first time: 2024-10-14T09:32:24.586Z
last time: 2024-10-14T09:57:52.620Z
first time: 2024-10-17T13:59:22.224Z
last time: 2024-10-17T14:40:52.574Z
first time: 2024-10-17T07:38:46.724Z
last time: 2024-10-17T07:55:27.895Z
first time: 2024-10-16T21:26:15.211Z
last time: 2024-10-16T21:29:04.433Z
first time: 2024-10-14T09:33:33.972Z
last time: 2024-10-14T09:47:38.022Z
first time: 2024-10-16T14:37:52.293Z
last time: 2024-10-16T14:48:59.464Z
first time: 2024-10-17T14:45:13.661Z
last time: 2024-10-17T14:52:45.621Z
first time: 2024-10-16T17:41:21.316Z
last time: 2024-10-16T17:55:19.607Z
first time: 2024-10-16T15:20:55.565Z
last time: 2024-10-16T15:20:55.565Z
first time: 2024-10-16T19:45:22.071Z
last time: 2024-10-16T20:12:32.291Z
first time: 2024-10-16T13:34:22.381Z
last time: 2024-10-16T13:35:08.805Z
first time: 2024-10-17T09:36:05.638Z
last time: 2024-10-17T09:46:58.223Z
first time: 2024-10-16T17:50:49.006Z
last time: 2024-10-16T17:51:26.166Z
first time: 2024-10-16T18:11:52.748Z
last time: 2024-10-16T18:13:17.447Z
first time: 2024-10-16T20:25:41.176Z
last time: 2024-10-16T20:39:40.100Z
first time: 2024-10-16T16:20:41.208Z
last time: 2024-10-16T16:26:57.768Z
first time: 2024-10-16T17:22:12.658Z
last time: 2024-10-16T17:37:51.877Z
first time: 2024-10-17T08:41:50.274Z
last time: 2024-10-17T09:01:47.660Z
first time: 2024-10-16T21:01:43.895Z
last time: 2024-10-16T21:05:36.586Z
first time: 2024-10-15T09:32:54.474Z
last time: 2024-10-15T09:39:34.618Z
first time: 2024-10-16T14:25:59.231Z
last time: 2024-10-16T14:54:17.178Z
first time: 2024-10-16T16:48:55.545Z
last time: 2024-10-16T17:26:57.936Z
first time: 2024-10-16T13:36:34.984Z
last time: 2024-10-16T13:38:25.109Z
first time: 2024-10-15T09:29:00.939Z
last time: 2024-10-15T09:57:15.149Z
first time: 2024-10-16T15:39:07.200Z
last time: 2024-10-16T15:49:47.460Z
first time: 2024-10-16T12:28:48.280Z
last time: 2024-10-16T12:46:10.687Z
first time: 2024-10-17T13:45:50.211Z
last time: 2024-10-17T13:51:33.387Z
first time: 2024-10-16T14:18:33.832Z
last time: 2024-10-16T14:22:21.438Z
first time: 2024-10-16T14:33:51.941Z
last time: 2024-10-16T14:52:42.274Z
first time: 2024-10-17T15:05:23.235Z
last time: 2024-10-17T15:25:15.704Z
first time: 2024-10-16T15:38:39.352Z
last time: 2024-10-16T15:52:31.679Z
first time: 2024-10-16T19:09:46.246Z
last time: 2024-10-16T19:21:03.723Z
first time: 2024-10-16T18:15:45.898Z
last time: 2024-10-16T19:46:55.626Z
first time: 2024-10-16T14:22:57.512Z
last time: 2024-10-16T14:30:18.321Z
first time: 2024-10-15T09:31:21.363Z
last time: 2024-10-15T09:44:54.192Z
first time: 2024-10-16T20:36:35.371Z
last time: 2024-10-16T20:51:24.726Z
first time: 2024-10-17T09:24:26.200Z
last time: 2024-10-17T09:33:37.995Z
first time: 2024-10-16T21:06:11.705Z
last time: 2024-10-16T21:07:05.910Z
first time: 2024-10-16T16:41:18.820Z
last time: 2024-10-16T16:48:31.141Z
first time: 2024-10-14T11:09:06.550Z
last time: 2024-10-14T11:12:59.689Z
first time: 2024-10-16T14:57:57.437Z
last time: 2024-10-16T15:08:21.654Z
first time: 2024-10-16T12:17:06.681Z
last time: 2024-10-16T12:24:48.279Z
first time: 2024-10-15T09:27:25.368Z
last time: 2024-10-15T09:41:11.823Z
first time: 2024-10-16T13:58:22.170Z
last time: 2024-10-16T14:12:44.105Z
first time: 2024-10-16T18:28:45.995Z
last time: 2024-10-16T18:44:42.811Z
first time: 2024-10-16T18:57:36.231Z
last time: 2024-10-16T19:14:53.497Z
first time: 2024-10-16T12:53:20.357Z
last time: 2024-10-16T13:06:35.781Z
first time: 2024-10-16T16:29:29.789Z
last time: 2024-10-16T16:45:10.919Z
first time: 2024-10-16T12:25:54.040Z
last time: 2024-10-16T12:39:51.138Z
first time: 2024-10-16T13:21:44.029Z
last time: 2024-10-16T13:24:59.562Z
first time: 2024-10-14T09:26:59.749Z
last time: 2024-10-14T09:43:08.798Z
first time: 2024-10-14T09:31:56.230Z
last time: 2024-10-14T09:43:40.960Z
first time: 2024-10-15T09:30:47.985Z
last time: 2024-10-15T09:43:05.802Z
first time: 2024-10-16T19:01:40.510Z
last time: 2024-10-16T20:31:19.523Z
first time: 2024-10-16T19:48:29.255Z
last time: 2024-10-16T20:02:57.999Z
first time: 2024-10-16T15:51:16.197Z
last time: 2024-10-16T16:11:31.710Z
first time: 2024-10-14T09:27:02.253Z
last time: 2024-10-14T09:37:06.586Z
first time: 2024-10-16T20:41:37.457Z
last time: 2024-10-16T21:18:49.105Z
first time: 2024-10-16T14:19:13.731Z
last time: 2024-10-16T14:43:24.342Z
first time: 2024-10-15T09:29:18.686Z
last time: 2024-10-15T09:40:35.123Z
first time: 2024-10-16T12:19:59.452Z
last time: 2024-10-16T12:25:31.186Z
first time: 2024-10-17T13:09:55.278Z
last time: 2024-10-17T13:13:11.463Z
first time: 2024-10-14T09:39:36.737Z
last time: 2024-10-14T09:53:10.711Z
first time: 2024-10-16T13:42:29.950Z
last time: 2024-10-16T13:55:40.635Z
first time: 2024-10-16T21:36:07.966Z
last time: 2024-10-16T21:43:59.087Z
first time: 2024-10-14T09:33:14.252Z
last time: 2024-10-14T09:39:37.652Z
first time: 2024-10-17T13:47:24.592Z
last time: 2024-10-17T13:50:56.577Z
first time: 2024-10-17T08:50:38.313Z
last time: 2024-10-17T08:51:11.718Z
first time: 2024-10-17T16:10:06.625Z
last time: 2024-10-17T16:15:40.842Z
first time: 2024-10-16T14:28:46.909Z
last time: 2024-10-16T14:34:06.701Z
first time: 2024-10-16T18:26:19.298Z
last time: 2024-10-16T18:38:16.995Z
first time: 2024-10-17T12:43:01.312Z
last time: 2024-10-17T12:52:42.704Z
first time: 2024-10-16T12:30:24.686Z
last time: 2024-10-16T12:39:06.029Z
first time: 2024-10-15T09:40:19.196Z
last time: 2024-10-15T10:23:14.261Z
first time: 2024-10-17T13:21:08.289Z
last time: 2024-10-17T13:35:02.396Z
first time: 2024-10-16T23:18:17.994Z
last time: 2024-10-16T23:29:39.633Z
first time: 2024-10-16T21:04:07.880Z
last time: 2024-10-16T21:11:05.888Z
first time: 2024-10-16T18:25:42.138Z
last time: 2024-10-16T18:41:25.322Z
first time: 2024-10-16T14:23:12.159Z
last time: 2024-10-16T14:53:37.160Z
first time: 2024-10-16T17:33:01.322Z
last time: 2024-10-16T17:34:08.525Z
first time: 2024-10-14T09:30:25.919Z
last time: 2024-10-14T09:40:27.908Z
first time: 2024-10-16T21:02:13.603Z
last time: 2024-10-16T21:05:15.877Z
first time: 2024-10-16T12:43:25.163Z
last time: 2024-10-16T12:52:54.570Z
first time: 2024-10-16T17:32:13.187Z
last time: 2024-10-16T17:51:03.995Z
first time: 2024-10-16T15:39:01.962Z
last time: 2024-10-16T15:41:56.611Z
first time: 2024-10-16T21:09:01.393Z
last time: 2024-10-16T21:24:08.890Z
first time: 2024-10-16T20:39:51.999Z
last time: 2024-10-16T20:51:24.316Z
first time: 2024-10-14T09:34:00.740Z
last time: 2024-10-14T10:42:20.130Z
first time: 2024-10-16T19:02:52.374Z
last time: 2024-10-16T19:20:36.251Z
first time: 2024-10-17T13:21:17.466Z
last time: 2024-10-17T13:38:16.385Z
first time: 2024-10-17T07:36:29.405Z
last time: 2024-10-17T07:46:12.489Z
first time: 2024-10-17T13:36:58.987Z
last time: 2024-10-17T13:39:17.031Z
first time: 2024-10-14T10:16:21.092Z
last time: 2024-10-14T10:32:29.963Z
first time: 2024-10-16T17:36:04.704Z
last time: 2024-10-16T18:33:05.704Z
first time: 2024-10-14T09:49:22.393Z
last time: 2024-10-14T09:57:43.124Z
first time: 2024-10-17T03:55:52.986Z
last time: 2024-10-17T05:09:16.058Z
first time: 2024-10-16T17:20:39.591Z
last time: 2024-10-16T17:36:01.330Z
first time: 2024-10-16T17:15:06.130Z
last time: 2024-10-16T17:28:07.307Z
first time: 2024-10-16T18:35:47.650Z
last time: 2024-10-16T18:45:14.227Z
first time: 2024-10-16T18:05:36.078Z
last time: 2024-10-16T18:08:04.760Z
first time: 2024-10-16T17:51:53.445Z
last time: 2024-10-16T18:02:03.477Z
first time: 2024-10-16T12:20:28.679Z
last time: 2024-10-16T12:31:59.116Z
first time: 2024-10-16T15:18:50.888Z
last time: 2024-10-16T15:33:39.820Z
first time: 2024-10-16T16:15:46.778Z
last time: 2024-10-16T16:30:54.261Z
first time: 2024-10-16T19:44:38.629Z
last time: 2024-10-16T20:04:58.689Z
first time: 2024-10-17T12:50:55.295Z
last time: 2024-10-17T12:54:07.908Z
first time: 2024-10-16T15:19:25.309Z
last time: 2024-10-16T15:26:04.531Z
first time: 2024-10-17T13:11:15.549Z
last time: 2024-10-17T13:13:00.370Z
first time: 2024-10-17T09:34:34.887Z
last time: 2024-10-17T09:41:26.183Z
first time: 2024-10-17T15:46:11.034Z
last time: 2024-10-17T15:49:44.710Z
first time: 2024-10-17T12:40:37.554Z
last time: 2024-10-17T13:03:46.512Z
first time: 2024-10-16T13:22:32.726Z
last time: 2024-10-16T13:52:19.168Z
first time: 2024-10-16T16:37:57.808Z
last time: 2024-10-16T16:38:25.159Z
first time: 2024-10-17T07:50:24.657Z
last time: 2024-10-17T07:53:47.837Z
first time: 2024-10-16T13:34:16.892Z
last time: 2024-10-16T13:36:27.782Z
first time: 2024-10-16T17:02:28.554Z
last time: 2024-10-16T17:11:15.153Z
first time: 2024-10-16T15:19:26.687Z
last time: 2024-10-16T15:34:31.078Z
first time: 2024-10-17T16:29:29.978Z
last time: 2024-10-17T16:36:37.731Z
first time: 2024-10-16T14:49:51.194Z
last time: 2024-10-16T20:35:35.816Z
first time: 2024-10-15T09:31:44.568Z
last time: 2024-10-15T09:36:10.539Z
first time: 2024-10-16T18:15:29.244Z
last time: 2024-10-16T18:19:50.522Z
first time: 2024-10-16T13:18:15.871Z
last time: 2024-10-16T13:29:46.583Z
first time: 2024-10-14T09:45:39.014Z
last time: 2024-10-14T10:16:05.070Z
first time: 2024-10-15T09:36:19.342Z
last time: 2024-10-15T10:21:24.860Z
first time: 2024-10-17T07:57:37.851Z
last time: 2024-10-17T08:09:34.314Z
first time: 2024-10-17T05:10:55.429Z
last time: 2024-10-17T05:43:25.003Z
first time: 2024-10-16T12:16:27.128Z
last time: 2024-10-16T12:39:18.189Z
first time: 2024-10-16T14:31:07.043Z
last time: 2024-10-16T14:44:27.010Z
first time: 2024-10-16T12:26:21.364Z
last time: 2024-10-16T12:31:08.774Z
first time: 2024-10-16T19:50:45.056Z
last time: 2024-10-16T20:07:38.436Z
first time: 2024-10-16T15:33:32.850Z
last time: 2024-10-16T15:42:27.649Z
first time: 2024-10-14T09:38:33.844Z
last time: 2024-10-14T09:49:41.333Z
first time: 2024-10-16T16:53:58.772Z
last time: 2024-10-16T16:58:53.693Z
first time: 2024-10-16T16:09:06.684Z
last time: 2024-10-16T17:01:05.297Z
first time: 2024-10-16T14:03:16.041Z
last time: 2024-10-16T14:07:38.005Z
first time: 2024-10-17T05:08:32.672Z
last time: 2024-10-17T05:10:53.853Z
first time: 2024-10-17T18:48:56.402Z
last time: 2024-10-17T19:01:15.130Z
first time: 2024-10-17T07:26:13.681Z
last time: 2024-10-17T08:14:30.680Z
first time: 2024-10-16T16:25:21.343Z
last time: 2024-10-16T16:30:07.819Z
first time: 2024-10-16T19:24:44.541Z
last time: 2024-10-16T19:28:50.237Z
first time: 2024-10-16T16:34:25.615Z
last time: 2024-10-16T16:46:16.566Z
first time: 2024-10-17T04:09:31.591Z
last time: 2024-10-17T04:13:25.516Z
first time: 2024-10-16T15:17:30.666Z
last time: 2024-10-16T15:27:17.854Z
first time: 2024-10-17T12:52:24.899Z
last time: 2024-10-17T12:57:14.537Z
first time: 2024-10-17T01:20:57.400Z
last time: 2024-10-17T01:28:18.039Z
first time: 2024-10-17T08:22:16.077Z
last time: 2024-10-17T08:41:25.124Z
first time: 2024-10-14T09:28:04.782Z
last time: 2024-10-14T09:40:42.055Z
first time: 2024-10-17T09:36:57.609Z
last time: 2024-10-17T09:49:37.813Z
first time: 2024-10-17T07:38:32.027Z
last time: 2024-10-17T07:48:00.919Z
first time: 2024-10-16T12:46:01.689Z
last time: 2024-10-16T12:48:50.747Z
first time: 2024-10-16T16:12:10.935Z
last time: 2024-10-16T16:26:34.765Z
first time: 2024-10-16T12:36:28.021Z
last time: 2024-10-16T12:51:20.045Z
first time: 2024-10-14T09:27:50.396Z
last time: 2024-10-14T09:47:40.786Z
first time: 2024-10-17T15:24:29.161Z
last time: 2024-10-17T15:24:33.362Z
first time: 2024-10-16T21:41:44.680Z
last time: 2024-10-16T22:14:31.425Z
first time: 2024-10-16T13:28:05.559Z
last time: 2024-10-16T13:40:42.228Z
first time: 2024-10-16T16:48:41.197Z
last time: 2024-10-16T16:57:32.110Z
first time: 2024-10-14T09:34:15.542Z
last time: 2024-10-14T09:51:15.104Z
first time: 2024-10-16T16:33:53.001Z
last time: 2024-10-16T16:55:22.772Z
first time: 2024-10-15T09:27:59.528Z
last time: 2024-10-15T09:36:12.787Z
first time: 2024-10-16T14:20:24.705Z
last time: 2024-10-16T14:27:12.507Z
first time: 2024-10-14T09:29:12.648Z
last time: 2024-10-14T09:33:29.367Z
first time: 2024-10-14T09:30:36.490Z
last time: 2024-10-14T09:56:58.411Z
first time: 2024-10-16T13:16:56.471Z
last time: 2024-10-16T13:32:42.399Z
first time: 2024-10-15T09:30:21.489Z
last time: 2024-10-15T09:36:47.062Z
first time: 2024-10-17T13:37:41.077Z
last time: 2024-10-17T13:38:38.246Z
first time: 2024-10-16T16:03:54.380Z
last time: 2024-10-16T16:16:48.766Z
first time: 2024-10-16T13:31:24.074Z
last time: 2024-10-16T13:37:49.239Z
first time: 2024-10-16T20:41:52.612Z
last time: 2024-10-16T20:51:09.695Z
first time: 2024-10-16T12:31:38.790Z
last time: 2024-10-16T12:36:52.125Z
first time: 2024-10-16T17:58:10.069Z
last time: 2024-10-16T18:17:13.747Z
first time: 2024-10-16T13:15:28.915Z
last time: 2024-10-16T13:24:59.449Z
first time: 2024-10-16T17:28:38.960Z
last time: 2024-10-16T17:42:59.263Z
first time: 2024-10-17T04:42:04.183Z
last time: 2024-10-17T04:44:31.816Z
first time: 2024-10-17T06:24:43.042Z
last time: 2024-10-17T06:33:21.043Z
first time: 2024-10-16T13:32:13.624Z
last time: 2024-10-16T13:39:56.618Z
first time: 2024-10-16T22:55:13.445Z
last time: 2024-10-16T22:56:30.070Z
first time: 2024-10-16T15:10:45.839Z
last time: 2024-10-16T15:15:57.987Z
first time: 2024-10-16T14:23:51.779Z
last time: 2024-10-16T14:26:30.911Z
first time: 2024-10-14T09:30:14.839Z
last time: 2024-10-14T10:02:50.516Z
first time: 2024-10-17T13:10:56.893Z
last time: 2024-10-17T13:14:08.419Z
first time: 2024-10-16T14:41:44.007Z
last time: 2024-10-16T14:53:42.752Z
first time: 2024-10-16T14:36:28.246Z
last time: 2024-10-16T14:51:40.873Z
first time: 2024-10-17T13:31:11.902Z
last time: 2024-10-17T13:42:59.643Z
first time: 2024-10-17T06:40:24.788Z
last time: 2024-10-17T06:54:47.419Z
first time: 2024-10-16T14:15:52.909Z
last time: 2024-10-16T14:21:51.357Z
first time: 2024-10-14T10:25:34.286Z
last time: 2024-10-14T10:53:04.383Z
first time: 2024-10-16T13:27:15.330Z
last time: 2024-10-16T13:36:16.466Z
first time: 2024-10-16T14:39:03.848Z
last time: 2024-10-16T15:00:33.814Z
first time: 2024-10-16T18:10:05.879Z
last time: 2024-10-16T18:53:30.675Z
first time: 2024-10-16T18:08:50.766Z
last time: 2024-10-16T18:16:56.005Z
first time: 2024-10-16T14:46:06.287Z
last time: 2024-10-16T14:48:54.494Z
first time: 2024-10-16T16:30:40.979Z
last time: 2024-10-16T16:48:46.481Z
first time: 2024-10-16T15:39:19.803Z
last time: 2024-10-16T15:44:23.601Z
first time: 2024-10-16T19:13:56.019Z
last time: 2024-10-16T19:35:35.117Z
first time: 2024-10-17T08:59:00.490Z
last time: 2024-10-17T09:10:07.282Z
first time: 2024-10-16T12:22:02.402Z
last time: 2024-10-16T12:26:47.148Z
first time: 2024-10-16T17:35:29.011Z
last time: 2024-10-16T17:35:59.103Z
first time: 2024-10-16T14:42:09.827Z
last time: 2024-10-16T14:54:36.030Z
first time: 2024-10-16T15:40:07.550Z
last time: 2024-10-16T15:53:05.420Z
first time: 2024-10-17T13:45:34.933Z
last time: 2024-10-17T13:49:10.423Z
first time: 2024-10-16T18:46:25.897Z
last time: 2024-10-16T18:48:18.581Z
first time: 2024-10-16T17:35:56.084Z
last time: 2024-10-16T17:47:10.945Z
first time: 2024-10-16T13:24:57.301Z
last time: 2024-10-16T13:43:11.156Z
first time: 2024-10-16T15:54:50.785Z
last time: 2024-10-16T16:10:45.845Z
first time: 2024-10-17T12:34:38.366Z
last time: 2024-10-17T12:53:15.986Z
first time: 2024-10-16T15:38:41.080Z
last time: 2024-10-16T15:38:50.503Z
first time: 2024-10-16T18:27:05.844Z
last time: 2024-10-16T18:36:30.075Z
first time: 2024-10-16T16:02:21.462Z

first time: 2024-10-16T13:31:50.944Z
last time: 2024-10-16T13:39:18.953Z
first time: 2024-10-17T14:48:14.960Z
last time: 2024-10-17T14:52:02.761Z
first time: 2024-10-16T13:58:50.625Z
last time: 2024-10-16T13:59:39.532Z
first time: 2024-10-16T14:52:55.897Z
last time: 2024-10-16T15:01:31.423Z
first time: 2024-10-16T21:28:43.836Z
last time: 2024-10-16T21:45:11.860Z
first time: 2024-10-15T09:37:24.406Z
last time: 2024-10-15T09:47:16.334Z
first time: 2024-10-16T18:59:33.106Z
last time: 2024-10-16T19:09:06.551Z
first time: 2024-10-16T14:01:46.072Z
last time: 2024-10-16T14:15:20.770Z
first time: 2024-10-16T20:35:50.132Z
last time: 2024-10-16T20:47:07.629Z
first time: 2024-10-16T12:34:58.462Z
last time: 2024-10-16T12:40:25.694Z
first time: 2024-10-17T04:43:20.119Z
last time: 2024-10-17T05:06:14.127Z
first time: 2024-10-16T15:50:49.912Z
last time: 2024-10-16T16:01:20.072Z
first time: 2024-10-16T15:39:56.504Z
last time: 2024-10-16T15:47:00.675Z
first time: 2024-10-16T21:08:54.149Z
last time: 2024-10-16T21:17:24.142Z
first time: 2024-10-16T18:02:15.489Z
last time: 2024-10-16T18:06:01.123Z
first time: 2024-10-16T14:46:59.274Z
last time: 2024-10-16T15:03:23.731Z
first time: 2024-10-16T12:41:14.080Z
last time: 2024-10-16T12:54:38.188Z
first time: 2024-10-16T14:14:21.656Z
last time: 2024-10-16T14:36:22.003Z
first time: 2024-10-16T12:36:40.421Z
last time: 2024-10-16T12:51:31.787Z
first time: 2024-10-17T17:04:09.436Z
last time: 2024-10-17T17:16:07.349Z
first time: 2024-10-17T09:10:13.499Z
last time: 2024-10-17T09:11:01.262Z
first time: 2024-10-17T08:23:32.773Z
last time: 2024-10-17T08:26:04.580Z
first time: 2024-10-16T23:02:21.698Z
last time: 2024-10-16T23:05:48.433Z
first time: 2024-10-16T12:34:28.300Z
last time: 2024-10-16T12:49:50.131Z
first time: 2024-10-16T16:11:51.524Z
last time: 2024-10-16T16:51:40.808Z
first time: 2024-10-16T15:01:00.812Z
last time: 2024-10-16T15:15:35.437Z
first time: 2024-10-16T14:46:15.523Z
last time: 2024-10-16T15:01:27.723Z
first time: 2024-10-17T14:12:11.271Z
last time: 2024-10-17T14:47:42.730Z
first time: 2024-10-16T18:55:57.209Z
last time: 2024-10-16T18:59:27.033Z
first time: 2024-10-16T16:55:52.562Z
last time: 2024-10-16T17:08:29.850Z
first time: 2024-10-16T13:24:30.034Z
last time: 2024-10-16T13:31:52.765Z
first time: 2024-10-16T17:13:46.325Z
last time: 2024-10-16T17:17:52.293Z
first time: 2024-10-14T09:34:33.725Z
last time: 2024-10-14T09:38:25.173Z
first time: 2024-10-16T12:20:23.247Z
last time: 2024-10-16T12:30:52.618Z
first time: 2024-10-16T16:39:00.697Z
last time: 2024-10-16T16:52:18.389Z
first time: 2024-10-17T17:18:07.798Z
last time: 2024-10-17T17:24:27.028Z
first time: 2024-10-16T15:17:12.682Z
last time: 2024-10-16T15:34:51.433Z
first time: 2024-10-17T06:27:57.145Z
last time: 2024-10-17T06:30:59.148Z
first time: 2024-10-15T09:33:48.575Z
last time: 2024-10-15T09:38:01.787Z
first time: 2024-10-16T19:34:51.076Z
last time: 2024-10-16T20:11:14.164Z
first time: 2024-10-16T15:03:03.424Z
last time: 2024-10-16T15:07:59.581Z
first time: 2024-10-17T15:07:01.991Z
last time: 2024-10-17T16:36:59.947Z
first time: 2024-10-17T09:27:10.188Z
last time: 2024-10-17T09:40:13.708Z
first time: 2024-10-16T14:19:28.013Z
last time: 2024-10-16T14:48:28.193Z
first time: 2024-10-16T14:32:01.173Z
last time: 2024-10-16T14:38:53.805Z
first time: 2024-10-15T09:30:30.479Z
last time: 2024-10-15T09:48:24.357Z
first time: 2024-10-16T13:34:19.805Z
last time: 2024-10-16T13:37:37.887Z
first time: 2024-10-16T18:57:18.398Z
last time: 2024-10-16T18:58:45.169Z
first time: 2024-10-14T09:29:21.948Z
last time: 2024-10-14T09:43:31.564Z
first time: 2024-10-16T18:30:56.646Z
last time: 2024-10-16T18:31:19.083Z
first time: 2024-10-17T13:08:14.822Z
last time: 2024-10-17T13:15:16.209Z
first time: 2024-10-16T18:30:03.270Z
last time: 2024-10-16T18:36:52.065Z
first time: 2024-10-16T13:57:06.174Z
last time: 2024-10-16T14:31:02.037Z
first time: 2024-10-17T13:46:24.654Z
last time: 2024-10-17T14:07:23.149Z
first time: 2024-10-16T16:46:00.771Z
last time: 2024-10-16T16:46:23.561Z
first time: 2024-10-16T12:27:18.883Z
last time: 2024-10-16T12:36:23.428Z
first time: 2024-10-14T10:18:42.875Z
last time: 2024-10-14T10:39:30.897Z
first time: 2024-10-17T09:36:39.202Z
last time: 2024-10-17T09:39:27.907Z
first time: 2024-10-16T12:29:05.873Z
last time: 2024-10-16T16:33:48.317Z
first time: 2024-10-16T13:21:14.044Z
last time: 2024-10-16T13:34:42.352Z
first time: 2024-10-17T13:02:54.230Z
last time: 2024-10-17T13:17:20.863Z
first time: 2024-10-16T17:09:09.685Z
last time: 2024-10-16T17:19:36.114Z
first time: 2024-10-16T13:20:30.028Z
last time: 2024-10-16T13:24:50.245Z
first time: 2024-10-17T12:40:49.466Z
last time: 2024-10-17T13:02:07.498Z
first time: 2024-10-17T07:40:28.287Z
last time: 2024-10-17T07:44:00.057Z
first time: 2024-10-17T14:19:43.164Z
last time: 2024-10-17T14:42:23.231Z
first time: 2024-10-16T12:43:21.065Z
last time: 2024-10-16T12:46:02.064Z
first time: 2024-10-16T13:27:22.218Z
last time: 2024-10-16T13:44:42.733Z
first time: 2024-10-16T17:28:00.618Z
last time: 2024-10-16T17:30:52.609Z
first time: 2024-10-17T14:10:43.552Z
last time: 2024-10-17T14:12:02.451Z
first time: 2024-10-14T10:16:37.630Z
last time: 2024-10-14T10:43:49.907Z
first time: 2024-10-16T12:16:37.817Z
last time: 2024-10-16T12:40:42.215Z
first time: 2024-10-16T18:31:24.937Z
last time: 2024-10-16T18:31:33.767Z
first time: 2024-10-17T13:56:03.641Z
last time: 2024-10-17T14:49:50.348Z
first time: 2024-10-16T16:13:23.163Z
last time: 2024-10-16T17:35:19.915Z
first time: 2024-10-16T18:24:12.966Z
last time: 2024-10-16T18:28:39.196Z
first time: 2024-10-16T15:24:16.222Z
last time: 2024-10-16T15:38:11.636Z
first time: 2024-10-16T14:08:19.879Z
last time: 2024-10-16T14:29:48.136Z
first time: 2024-10-16T16:40:10.554Z
last time: 2024-10-16T16:54:27.450Z
first time: 2024-10-14T09:33:45.230Z
last time: 2024-10-14T09:39:05.581Z
first time: 2024-10-17T12:46:05.257Z
last time: 2024-10-17T13:23:18.766Z
first time: 2024-10-17T09:30:33.800Z
last time: 2024-10-17T09:42:54.648Z
first time: 2024-10-15T09:38:35.676Z
last time: 2024-10-15T09:53:01.687Z
first time: 2024-10-17T04:41:14.038Z
last time: 2024-10-17T04:53:16.372Z
first time: 2024-10-16T15:57:29.541Z
last time: 2024-10-16T16:08:22.076Z
first time: 2024-10-16T14:50:53.758Z
last time: 2024-10-16T15:01:55.212Z
first time: 2024-10-14T10:25:03.022Z
last time: 2024-10-14T10:58:35.349Z
first time: 2024-10-17T09:10:43.306Z
last time: 2024-10-17T09:23:03.649Z
first time: 2024-10-17T09:33:18.205Z
last time: 2024-10-17T09:37:28.190Z
first time: 2024-10-17T15:49:23.294Z
last time: 2024-10-17T16:27:11.825Z
first time: 2024-10-16T16:42:46.303Z
last time: 2024-10-16T16:50:40.299Z
first time: 2024-10-16T12:30:08.754Z
last time: 2024-10-16T12:32:47.443Z
first time: 2024-10-17T08:23:40.597Z
last time: 2024-10-17T08:39:27.561Z
first time: 2024-10-14T09:46:40.387Z
last time: 2024-10-14T10:02:05.569Z
first time: 2024-10-16T21:42:51.820Z
last time: 2024-10-16T22:00:24.578Z
first time: 2024-10-17T12:32:39.012Z
last time: 2024-10-17T12:49:22.239Z
first time: 2024-10-14T10:27:52.207Z
last time: 2024-10-14T10:39:09.831Z
first time: 2024-10-14T09:27:35.365Z
last time: 2024-10-14T09:44:27.506Z
first time: 2024-10-16T19:10:27.265Z
last time: 2024-10-16T19:28:08.800Z
first time: 2024-10-16T12:32:47.996Z
last time: 2024-10-16T12:49:39.261Z
first time: 2024-10-16T13:30:30.045Z
last time: 2024-10-16T13:32:54.125Z
first time: 2024-10-15T09:28:18.164Z
last time: 2024-10-15T09:44:15.687Z
first time: 2024-10-16T20:28:41.523Z
last time: 2024-10-16T20:31:22.674Z
first time: 2024-10-16T13:28:10.798Z
last time: 2024-10-16T13:37:37.024Z
first time: 2024-10-16T17:46:23.832Z
last time: 2024-10-16T17:48:30.613Z
first time: 2024-10-16T13:24:38.295Z
last time: 2024-10-16T14:01:16.236Z
first time: 2024-10-16T14:58:12.264Z
last time: 2024-10-16T15:01:10.422Z
first time: 2024-10-16T18:27:57.192Z
last time: 2024-10-16T18:28:02.147Z
first time: 2024-10-16T12:21:35.165Z
last time: 2024-10-16T12:39:15.830Z
first time: 2024-10-17T07:44:28.828Z
last time: 2024-10-17T07:50:31.964Z
first time: 2024-10-17T13:47:08.145Z
last time: 2024-10-17T14:05:12.136Z
first time: 2024-10-16T13:44:17.325Z
last time: 2024-10-16T13:47:25.976Z
first time: 2024-10-16T15:25:54.178Z
last time: 2024-10-16T15:33:01.468Z
first time: 2024-10-16T12:21:17.707Z
last time: 2024-10-16T12:25:14.936Z
first time: 2024-10-16T20:15:32.822Z
last time: 2024-10-16T20:24:07.155Z
first time: 2024-10-16T12:31:07.743Z
last time: 2024-10-16T12:45:33.255Z
first time: 2024-10-16T18:09:04.081Z
last time: 2024-10-16T18:18:08.585Z
first time: 2024-10-17T17:24:52.163Z
last time: 2024-10-17T17:37:43.666Z
first time: 2024-10-16T12:26:47.917Z
last time: 2024-10-16T12:37:27.234Z
first time: 2024-10-17T12:30:38.286Z
last time: 2024-10-17T12:37:49.255Z
first time: 2024-10-16T14:54:39.537Z
last time: 2024-10-16T15:09:41.462Z
first time: 2024-10-16T21:04:30.548Z
last time: 2024-10-16T21:11:53.199Z
first time: 2024-10-16T12:24:01.668Z
last time: 2024-10-16T12:32:23.153Z
first time: 2024-10-16T16:03:52.336Z
last time: 2024-10-16T16:11:38.477Z
first time: 2024-10-17T12:46:36.807Z
last time: 2024-10-17T12:51:40.907Z
first time: 2024-10-17T04:35:43.629Z
last time: 2024-10-17T04:39:10.603Z
first time: 2024-10-16T18:25:07.547Z
last time: 2024-10-16T18:44:47.995Z
first time: 2024-10-16T22:15:18.938Z
last time: 2024-10-16T22:26:38.547Z
first time: 2024-10-17T08:09:42.266Z
last time: 2024-10-17T08:23:20.189Z
first time: 2024-10-16T16:32:08.863Z
last time: 2024-10-16T16:59:54.786Z
first time: 2024-10-16T20:03:56.333Z
last time: 2024-10-16T20:08:10.670Z
first time: 2024-10-14T09:27:33.720Z
last time: 2024-10-14T09:41:44.003Z
first time: 2024-10-15T09:31:45.672Z
last time: 2024-10-15T09:32:16.559Z
first time: 2024-10-16T19:07:26.021Z
last time: 2024-10-16T19:16:23.740Z
first time: 2024-10-14T10:14:09.972Z
last time: 2024-10-14T10:25:58.113Z
first time: 2024-10-15T09:37:46.739Z
last time: 2024-10-15T09:50:27.085Z
first time: 2024-10-16T17:46:04.451Z
last time: 2024-10-16T18:02:36.944Z
first time: 2024-10-14T09:29:56.544Z
last time: 2024-10-14T09:41:49.103Z
first time: 2024-10-16T21:21:24.612Z
last time: 2024-10-16T21:28:01.948Z
first time: 2024-10-16T17:56:12.098Z
last time: 2024-10-16T17:57:49.750Z
first time: 2024-10-16T12:22:38.319Z
last time: 2024-10-16T12:28:57.659Z
first time: 2024-10-16T19:39:48.771Z
last time: 2024-10-16T19:44:30.654Z
first time: 2024-10-17T08:27:58.652Z
last time: 2024-10-17T08:42:59.737Z
first time: 2024-10-16T16:04:16.252Z
last time: 2024-10-16T16:04:19.515Z
first time: 2024-10-17T14:42:05.536Z
last time: 2024-10-17T14:55:11.191Z
first time: 2024-10-16T15:21:27.275Z
last time: 2024-10-16T15:33:26.146Z
first time: 2024-10-14T10:47:45.180Z
last time: 2024-10-14T11:03:26.427Z
first time: 2024-10-16T13:23:49.812Z
last time: 2024-10-16T14:02:11.667Z
first time: 2024-10-16T12:35:06.590Z
last time: 2024-10-16T12:46:17.924Z
first time: 2024-10-14T09:30:02.789Z
last time: 2024-10-14T09:48:25.647Z
first time: 2024-10-16T14:19:35.912Z
last time: 2024-10-16T14:20:41.031Z
first time: 2024-10-16T14:49:34.268Z
last time: 2024-10-16T16:14:06.080Z
first time: 2024-10-16T17:14:49.022Z
last time: 2024-10-16T17:48:46.810Z
first time: 2024-10-17T12:34:43.621Z
last time: 2024-10-17T12:58:32.766Z
first time: 2024-10-16T16:36:04.136Z
last time: 2024-10-16T16:45:44.477Z
first time: 2024-10-16T17:55:46.524Z
last time: 2024-10-16T18:03:17.709Z
first time: 2024-10-16T17:47:03.190Z
last time: 2024-10-16T18:01:22.264Z
first time: 2024-10-16T18:04:38.238Z
last time: 2024-10-16T18:28:10.380Z
first time: 2024-10-17T09:07:45.939Z
last time: 2024-10-17T09:10:28.912Z
first time: 2024-10-17T12:16:16.322Z
last time: 2024-10-17T12:24:31.865Z
first time: 2024-10-17T08:59:43.383Z
last time: 2024-10-17T09:22:30.149Z
first time: 2024-10-16T14:19:26.504Z
last time: 2024-10-16T14:23:23.489Z
first time: 2024-10-16T17:35:47.537Z
last time: 2024-10-16T17:59:33.552Z
first time: 2024-10-16T16:50:22.896Z
last time: 2024-10-16T17:10:09.537Z
first time: 2024-10-17T07:55:06.639Z
last time: 2024-10-17T08:01:13.442Z
first time: 2024-10-16T21:40:37.169Z
last time: 2024-10-16T22:03:38.910Z
first time: 2024-10-14T10:24:17.397Z
last time: 2024-10-14T10:31:06.087Z
first time: 2024-10-17T15:59:26.566Z
last time: 2024-10-17T16:09:55.185Z
first time: 2024-10-16T19:04:23.163Z
last time: 2024-10-16T19:32:43.333Z
first time: 2024-10-16T18:41:32.534Z
last time: 2024-10-16T18:43:35.498Z
first time: 2024-10-16T13:18:21.335Z
last time: 2024-10-16T13:40:13.678Z
first time: 2024-10-16T15:01:19.019Z
last time: 2024-10-16T15:18:08.826Z
first time: 2024-10-17T12:16:55.578Z
last time: 2024-10-17T12:36:51.522Z
first time: 2024-10-16T16:36:01.448Z
last time: 2024-10-16T16:48:40.186Z
first time: 2024-10-14T09:31:20.620Z
last time: 2024-10-14T09:41:31.397Z
first time: 2024-10-16T14:21:06.606Z
last time: 2024-10-16T14:36:42.634Z
first time: 2024-10-17T14:06:24.550Z
last time: 2024-10-17T14:11:15.433Z
first time: 2024-10-16T17:47:52.785Z
last time: 2024-10-16T18:12:09.285Z
first time: 2024-10-16T18:22:54.538Z
last time: 2024-10-16T18:48:53.426Z
first time: 2024-10-16T21:00:32.316Z
last time: 2024-10-16T21:08:58.999Z
first time: 2024-10-17T13:12:03.976Z
last time: 2024-10-17T13:16:49.100Z
first time: 2024-10-16T17:17:04.314Z
last time: 2024-10-16T17:34:14.444Z
first time: 2024-10-16T16:57:54.301Z
last time: 2024-10-16T17:11:50.277Z
first time: 2024-10-16T12:34:44.049Z
last time: 2024-10-16T12:57:51.534Z
first time: 2024-10-16T19:20:23.316Z
last time: 2024-10-16T19:24:58.446Z
first time: 2024-10-16T14:44:48.687Z
last time: 2024-10-16T15:05:16.048Z
first time: 2024-10-15T10:35:20.248Z
last time: 2024-10-15T10:53:57.443Z
first time: 2024-10-16T20:02:45.340Z
last time: 2024-10-16T20:13:45.545Z
first time: 2024-10-16T16:51:27.311Z
last time: 2024-10-16T17:11:33.423Z
first time: 2024-10-16T15:36:45.170Z
last time: 2024-10-16T15:44:45.181Z
first time: 2024-10-16T13:56:00.606Z
last time: 2024-10-16T13:58:48.679Z
first time: 2024-10-16T19:08:06.107Z
last time: 2024-10-16T19:12:49.927Z
first time: 2024-10-15T09:44:39.279Z
last time: 2024-10-15T09:54:33.509Z
first time: 2024-10-16T19:12:30.572Z
last time: 2024-10-16T20:32:11.353Z
first time: 2024-10-16T19:44:13.913Z
last time: 2024-10-16T19:55:46.880Z
first time: 2024-10-16T14:18:16.118Z
last time: 2024-10-16T14:20:26.150Z
first time: 2024-10-15T09:52:27.062Z
last time: 2024-10-15T10:00:38.701Z
first time: 2024-10-16T17:39:03.913Z
last time: 2024-10-16T17:39:57.680Z
first time: 2024-10-16T16:46:13.714Z
last time: 2024-10-16T17:04:22.500Z
first time: 2024-10-16T19:17:08.801Z
last time: 2024-10-16T19:33:07.851Z
first time: 2024-10-16T12:17:12.809Z
last time: 2024-10-16T12:20:19.403Z
first time: 2024-10-16T16:05:22.494Z
last time: 2024-10-16T16:09:19.219Z
first time: 2024-10-16T12:23:10.341Z
last time: 2024-10-16T12:28:44.626Z
first time: 2024-10-16T14:24:51.649Z
last time: 2024-10-16T15:25:19.041Z
first time: 2024-10-16T14:25:25.126Z
last time: 2024-10-16T14:43:33.182Z
first time: 2024-10-17T17:13:42.294Z
last time: 2024-10-17T17:22:09.842Z
first time: 2024-10-16T16:35:21.548Z
last time: 2024-10-16T16:49:02.383Z
first time: 2024-10-16T16:55:15.667Z
last time: 2024-10-16T17:00:55.053Z
first time: 2024-10-16T12:37:15.090Z
last time: 2024-10-16T12:50:05.002Z
first time: 2024-10-16T13:02:30.107Z
last time: 2024-10-16T13:11:08.210Z
first time: 2024-10-16T18:44:43.455Z
last time: 2024-10-16T18:47:42.579Z
first time: 2024-10-17T15:00:17.027Z
last time: 2024-10-17T15:09:45.464Z
first time: 2024-10-17T09:00:31.749Z
last time: 2024-10-17T09:03:11.657Z
first time: 2024-10-16T15:33:12.733Z
last time: 2024-10-16T15:44:32.869Z
first time: 2024-10-17T16:05:06.678Z
last time: 2024-10-17T16:26:52.867Z
first time: 2024-10-16T21:13:48.691Z
last time: 2024-10-19T05:22:27.479Z
first time: 2024-10-16T15:26:16.977Z
last time: 2024-10-16T15:40:40.994Z
first time: 2024-10-16T14:30:26.352Z
last time: 2024-10-16T17:45:41.080Z
first time: 2024-10-17T11:36:07.416Z
last time: 2024-10-17T11:53:51.874Z
first time: 2024-10-16T21:03:51.267Z
last time: 2024-10-16T22:39:22.891Z
first time: 2024-10-16T12:17:25.401Z
last time: 2024-10-16T12:25:21.741Z
first time: 2024-10-16T22:55:44.000Z
last time: 2024-10-16T23:18:57.866Z
first time: 2024-10-16T17:45:38.938Z
last time: 2024-10-16T17:51:39.084Z
first time: 2024-10-16T20:14:29.948Z
last time: 2024-10-16T20:22:18.595Z
first time: 2024-10-16T20:16:31.651Z
last time: 2024-10-16T20:16:34.106Z
first time: 2024-10-17T08:57:17.555Z
last time: 2024-10-17T10:26:46.753Z
first time: 2024-10-14T10:35:04.514Z
last time: 2024-10-14T10:49:40.776Z
first time: 2024-10-16T19:42:44.739Z
last time: 2024-10-16T19:57:30.980Z
first time: 2024-10-16T18:39:54.394Z
last time: 2024-10-16T18:49:22.139Z
first time: 2024-10-16T18:12:58.074Z
last time: 2024-10-16T18:17:12.117Z
first time: 2024-10-14T09:34:55.947Z
last time: 2024-10-14T09:39:45.707Z
first time: 2024-10-16T16:53:12.290Z
last time: 2024-10-16T16:55:58.378Z
first time: 2024-10-16T15:06:17.783Z
last time: 2024-10-16T15:08:48.902Z
first time: 2024-10-17T07:12:40.987Z
last time: 2024-10-17T07:19:41.217Z
first time: 2024-10-16T17:16:59.806Z
last time: 2024-10-16T17:32:38.846Z
first time: 2024-10-16T16:35:37.899Z
last time: 2024-10-16T16:47:18.778Z
first time: 2024-10-16T14:58:19.946Z
last time: 2024-10-16T15:12:41.412Z
first time: 2024-10-16T12:23:40.915Z
last time: 2024-10-16T12:26:51.104Z
first time: 2024-10-15T09:31:49.967Z
last time: 2024-10-15T09:58:36.715Z
first time: 2024-10-16T21:14:56.425Z
last time: 2024-10-16T21:25:00.616Z
first time: 2024-10-16T14:54:37.635Z
last time: 2024-10-16T15:06:56.188Z
first time: 2024-10-16T13:22:15.933Z
last time: 2024-10-16T13:41:17.029Z
first time: 2024-10-16T13:35:17.624Z
last time: 2024-10-16T13:58:41.490Z
first time: 2024-10-16T12:33:37.329Z
last time: 2024-10-16T12:37:39.569Z
first time: 2024-10-17T02:46:07.980Z
last time: 2024-10-17T02:53:28.128Z
first time: 2024-10-16T18:08:18.770Z
last time: 2024-10-16T18:34:02.564Z
first time: 2024-10-16T18:56:53.545Z
last time: 2024-10-16T19:07:31.793Z
first time: 2024-10-14T11:05:06.300Z
last time: 2024-10-14T11:15:51.996Z
first time: 2024-10-17T09:35:02.534Z
last time: 2024-10-17T09:51:39.689Z
first time: 2024-10-16T15:35:14.879Z
last time: 2024-10-16T15:52:03.483Z
first time: 2024-10-16T16:41:14.820Z
last time: 2024-10-16T17:27:00.412Z
first time: 2024-10-15T09:29:28.772Z
last time: 2024-10-15T09:32:34.012Z
first time: 2024-10-16T19:04:07.160Z
last time: 2024-10-16T19:16:13.253Z
first time: 2024-10-16T17:59:52.968Z
last time: 2024-10-16T18:22:55.421Z
first time: 2024-10-16T13:42:10.702Z
last time: 2024-10-16T14:00:48.368Z
first time: 2024-10-16T18:47:21.060Z
last time: 2024-10-16T18:58:26.048Z
first time: 2024-10-16T20:52:55.784Z
last time: 2024-10-16T21:01:14.998Z
first time: 2024-10-16T14:48:47.508Z
last time: 2024-10-16T15:46:35.535Z
first time: 2024-10-16T18:39:06.293Z
last time: 2024-10-16T18:44:59.068Z
first time: 2024-10-17T01:04:57.842Z
last time: 2024-10-17T03:49:23.887Z
first time: 2024-10-16T18:57:05.302Z
last time: 2024-10-16T19:02:17.266Z
first time: 2024-10-16T18:22:19.939Z
last time: 2024-10-16T18:46:35.169Z
first time: 2024-10-17T08:35:51.546Z
last time: 2024-10-17T08:47:46.676Z
first time: 2024-10-16T20:57:10.435Z
last time: 2024-10-16T21:15:42.118Z
first time: 2024-10-16T17:27:00.204Z
last time: 2024-10-16T17:35:02.533Z
first time: 2024-10-16T15:50:43.261Z
last time: 2024-10-16T16:09:47.942Z
first time: 2024-10-16T12:33:01.901Z
last time: 2024-10-16T12:37:44.577Z
first time: 2024-10-16T19:31:06.973Z
last time: 2024-10-16T19:36:25.385Z
first time: 2024-10-16T12:48:58.714Z
last time: 2024-10-16T12:56:40.239Z
first time: 2024-10-16T18:07:07.823Z
last time: 2024-10-16T18:16:53.243Z
first time: 2024-10-17T08:09:11.782Z
last time: 2024-10-17T08:23:03.850Z
first time: 2024-10-16T19:13:19.644Z
last time: 2024-10-16T19:27:51.383Z
first time: 2024-10-15T09:31:56.895Z
last time: 2024-10-15T09:38:57.076Z
first time: 2024-10-16T18:06:53.054Z

first time: 2024-10-16T15:11:35.014Z
last time: 2024-10-16T15:24:18.422Z
first time: 2024-10-16T16:27:32.139Z
last time: 2024-10-16T16:36:56.398Z
first time: 2024-10-16T13:42:15.090Z
last time: 2024-10-16T14:05:16.408Z
first time: 2024-10-16T13:38:05.340Z
last time: 2024-10-16T13:45:57.459Z
first time: 2024-10-16T15:36:37.733Z
last time: 2024-10-16T16:00:25.263Z
first time: 2024-10-16T13:22:43.866Z
last time: 2024-10-16T13:42:59.857Z
first time: 2024-10-15T09:36:29.959Z
last time: 2024-10-15T09:59:11.041Z
first time: 2024-10-17T13:23:24.539Z
last time: 2024-10-17T13:28:15.941Z
first time: 2024-10-16T20:46:03.394Z
last time: 2024-10-16T20:46:58.368Z
first time: 2024-10-16T20:13:06.618Z
last time: 2024-10-16T20:13:45.350Z
first time: 2024-10-16T20:10:23.065Z
last time: 2024-10-16T20:13:54.549Z
first time: 2024-10-16T18:39:10.049Z
last time: 2024-10-16T19:01:26.018Z
first time: 2024-10-16T15:53:46.634Z
last time: 2024-10-16T22:00:38.773Z
first time: 2024-10-16T19:33:56.010Z
last time: 2024-10-16T19:53:39.717Z
first time: 2024-10-15T09:30:33.852Z
last time: 2024-10-15T09:44:15.448Z
first time: 2024-10-17T15:13:50.977Z
last time: 2024-10-17T15:17:13.585Z
first time: 2024-10-14T10:16:14.659Z
last time: 2024-10-14T10:19:53.269Z
first time: 2024-10-16T13:23:48.823Z
last time: 2024-10-16T13:41:23.309Z
first time: 2024-10-16T12:18:20.919Z
last time: 2024-10-16T12:28:53.334Z
first time: 2024-10-16T19:51:46.972Z
last time: 2024-10-16T19:53:52.208Z
first time: 2024-10-16T15:16:15.883Z
last time: 2024-10-16T15:16:23.505Z
first time: 2024-10-14T10:22:13.812Z
last time: 2024-10-14T10:34:08.574Z
first time: 2024-10-17T15:31:35.499Z
last time: 2024-10-17T15:33:47.803Z
first time: 2024-10-16T14:50:22.724Z
last time: 2024-10-16T15:17:35.403Z
first time: 2024-10-16T18:09:09.694Z
last time: 2024-10-16T18:16:26.675Z
first time: 2024-10-16T18:33:29.350Z
last time: 2024-10-16T18:34:56.923Z
first time: 2024-10-16T18:11:50.881Z
last time: 2024-10-16T18:33:17.848Z
first time: 2024-10-14T10:28:02.443Z
last time: 2024-10-14T10:53:03.246Z
first time: 2024-10-16T13:44:49.807Z
last time: 2024-10-16T14:10:15.750Z
first time: 2024-10-16T19:55:20.113Z
last time: 2024-10-16T19:57:47.282Z
first time: 2024-10-14T09:50:33.019Z
last time: 2024-10-14T10:02:57.298Z
first time: 2024-10-16T14:21:04.366Z
last time: 2024-10-16T14:34:27.223Z
first time: 2024-10-16T16:45:10.503Z
last time: 2024-10-16T16:47:09.516Z
first time: 2024-10-14T11:06:54.277Z
last time: 2024-10-14T11:34:32.131Z
first time: 2024-10-16T16:16:31.276Z
last time: 2024-10-16T16:37:15.644Z
first time: 2024-10-16T15:47:26.728Z
last time: 2024-10-16T15:54:19.668Z
first time: 2024-10-14T09:29:11.703Z
last time: 2024-10-14T10:06:12.940Z
first time: 2024-10-15T09:32:58.611Z
last time: 2024-10-15T09:44:53.768Z
first time: 2024-10-17T12:37:32.062Z
last time: 2024-10-17T12:50:16.145Z
first time: 2024-10-16T13:19:17.252Z
last time: 2024-10-16T13:21:23.016Z
first time: 2024-10-16T12:24:11.416Z
last time: 2024-10-16T12:24:24.673Z
first time: 2024-10-17T03:14:55.256Z
last time: 2024-10-17T03:23:37.445Z
first time: 2024-10-16T19:06:37.877Z
last time: 2024-10-17T20:26:20.068Z
first time: 2024-10-16T18:16:05.635Z
last time: 2024-10-16T18:21:19.257Z
first time: 2024-10-16T16:39:39.809Z
last time: 2024-10-16T16:59:28.440Z
first time: 2024-10-16T12:19:16.136Z
last time: 2024-10-16T12:24:41.541Z
first time: 2024-10-16T15:37:55.800Z
last time: 2024-10-16T16:01:45.387Z
first time: 2024-10-16T17:48:03.197Z
last time: 2024-10-16T18:17:59.823Z
first time: 2024-10-16T16:48:26.816Z
last time: 2024-10-16T17:12:18.777Z
first time: 2024-10-17T13:12:49.398Z
last time: 2024-10-17T13:16:11.727Z
first time: 2024-10-16T13:41:32.936Z
last time: 2024-10-16T13:54:36.273Z
first time: 2024-10-16T19:21:48.269Z
last time: 2024-10-16T19:46:13.021Z
first time: 2024-10-15T09:38:17.854Z
last time: 2024-10-15T09:56:05.153Z
first time: 2024-10-16T20:09:30.994Z
last time: 2024-10-16T20:15:03.413Z
first time: 2024-10-17T13:47:28.580Z
last time: 2024-10-17T14:11:36.658Z
first time: 2024-10-16T13:20:13.974Z
last time: 2024-10-16T13:33:56.658Z
first time: 2024-10-17T05:04:08.453Z
last time: 2024-10-17T05:26:17.830Z
first time: 2024-10-17T18:57:25.034Z
last time: 2024-10-17T19:04:34.776Z
first time: 2024-10-16T13:35:51.037Z
last time: 2024-10-16T13:38:22.624Z
first time: 2024-10-17T13:29:11.859Z
last time: 2024-10-17T13:51:43.753Z
first time: 2024-10-16T18:09:18.613Z
last time: 2024-10-16T18:20:21.898Z
first time: 2024-10-16T12:19:46.820Z
last time: 2024-10-16T12:23:26.661Z
first time: 2024-10-16T17:25:59.628Z
last time: 2024-10-16T17:26:01.939Z
first time: 2024-10-16T18:32:02.606Z
last time: 2024-10-16T18:46:00.440Z
first time: 2024-10-16T13:30:33.940Z
last time: 2024-10-16T13:39:17.437Z
first time: 2024-10-16T19:15:32.329Z
last time: 2024-10-16T19:27:31.107Z
first time: 2024-10-15T09:50:57.298Z
last time: 2024-10-15T10:02:25.267Z
first time: 2024-10-16T20:37:58.635Z
last time: 2024-10-16T21:02:26.840Z
first time: 2024-10-16T17:54:15.347Z
last time: 2024-10-16T18:11:41.898Z
first time: 2024-10-17T03:24:50.051Z
last time: 2024-10-17T03:32:57.244Z
first time: 2024-10-16T16:11:59.461Z
last time: 2024-10-16T16:23:50.158Z
first time: 2024-10-16T17:33:54.120Z
last time: 2024-10-16T17:47:31.242Z
first time: 2024-10-15T09:32:43.799Z
last time: 2024-10-15T09:40:08.599Z
first time: 2024-10-16T12:27:38.533Z
last time: 2024-10-16T12:53:59.495Z
first time: 2024-10-16T20:41:37.318Z
last time: 2024-10-16T20:51:04.709Z
first time: 2024-10-16T19:28:52.126Z
last time: 2024-10-16T19:39:38.386Z
first time: 2024-10-16T13:30:35.149Z
last time: 2024-10-16T13:58:33.574Z
first time: 2024-10-16T13:26:27.505Z
last time: 2024-10-16T13:31:22.215Z
first time: 2024-10-16T14:34:41.842Z
last time: 2024-10-16T17:54:10.370Z
first time: 2024-10-17T08:21:15.796Z
last time: 2024-10-17T08:26:51.281Z
first time: 2024-10-16T21:18:31.845Z
last time: 2024-10-16T21:25:37.781Z
first time: 2024-10-16T17:23:25.228Z
last time: 2024-10-16T17:41:44.326Z
first time: 2024-10-16T14:50:38.003Z
last time: 2024-10-16T15:03:22.156Z
first time: 2024-10-17T16:40:59.597Z
last time: 2024-10-17T17:14:52.779Z
first time: 2024-10-14T10:16:30.911Z
last time: 2024-10-14T10:33:55.743Z
first time: 2024-10-14T09:26:27.237Z
last time: 2024-10-14T09:32:01.862Z
first time: 2024-10-14T09:36:16.483Z
last time: 2024-10-14T10:00:05.733Z
first time: 2024-10-16T13:32:49.490Z
last time: 2024-10-16T13:37:08.006Z
first time: 2024-10-16T17:44:34.494Z
last time: 2024-10-16T17:58:21.461Z
first time: 2024-10-16T16:18:38.549Z
last time: 2024-10-16T16:47:34.885Z
first time: 2024-10-16T17:40:54.050Z
last time: 2024-10-16T18:00:34.409Z
first time: 2024-10-16T14:15:05.752Z
last time: 2024-10-16T14:24:48.602Z
first time: 2024-10-17T02:39:02.201Z
last time: 2024-10-17T02:59:57.609Z
first time: 2024-10-16T12:36:58.526Z
last time: 2024-10-16T12:40:16.244Z
first time: 2024-10-16T12:36:23.052Z
last time: 2024-10-16T12:51:58.177Z
first time: 2024-10-14T09:25:06.958Z
last time: 2024-10-14T09:27:43.789Z
first time: 2024-10-17T17:00:02.881Z
last time: 2024-10-17T17:18:35.789Z
first time: 2024-10-16T19:24:34.815Z
last time: 2024-10-16T19:27:41.872Z
first time: 2024-10-16T14:34:12.180Z
last time: 2024-10-16T14:36:29.643Z
first time: 2024-10-16T19:26:01.297Z
last time: 2024-10-16T19:35:33.470Z
first time: 2024-10-14T10:20:50.345Z
last time: 2024-10-14T11:27:21.394Z
first time: 2024-10-16T14:26:17.918Z
last time: 2024-10-16T14:33:55.789Z
first time: 2024-10-16T18:50:39.289Z
last time: 2024-10-16T18:54:47.129Z
first time: 2024-10-16T15:31:06.061Z
last time: 2024-10-16T15:34:57.828Z
first time: 2024-10-15T09:29:26.951Z
last time: 2024-10-15T09:50:50.325Z
first time: 2024-10-16T20:45:31.410Z
last time: 2024-10-16T21:21:02.852Z
first time: 2024-10-16T12:32:52.528Z
last time: 2024-10-16T12:46:05.528Z
first time: 2024-10-16T20:03:33.586Z
last time: 2024-10-16T20:06:29.696Z
first time: 2024-10-14T10:17:11.379Z
last time: 2024-10-14T10:29:19.368Z
first time: 2024-10-16T18:47:04.388Z
last time: 2024-10-16T19:06:44.158Z
first time: 2024-10-15T09:28:31.864Z
last time: 2024-10-15T09:35:29.960Z
first time: 2024-10-16T15:24:22.876Z
last time: 2024-10-16T16:10:03.428Z
first time: 2024-10-17T16:01:02.259Z
last time: 2024-10-17T16:20:03.523Z
first time: 2024-10-16T18:45:00.540Z
last time: 2024-10-16T18:56:34.453Z
first time: 2024-10-16T12:44:28.190Z
last time: 2024-10-16T13:09:07.752Z
first time: 2024-10-16T15:41:28.287Z
last time: 2024-10-16T16:21:06.740Z
first time: 2024-10-16T16:51:26.773Z
last time: 2024-10-16T16:52:09.178Z
first time: 2024-10-15T09:35:16.996Z
last time: 2024-10-15T09:52:25.101Z
first time: 2024-10-16T12:24:53.442Z
last time: 2024-10-16T12:34:49.938Z
first time: 2024-10-16T19:03:16.801Z
last time: 2024-10-16T19:08:15.747Z
first time: 2024-10-16T18:40:27.693Z
last time: 2024-10-16T18:57:31.205Z

first time: 2024-10-16T17:02:32.793Z
last time: 2024-10-16T17:26:46.325Z
first time: 2024-10-17T19:59:24.087Z
last time: 2024-10-17T20:15:02.809Z
first time: 2024-10-16T14:45:19.240Z
last time: 2024-10-16T15:12:31.770Z
first time: 2024-10-16T13:52:18.336Z
last time: 2024-10-16T13:54:45.280Z
first time: 2024-10-17T15:54:41.805Z
last time: 2024-10-17T16:10:43.427Z
first time: 2024-10-16T20:10:54.409Z
last time: 2024-10-16T20:22:22.155Z
first time: 2024-10-15T09:28:36.450Z
last time: 2024-10-15T09:29:01.082Z
first time: 2024-10-16T16:33:45.589Z
last time: 2024-10-16T16:40:05.658Z
first time: 2024-10-16T14:41:25.993Z
last time: 2024-10-16T14:52:56.479Z
first time: 2024-10-14T10:29:45.918Z
last time: 2024-10-14T10:44:58.977Z
first time: 2024-10-16T17:17:52.041Z
last time: 2024-10-16T20:36:02.924Z
first time: 2024-10-17T15:26:00.119Z
last time: 2024-10-17T18:02:12.300Z
first time: 2024-10-16T16:30:44.426Z
last time: 2024-10-16T16:52:25.252Z
first time: 2024-10-16T19:43:24.355Z
last time: 2024-10-16T19:49:14.013Z
first time: 2024-10-16T16:26:26.828Z
last time: 2024-10-16T16:48:12.358Z
first time: 2024-10-16T15:52:35.239Z
last time: 2024-10-16T15:59:59.244Z
first time: 2024-10-17T13:49:20.549Z
last time: 2024-10-17T13:49:25.880Z
first time: 2024-10-16T13:23:44.187Z
last time: 2024-10-16T13:38:49.447Z
first time: 2024-10-17T14:08:54.209Z
last time: 2024-10-17T14:35:07.669Z
first time: 2024-10-17T05:05:47.298Z
last time: 2024-10-17T05:18:09.150Z
first time: 2024-10-16T21:47:10.886Z
last time: 2024-10-16T21:50:45.870Z
first time: 2024-10-14T10:17:34.258Z
last time: 2024-10-14T10:35:37.935Z
first time: 2024-10-14T09:32:31.505Z
last time: 2024-10-14T09:51:22.268Z
first time: 2024-10-16T16:46:49.894Z
last time: 2024-10-16T16:53:42.876Z
first time: 2024-10-14T10:22:36.690Z
last time: 2024-10-14T10:33:42.913Z
first time: 2024-10-14T09:46:54.353Z
last time: 2024-10-14T09:50:53.430Z
first time: 2024-10-16T12:31:53.976Z
last time: 2024-10-16T14:45:48.913Z
first time: 2024-10-16T15:52:16.211Z
last time: 2024-10-16T17:12:14.413Z
first time: 2024-10-17T10:02:40.532Z
last time: 2024-10-17T13:06:53.785Z
first time: 2024-10-14T10:17:32.878Z
last time: 2024-10-14T10:23:51.412Z
first time: 2024-10-16T13:43:32.250Z
last time: 2024-10-16T14:06:38.356Z
first time: 2024-10-16T13:39:54.169Z
last time: 2024-10-16T13:51:41.483Z
first time: 2024-10-16T18:47:05.859Z
last time: 2024-10-16T18:53:59.526Z
first time: 2024-10-17T08:43:49.402Z
last time: 2024-10-17T08:54:53.392Z
first time: 2024-10-16T12:27:22.251Z
last time: 2024-10-16T12:35:12.488Z
first time: 2024-10-16T12:20:09.242Z
last time: 2024-10-16T12:28:07.056Z
first time: 2024-10-15T09:27:38.519Z
last time: 2024-10-15T09:39:52.942Z
first time: 2024-10-14T11:51:23.728Z
last time: 2024-10-14T11:55:29.603Z
first time: 2024-10-14T09:28:10.626Z
last time: 2024-10-14T09:43:07.990Z
first time: 2024-10-16T12:33:05.032Z
last time: 2024-10-16T12:34:54.671Z
first time: 2024-10-16T15:01:34.876Z
last time: 2024-10-16T15:02:59.662Z
first time: 2024-10-17T06:39:38.453Z
last time: 2024-10-17T06:43:36.027Z
first time: 2024-10-16T20:25:44.894Z
last time: 2024-10-16T20:27:37.787Z
first time: 2024-10-15T09:29:52.392Z
last time: 2024-10-15T09:41:51.438Z
first time: 2024-10-17T12:23:55.152Z
last time: 2024-10-17T12:29:37.153Z
first time: 2024-10-16T17:21:52.618Z
last time: 2024-10-16T17:21:57.745Z
first time: 2024-10-16T20:32:21.138Z
last time: 2024-10-16T20:41:16.044Z
first time: 2024-10-16T16:00:58.152Z
last time: 2024-10-16T16:01:41.613Z
first time: 2024-10-16T19:49:00.451Z
last time: 2024-10-16T20:00:45.332Z
first time: 2024-10-17T13:34:06.980Z
last time: 2024-10-17T20:46:27.912Z
first time: 2024-10-17T03:27:27.673Z
last time: 2024-10-17T03:33:23.830Z
first time: 2024-10-17T17:12:49.677Z
last time: 2024-10-17T17:55:48.412Z
first time: 2024-10-16T15:29:33.139Z
last time: 2024-10-16T16:21:51.611Z
first time: 2024-10-16T14:19:58.837Z
last time: 2024-10-16T14:21:19.472Z
first time: 2024-10-16T18:26:19.520Z
last time: 2024-10-16T18:41:38.200Z
first time: 2024-10-16T16:28:14.757Z
last time: 2024-10-16T16:47:57.641Z
first time: 2024-10-14T09:32:34.247Z
last time: 2024-10-14T09:57:54.536Z
first time: 2024-10-14T09:47:02.552Z
last time: 2024-10-14T10:59:40.692Z
first time: 2024-10-17T13:21:43.476Z
last time: 2024-10-17T13:35:56.901Z
first time: 2024-10-16T19:20:17.523Z
last time: 2024-10-16T19:45:50.999Z
first time: 2024-10-16T17:04:03.450Z
last time: 2024-10-16T17:07:30.208Z
first time: 2024-10-16T19:47:03.569Z
last time: 2024-10-16T20:01:24.074Z
first time: 2024-10-17T05:03:46.568Z
last time: 2024-10-17T05:15:55.943Z
first time: 2024-10-16T19:31:43.538Z
last time: 2024-10-16T19:36:13.031Z
first time: 2024-10-16T12:22:52.954Z
last time: 2024-10-16T12:28:54.980Z
first time: 2024-10-16T12:37:35.847Z
last time: 2024-10-16T12:53:13.498Z
first time: 2024-10-16T17:41:30.297Z
last time: 2024-10-16T17:48:32.319Z
first time: 2024-10-16T20:12:57.138Z
last time: 2024-10-16T20:19:00.670Z
first time: 2024-10-16T13:59:13.895Z
last time: 2024-10-16T14:28:58.746Z
first time: 2024-10-16T21:56:54.818Z
last time: 2024-10-18T22:23:24.720Z
first time: 2024-10-14T10:28:49.292Z
last time: 2024-10-14T11:14:07.287Z
first time: 2024-10-17T07:29:52.944Z
last time: 2024-10-17T07:32:43.117Z
first time: 2024-10-16T15:33:42.426Z
last time: 2024-10-16T15:42:58.458Z
first time: 2024-10-17T04:41:13.687Z
last time: 2024-10-17T04:58:13.174Z
first time: 2024-10-17T18:05:53.718Z
last time: 2024-10-17T18:24:48.373Z
first time: 2024-10-16T20:11:56.318Z
last time: 2024-10-16T20:30:36.461Z
first time: 2024-10-16T14:28:20.637Z
last time: 2024-10-16T14:52:15.833Z
first time: 2024-10-16T17:25:29.088Z
last time: 2024-10-16T21:30:57.863Z
first time: 2024-10-16T14:47:23.702Z
last time: 2024-10-16T15:00:54.207Z
first time: 2024-10-17T13:37:23.591Z
last time: 2024-10-17T13:39:58.060Z
first time: 2024-10-16T13:23:24.746Z
last time: 2024-10-16T13:46:18.576Z
first time: 2024-10-14T09:29:14.226Z
last time: 2024-10-14T10:57:03.355Z
first time: 2024-10-16T19:45:30.020Z
last time: 2024-10-16T19:52:50.234Z
first time: 2024-10-14T09:33:06.908Z
last time: 2024-10-14T09:37:56.196Z
first time: 2024-10-14T10:23:34.574Z
last time: 2024-10-14T10:36:30.111Z
first time: 2024-10-16T14:47:55.553Z
last time: 2024-10-16T14:49:07.189Z
first time: 2024-10-16T12:51:00.426Z
last time: 2024-10-16T12:53:08.505Z
first time: 2024-10-14T09:37:08.632Z
last time: 2024-10-14T09:52:02.553Z
first time: 2024-10-16T15:38:28.468Z
last time: 2024-10-16T16:55:17.326Z
first time: 2024-10-16T18:34:05.213Z
last time: 2024-10-16T18:40:04.154Z
first time: 2024-10-17T18:09:52.475Z
last time: 2024-10-17T18:39:13.135Z
first time: 2024-10-16T15:18:23.321Z
last time: 2024-10-16T15:20:52.248Z
first time: 2024-10-16T14:44:25.332Z
last time: 2024-10-16T14:53:33.488Z
first time: 2024-10-14T10:13:15.948Z
last time: 2024-10-14T10:18:22.287Z
first time: 2024-10-17T05:24:02.507Z
last time: 2024-10-17T05:37:16.130Z
first time: 2024-10-14T09:59:11.628Z
last time: 2024-10-14T10:08:22.476Z
first time: 2024-10-16T12:43:56.009Z
last time: 2024-10-16T12:58:52.918Z
first time: 2024-10-16T13:28:56.238Z
last time: 2024-10-16T13:33:02.200Z
first time: 2024-10-16T13:22:22.763Z
last time: 2024-10-16T13:26:11.029Z
first time: 2024-10-17T12:49:53.401Z
last time: 2024-10-17T13:06:44.507Z
first time: 2024-10-16T14:54:09.364Z
last time: 2024-10-16T14:54:39.723Z
first time: 2024-10-16T12:37:17.110Z
last time: 2024-10-16T12:56:16.872Z
first time: 2024-10-16T17:49:50.347Z
last time: 2024-10-16T17:58:30.957Z
first time: 2024-10-16T20:31:09.891Z
last time: 2024-10-16T20:47:23.057Z
first time: 2024-10-16T23:16:01.809Z
last time: 2024-10-16T23:26:35.456Z
first time: 2024-10-17T07:41:21.936Z
last time: 2024-10-17T07:44:40.328Z
first time: 2024-10-14T09:29:09.250Z
last time: 2024-10-14T09:51:53.120Z
first time: 2024-10-17T13:40:27.160Z
last time: 2024-10-17T13:49:59.188Z
first time: 2024-10-17T03:24:56.514Z
last time: 2024-10-17T03:35:16.540Z
first time: 2024-10-16T15:09:52.367Z
last time: 2024-10-16T15:26:36.101Z
first time: 2024-10-17T17:32:59.627Z
last time: 2024-10-17T17:42:27.201Z
first time: 2024-10-17T07:18:50.842Z
last time: 2024-10-17T08:01:55.802Z
first time: 2024-10-16T14:26:42.871Z
last time: 2024-10-16T14:37:14.621Z
first time: 2024-10-17T09:33:51.772Z
last time: 2024-10-17T09:41:51.167Z
first time: 2024-10-16T14:26:15.176Z
last time: 2024-10-16T14:47:35.511Z
first time: 2024-10-16T21:30:11.647Z
last time: 2024-10-16T21:37:54.949Z
first time: 2024-10-14T09:38:41.617Z
last time: 2024-10-14T09:55:49.942Z
first time: 2024-10-16T14:38:27.088Z
last time: 2024-10-16T14:46:25.342Z
first time: 2024-10-14T09:35:04.760Z
last time: 2024-10-14T09:50:09.132Z
first time: 2024-10-16T14:43:00.005Z
last time: 2024-10-16T14:56:16.092Z
first time: 2024-10-16T20:09:46.054Z
last time: 2024-10-16T20:12:12.634Z
first time: 2024-10-15T09:28:47.998Z
last time: 2024-10-15T09:31:36.021Z
first time: 2024-10-16T17:48:47.867Z
last time: 2024-10-16T21:07:20.048Z
first time: 2024-10-17T17:11:13.642Z
last time: 2024-10-17T17:22:35.090Z
first time: 2024-10-16T15:04:09.915Z
last time: 2024-10-16T15:10:02.498Z
first time: 2024-10-16T12:21:00.035Z
last time: 2024-10-16T12:37:52.331Z
first time: 2024-10-16T13:26:00.222Z
last time: 2024-10-16T13:32:10.549Z
first time: 2024-10-14T09:47:26.580Z
last time: 2024-10-14T09:56:52.944Z
first time: 2024-10-16T15:13:21.370Z
last time: 2024-10-16T15:19:30.501Z
first time: 2024-10-16T20:35:14.444Z
last time: 2024-10-16T20:38:59.763Z
first time: 2024-10-16T12:21:38.020Z
last time: 2024-10-16T12:42:35.755Z
first time: 2024-10-16T19:59:48.954Z
last time: 2024-10-16T20:08:20.848Z
first time: 2024-10-16T14:41:03.700Z
last time: 2024-10-16T14:45:12.719Z
first time: 2024-10-15T09:32:54.551Z
last time: 2024-10-15T09:44:20.404Z
first time: 2024-10-17T05:08:30.106Z
last time: 2024-10-17T05:20:43.784Z
first time: 2024-10-17T06:40:05.527Z
last time: 2024-10-17T06:53:24.595Z
first time: 2024-10-16T13:22:05.754Z
last time: 2024-10-16T13:30:27.047Z
first time: 2024-10-15T09:28:57.756Z
last time: 2024-10-15T09:36:36.417Z
first time: 2024-10-16T14:23:07.606Z
last time: 2024-10-16T14:40:41.197Z
first time: 2024-10-16T13:30:54.201Z
last time: 2024-10-16T14:00:50.272Z
first time: 2024-10-16T12:24:04.560Z
last time: 2024-10-16T12:27:20.311Z
first time: 2024-10-16T20:13:24.808Z
last time: 2024-10-16T20:18:09.204Z
first time: 2024-10-16T12:20:24.541Z
last time: 2024-10-16T12:32:18.006Z
first time: 2024-10-17T00:22:13.905Z
last time: 2024-10-17T00:26:13.290Z
first time: 2024-10-16T12:33:30.108Z
last time: 2024-10-16T12:46:54.259Z
first time: 2024-10-17T13:12:06.214Z
last time: 2024-10-17T13:15:12.034Z
first time: 2024-10-16T22:53:20.249Z
last time: 2024-10-16T22:57:45.207Z
first time: 2024-10-17T09:23:49.950Z
last time: 2024-10-17T09:29:16.698Z
first time: 2024-10-16T12:42:59.865Z
last time: 2024-10-16T12:46:15.766Z
first time: 2024-10-16T12:48:30.084Z
last time: 2024-10-16T12:52:23.934Z
first time: 2024-10-17T13:33:42.495Z
last time: 2024-10-17T14:01:18.751Z
first time: 2024-10-14T09:33:04.844Z
last time: 2024-10-14T09:56:14.065Z
first time: 2024-10-16T15:29:25.594Z
last time: 2024-10-16T15:31:29.987Z
first time: 2024-10-16T21:39:58.670Z
last time: 2024-10-16T23:28:35.062Z
first time: 2024-10-16T16:51:09.956Z
last time: 2024-10-16T17:03:02.358Z
first time: 2024-10-16T19:41:52.250Z
last time: 2024-10-16T20:01:37.684Z
first time: 2024-10-16T15:35:57.393Z
last time: 2024-10-16T15:39:22.731Z
first time: 2024-10-17T19:42:30.634Z
last time: 2024-10-17T20:01:30.130Z
first time: 2024-10-16T18:02:15.211Z
last time: 2024-10-16T18:04:33.811Z
first time: 2024-10-17T06:54:43.609Z
last time: nan
first time: 2024-10-16T17:08:21.166Z
last time: 2024-10-16T17:23:15.964Z
first time: 2024-10-16T12:21:52.632Z
last time: 2024-10-16T12:29:44.418Z
first time: 2024-10-16T16:57:59.188Z
last time: 2024-10-16T16:57:59.188Z
first time: 2024-10-16T16:33:48.114Z
last time: 2024-10-16T16:54:07.825Z
first time: 2024-10-16T13:24:27.316Z
last time: 2024-10-16T13:33:05.513Z
first time: 2024-10-16T15:31:10.884Z
last time: 2024-10-16T15:33:17.703Z
first time: 2024-10-14T09:26:10.371Z
last time: 2024-10-14T09:40:48.551Z
first time: 2024-10-16T17:52:13.696Z
last time: 2024-10-16T17:55:13.199Z
first time: 2024-10-15T09:33:33.741Z
last time: 2024-10-15T10:01:44.693Z
first time: 2024-10-16T13:35:42.983Z
last time: 2024-10-16T13:42:58.944Z
first time: 2024-10-14T11:03:13.924Z
last time: 2024-10-14T11:14:03.807Z
first time: 2024-10-16T13:15:05.939Z
last time: 2024-10-16T13:29:24.287Z
first time: 2024-10-16T15:24:15.573Z
last time: 2024-10-16T16:26:46.218Z
first time: 2024-10-17T12:30:03.269Z
last time: 2024-10-17T12:46:21.826Z
first time: 2024-10-16T12:40:53.782Z
last time: 2024-10-16T13:39:20.858Z
first time: 2024-10-16T18:55:18.468Z
last time: 2024-10-16T19:21:37.015Z
first time: 2024-10-16T21:23:24.248Z
last time: 2024-10-16T21:37:57.201Z
first time: 2024-10-17T13:46:01.162Z
last time: 2024-10-17T13:46:07.001Z
first time: 2024-10-16T14:57:29.947Z
last time: 2024-10-16T15:02:50.846Z
first time: 2024-10-17T08:03:35.375Z
last time: 2024-10-17T08:18:04.764Z
first time: 2024-10-16T17:35:27.338Z
last time: 2024-10-16T17:37:38.015Z
first time: 2024-10-16T17:27:07.505Z
last time: 2024-10-16T17:31:55.759Z
first time: 2024-10-16T18:50:38.215Z
last time: 2024-10-16T19:17:35.511Z
first time: 2024-10-17T04:46:57.839Z
last time: 2024-10-17T04:53:41.907Z
first time: 2024-10-16T16:28:10.403Z
last time: 2024-10-16T16:37:38.997Z
first time: 2024-10-16T18:01:31.549Z
last time: 2024-10-16T18:19:22.375Z
first time: 2024-10-17T08:29:40.046Z
last time: 2024-10-17T08:37:16.429Z
first time: 2024-10-16T13:17:39.257Z
last time: 2024-10-16T13:35:44.888Z
first time: 2024-10-16T20:27:39.185Z
last time: 2024-10-16T20:36:24.100Z
first time: 2024-10-16T13:42:40.577Z
last time: 2024-10-16T13:46:12.422Z
first time: 2024-10-17T12:36:29.922Z
last time: 2024-10-17T12:55:24.134Z
first time: 2024-10-16T13:18:05.793Z
last time: 2024-10-16T13:25:00.998Z
first time: 2024-10-15T09:27:02.217Z
last time: 2024-10-15T09:35:07.079Z
first time: 2024-10-17T08:34:01.579Z
last time: 2024-10-17T08:44:42.433Z
first time: 2024-10-16T13:47:56.602Z
last time: 2024-10-16T13:52:36.537Z
first time: 2024-10-16T14:39:30.849Z
last time: 2024-10-16T14:39:50.138Z
first time: 2024-10-14T09:37:42.645Z
last time: 2024-10-14T09:43:06.140Z
first time: 2024-10-16T16:45:26.699Z
last time: 2024-10-16T16:52:07.147Z
first time: 2024-10-17T15:48:00.714Z
last time: 2024-10-17T17:07:08.859Z
first time: 2024-10-15T09:29:57.635Z
last time: 2024-10-15T09:37:07.172Z
first time: 2024-10-17T14:08:12.089Z
last time: 2024-10-17T14:11:23.315Z
first time: 2024-10-16T17:52:51.262Z
last time: 2024-10-16T18:06:05.179Z
first time: 2024-10-16T20:04:12.245Z
last time: 2024-10-16T20:10:49.378Z
first time: 2024-10-17T15:10:34.023Z
last time: 2024-10-17T15:14:02.146Z
first time: 2024-10-15T09:27:49.443Z
last time: 2024-10-15T09:33:00.086Z
first time: 2024-10-16T17:01:21.536Z
last time: 2024-10-16T17:09:19.240Z
first time: 2024-10-16T12:33:39.033Z
last time: 2024-10-16T12:37:27.101Z
first time: 2024-10-17T15:01:08.598Z
last time: 2024-10-17T15:27:18.643Z
first time: 2024-10-17T10:21:38.346Z
last time: 2024-10-17T10:29:47.265Z
first time: 2024-10-16T17:36:13.101Z
last time: 2024-10-16T18:09:11.080Z
first time: 2024-10-16T12:20:05.758Z
last time: 2024-10-16T12:34:35.449Z
first time: 2024-10-16T12:28:50.839Z
last time: 2024-10-16T12:38:26.568Z
first time: 2024-10-16T14:13:09.303Z
last time: 2024-10-16T14:13:45.726Z
first time: 2024-10-17T04:09:17.322Z
last time: 2024-10-17T04:23:20.122Z
first time: 2024-10-16T20:46:41.649Z
last time: 2024-10-16T20:49:08.896Z
first time: 2024-10-16T18:20:33.065Z
last time: 2024-10-16T18:24:59.191Z
first time: 2024-10-15T09:28:29.921Z
last time: 2024-10-15T09:34:19.921Z
first time: 2024-10-16T17:04:17.687Z
last time: 2024-10-16T17:08:35.749Z
first time: 2024-10-14T09:27:04.611Z
last time: 2024-10-14T09:31:23.032Z
first time: 2024-10-17T08:19:23.314Z
last time: 2024-10-17T08:29:50.511Z
first time: 2024-10-16T19:05:42.598Z
last time: 2024-10-16T19:40:53.821Z
first time: 2024-10-14T10:15:49.514Z
last time: 2024-10-14T10:19:12.076Z
first time: 2024-10-17T08:31:37.650Z
last time: 2024-10-17T08:43:42.697Z
first time: 2024-10-16T12:28:16.537Z
last time: 2024-10-16T12:35:44.348Z
first time: 2024-10-15T09:27:36.119Z
last time: 2024-10-15T09:30:31.156Z
first time: 2024-10-17T13:09:03.855Z
last time: 2024-10-17T13:17:36.589Z
first time: 2024-10-17T13:59:07.367Z
last time: 2024-10-17T14:11:15.106Z
first time: 2024-10-16T14:43:53.164Z
last time: 2024-10-16T14:43:59.668Z
first time: 2024-10-16T15:01:54.902Z
last time: 2024-10-16T15:05:51.645Z
first time: 2024-10-17T16:28:39.902Z
last time: 2024-10-17T16:44:21.191Z
first time: 2024-10-16T20:38:58.097Z
last time: 2024-10-16T20:41:49.487Z
first time: 2024-10-16T12:42:25.140Z
last time: 2024-10-16T12:57:11.003Z
first time: 2024-10-17T09:22:50.316Z
last time: 2024-10-17T09:26:25.355Z
first time: 2024-10-17T12:18:29.648Z
last time: 2024-10-17T12:22:26.227Z
first time: 2024-10-16T12:28:11.753Z
last time: 2024-10-16T12:53:25.568Z
first time: 2024-10-16T13:50:25.915Z
last time: 2024-10-16T13:53:48.448Z
first time: 2024-10-16T20:31:12.818Z
last time: 2024-10-16T20:44:54.459Z
first time: 2024-10-16T21:24:58.773Z
last time: 2024-10-16T21:27:48.527Z
first time: 2024-10-16T12:29:36.808Z
last time: 2024-10-16T13:34:57.982Z
first time: 2024-10-16T17:26:19.321Z
last time: 2024-10-16T17:37:50.820Z
first time: 2024-10-17T13:56:33.005Z
last time: 2024-10-17T13:58:45.397Z
first time: 2024-10-17T14:50:25.988Z
last time: 2024-10-17T14:59:21.951Z
first time: 2024-10-15T09:35:07.273Z
last time: 2024-10-15T11:48:12.022Z
first time: 2024-10-16T14:06:51.578Z
last time: 2024-10-16T14:11:29.080Z
first time: 2024-10-17T07:54:24.203Z
last time: 2024-10-17T08:05:59.280Z
first time: 2024-10-17T14:55:45.022Z
last time: 2024-10-17T15:16:40.801Z
first time: 2024-10-17T14:41:56.701Z
last time: 2024-10-17T14:50:33.764Z
first time: 2024-10-16T15:38:52.586Z
last time: 2024-10-16T16:02:23.916Z
first time: 2024-10-16T14:55:11.630Z
last time: 2024-10-16T15:04:19.421Z
first time: 2024-10-16T16:12:09.263Z
last time: 2024-10-16T16:16:16.488Z
first time: 2024-10-14T09:34:37.297Z
last time: 2024-10-14T09:38:35.807Z
first time: 2024-10-16T16:15:43.151Z
last time: 2024-10-16T16:26:31.664Z
first time: 2024-10-16T19:52:53.583Z
last time: 2024-10-16T20:07:10.442Z
first time: 2024-10-16T17:07:58.612Z
last time: 2024-10-16T17:19:33.452Z
first time: 2024-10-15T09:33:35.810Z
last time: 2024-10-15T09:48:26.521Z
first time: 2024-10-17T14:35:09.639Z
last time: 2024-10-17T14:46:52.134Z
first time: 2024-10-16T20:08:59.019Z
last time: 2024-10-16T20:12:07.083Z
first time: 2024-10-16T12:29:22.422Z
last time: nan
first time: 2024-10-16T16:37:59.730Z
last time: 2024-10-16T17:04:12.533Z
first time: 2024-10-14T10:20:26.984Z
last time: 2024-10-14T10:23:09.858Z
first time: 2024-10-17T04:51:20.362Z
last time: 2024-10-17T05:03:22.478Z
first time: 2024-10-16T21:37:32.190Z
last time: 2024-10-16T21:42:42.851Z
first time: 2024-10-16T19:15:30.407Z
last time: 2024-10-16T22:51:28.446Z
first time: 2024-10-16T17:16:12.398Z
last time: 2024-10-16T17:18:42.602Z
first time: 2024-10-16T16:03:45.911Z
last time: 2024-10-16T17:54:11.835Z
first time: 2024-10-16T18:35:13.341Z
last time: 2024-10-16T18:44:45.661Z
first time: 2024-10-16T19:22:22.352Z
last time: 2024-10-17T20:51:57.862Z
first time: 2024-10-16T13:30:26.909Z
last time: 2024-10-16T13:42:42.551Z
first time: 2024-10-16T16:57:39.178Z
last time: 2024-10-16T17:05:13.099Z
first time: 2024-10-14T10:16:16.654Z
last time: 2024-10-14T10:32:46.459Z
first time: 2024-10-16T23:21:12.481Z
last time: 2024-10-16T23:22:53.022Z
first time: 2024-10-16T14:48:37.025Z
last time: 2024-10-16T14:51:04.066Z
first time: 2024-10-16T20:54:16.579Z
last time: 2024-10-16T21:08:39.936Z
first time: 2024-10-17T13:50:47.268Z
last time: 2024-10-17T14:02:57.197Z
first time: 2024-10-16T14:04:58.912Z

first time: 2024-10-16T14:05:56.446Z
last time: 2024-10-16T14:12:17.876Z
first time: 2024-10-16T12:43:32.081Z
last time: 2024-10-16T12:57:46.904Z
first time: 2024-10-15T09:28:39.460Z
last time: 2024-10-15T09:39:32.168Z
first time: 2024-10-16T15:02:37.951Z
last time: 2024-10-16T15:06:12.587Z
first time: 2024-10-17T14:47:07.813Z
last time: 2024-10-17T14:55:03.302Z
first time: 2024-10-17T04:14:51.252Z
last time: 2024-10-17T04:24:00.204Z
first time: 2024-10-16T12:24:04.866Z
last time: 2024-10-16T12:36:49.169Z
first time: 2024-10-16T13:18:54.396Z
last time: 2024-10-16T13:21:35.916Z
first time: 2024-10-16T14:44:30.787Z
last time: 2024-10-16T14:58:56.078Z
first time: 2024-10-17T08:43:30.815Z
last time: 2024-10-17T08:55:52.786Z
first time: 2024-10-16T22:22:23.766Z
last time: 2024-10-16T22:42:22.544Z
first time: 2024-10-16T13:38:23.289Z
last time: 2024-10-16T13:41:07.096Z
first time: 2024-10-16T17:06:13.674Z
last time: 2024-10-16T17:11:09.975Z
first time: 2024-10-16T15:29:08.419Z
last time: 2024-10-16T15:42:42.158Z
first time: 2024-10-16T14:24:05.416Z
last time: 2024-10-16T14:31:15.411Z
first time: 2024-10-16T16:29:41.584Z
last time: 2024-10-16T16:39:00.522Z
first time: 2024-10-16T13:31:07.152Z
last time: 2024-10-16T13:45:00.290Z
first time: 2024-10-16T23:05:03.996Z
last time: 2024-10-16T23:19:44.075Z
first time: 2024-10-16T13:45:10.138Z
last time: 2024-10-16T14:00:08.890Z
first time: 2024-10-16T20:58:05.486Z
last time: 2024-10-16T21:13:15.147Z
first time: 2024-10-16T20:14:16.782Z
last time: 2024-10-16T20:42:26.082Z
first time: 2024-10-16T16:53:57.125Z
last time: 2024-10-16T16:55:46.961Z
first time: 2024-10-16T17:57:32.213Z
last time: 2024-10-16T18:13:38.283Z
first time: 2024-10-16T13:38:57.173Z
last time: 2024-10-16T13:42:40.614Z
first time: 2024-10-14T09:34:04.964Z
last time: 2024-10-14T09:45:41.054Z
first time: 2024-10-16T12:23:36.783Z
last time: 2024-10-16T12:38:27.436Z
first time: 2024-10-16T13:17:34.757Z
last time: 2024-10-16T13:25:41.135Z
first time: 2024-10-17T09:36:17.096Z
last time: 2024-10-17T10:03:06.267Z
first time: 2024-10-16T18:04:40.122Z
last time: 2024-10-16T18:14:56.361Z
first time: 2024-10-16T13:30:28.561Z
last time: 2024-10-16T13:54:48.227Z
first time: 2024-10-17T08:19:54.678Z
last time: 2024-10-17T08:37:58.858Z
first time: 2024-10-16T14:40:43.335Z
last time: 2024-10-16T14:58:16.586Z
first time: 2024-10-16T12:21:33.423Z
last time: 2024-10-16T12:37:50.964Z
first time: 2024-10-16T16:56:00.947Z
last time: 2024-10-16T17:13:22.252Z
first time: 2024-10-15T09:51:56.673Z
last time: 2024-10-15T10:19:08.479Z
first time: 2024-10-16T16:58:50.964Z
last time: 2024-10-16T17:03:49.174Z
first time: 2024-10-16T16:19:03.746Z
last time: 2024-10-16T16:32:06.042Z
first time: 2024-10-16T13:17:05.513Z
last time: 2024-10-16T13:21:24.024Z
first time: 2024-10-15T09:32:20.707Z
last time: 2024-10-15T09:47:13.337Z
first time: 2024-10-15T09:30:24.767Z
last time: 2024-10-15T09:38:24.287Z
first time: 2024-10-16T13:25:57.580Z
last time: 2024-10-16T13:43:52.435Z
first time: 2024-10-15T09:36:59.870Z
last time: 2024-10-15T10:03:54.812Z
first time: 2024-10-17T16:57:30.959Z
last time: 2024-10-17T17:16:13.133Z
first time: 2024-10-16T12:28:02.607Z
last time: 2024-10-16T12:34:57.321Z
first time: 2024-10-16T18:00:29.086Z
last time: 2024-10-16T18:09:00.529Z
first time: 2024-10-17T07:46:20.637Z
last time: 2024-10-17T07:52:28.711Z
first time: 2024-10-17T04:40:51.385Z
last time: 2024-10-17T04:57:37.308Z
first time: 2024-10-15T09:32:55.461Z
last time: 2024-10-15T09:45:15.318Z
first time: 2024-10-16T21:43:39.913Z
last time: 2024-10-16T21:49:39.975Z
first time: 2024-10-16T15:34:28.457Z
last time: 2024-10-16T15:42:38.294Z
first time: 2024-10-14T09:35:06.163Z
last time: 2024-10-14T09:56:05.609Z
first time: 2024-10-16T17:09:41.444Z
last time: 2024-10-16T17:17:23.385Z
first time: 2024-10-16T17:54:49.317Z
last time: 2024-10-16T17:55:34.096Z
first time: 2024-10-14T09:27:33.757Z
last time: 2024-10-14T09:30:49.347Z
first time: 2024-10-14T09:33:37.771Z
last time: 2024-10-14T09:36:18.347Z
first time: 2024-10-16T12:44:18.417Z
last time: 2024-10-16T13:05:36.548Z
first time: 2024-10-16T12:40:41.627Z
last time: 2024-10-16T12:41:24.089Z
first time: 2024-10-14T09:31:38.176Z
last time: 2024-10-14T09:37:17.028Z
first time: 2024-10-14T10:17:14.152Z
last time: 2024-10-14T10:42:35.763Z
first time: 2024-10-17T09:34:30.017Z
last time: 2024-10-17T09:49:08.006Z
first time: 2024-10-16T12:18:53.119Z
last time: 2024-10-16T12:21:56.076Z
first time: 2024-10-15T09:29:34.150Z
last time: 2024-10-15T09:32:40.460Z
first time: 2024-10-17T07:19:32.046Z
last time: 2024-10-17T07:26:32.188Z
first time: 2024-10-17T04:00:42.813Z
last time: 2024-10-17T04:04:58.063Z
first time: 2024-10-16T14:37:05.599Z
last time: 2024-10-16T14:44:20.816Z
first time: 2024-10-16T15:43:49.977Z
last time: 2024-10-16T15:56:13.709Z
first time: 2024-10-17T16:07:42.849Z
last time: 2024-10-17T16:19:21.815Z
first time: 2024-10-14T10:24:58.039Z
last time: 2024-10-14T10:50:59.030Z
first time: 2024-10-16T14:28:01.559Z
last time: 2024-10-16T14:37:48.250Z
first time: 2024-10-14T09:30:33.703Z
last time: 2024-10-14T09:45:51.062Z
first time: 2024-10-17T13:01:07.048Z
last time: 2024-10-17T13:09:09.061Z
first time: 2024-10-14T09:29:03.354Z
last time: 2024-10-14T09:31:24.562Z
first time: 2024-10-16T16:44:50.292Z
last time: 2024-10-16T16:52:01.583Z
first time: 2024-10-16T17:01:15.302Z
last time: 2024-10-16T17:11:51.090Z
first time: 2024-10-16T12:33:04.483Z
last time: 2024-10-16T12:50:24.981Z
first time: 2024-10-14T09:27:26.714Z
last time: 2024-10-14T09:32:17.595Z
first time: 2024-10-16T14:37:23.108Z
last time: 2024-10-16T14:43:16.487Z
first time: 2024-10-16T15:23:26.524Z
last time: 2024-10-16T15:34:23.905Z
first time: 2024-10-17T04:09:07.221Z
last time: 2024-10-17T04:21:10.618Z
first time: 2024-10-15T09:27:36.910Z
last time: 2024-10-15T09:32:15.922Z
first time: 2024-10-14T09:33:15.817Z
last time: 2024-10-14T09:54:33.253Z
first time: 2024-10-14T10:19:16.809Z
last time: 2024-10-14T10:39:41.014Z
first time: 2024-10-14T10:16:43.849Z
last time: 2024-10-14T10:31:21.490Z
first time: 2024-10-16T17:34:11.516Z
last time: 2024-10-16T17:56:42.035Z
first time: 2024-10-16T16:36:18.443Z
last time: 2024-10-16T16:40:44.809Z
first time: 2024-10-16T18:22:11.098Z
last time: 2024-10-16T18:27:22.240Z
first time: 2024-10-17T06:53:11.405Z
last time: 2024-10-17T07:11:29.866Z
first time: 2024-10-16T16:07:47.190Z
last time: 2024-10-16T16:29:05.706Z
first time: 2024-10-14T09:31:10.569Z
last time: 2024-10-14T09:36:06.915Z
first time: 2024-10-16T19:47:57.208Z
last time: 2024-10-16T19:53:33.472Z
first time: 2024-10-16T13:25:55.307Z
last time: 2024-10-16T13:37:58.008Z
first time: 2024-10-16T16:42:23.648Z
last time: 2024-10-16T17:13:31.288Z
first time: 2024-10-17T13:38:25.222Z
last time: 2024-10-17T13:38:55.334Z
first time: 2024-10-16T20:16:23.186Z
last time: 2024-10-16T20:17:52.525Z
first time: 2024-10-16T20:18:19.874Z
last time: 2024-10-16T20:28:02.025Z
first time: 2024-10-14T09:33:41.781Z
last time: 2024-10-14T09:45:07.233Z
first time: 2024-10-16T13:06:49.001Z
last time: 2024-10-16T13:27:16.464Z
first time: 2024-10-17T08:45:03.344Z
last time: 2024-10-17T09:07:16.242Z
first time: 2024-10-17T08:59:54.275Z
last time: 2024-10-17T09:22:25.662Z
first time: 2024-10-14T09:30:31.498Z
last time: 2024-10-14T09:38:55.704Z
first time: 2024-10-16T13:24:13.186Z
last time: 2024-10-16T13:37:33.136Z
first time: 2024-10-16T20:24:48.133Z
last time: 2024-10-16T20:26:47.788Z
first time: 2024-10-17T04:26:20.267Z
last time: 2024-10-17T04:34:33.011Z
first time: 2024-10-17T14:02:21.051Z
last time: 2024-10-17T14:15:19.017Z
first time: 2024-10-15T09:28:21.728Z
last time: 2024-10-15T09:30:47.810Z

/tmp/ipykernel_5237/83090093.py:20: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df = df.groupby('psid').apply(calculate_time_diff)

                          psid  time_difference
0     _1KUVoNGiAg-FXLYMSdwbQ**        15.752767
1     _1KUVoNGiAg-GTXuLE-E1g**       146.594367
2     _1KUVoNGiAg-ODrdbezcMw**        15.361583
3     _1KUVoNGiAg-d35IGIrcEA**        13.656383
4     _1KUVoNGiAg0OjdoLHQ17Q**        12.528833
...                        ...              ...
1427  _1KUVoNGiAjyy-x0jm2qrw**        13.332500
1428  _1KUVoNGiAjz-R_IQlXnww**         1.994250
1429  _1KUVoNGiAjz9z84bgIj8Q**         8.212400
1430  _1KUVoNGiAjzcvail1lDPA**        12.966100
1431  _1KUVoNGiAjzeHozgt9H4w**         2.434700

[1432 rows x 2 columns]

In [18]:
# Calculate the mean and median of time_difference
mean_time_difference = last_observation['time_difference'].mean()
median_time_difference = last_observation['time_difference'].median()

print("Mean time difference:", mean_time_difference)
print("Median time difference:", median_time_difference)

import numpy as np

# Calculate the 80th percentile of time_difference

percentile_80 = np.percentile(last_observation['time_difference'], 80)

print(f"80% of the sample completed within {percentile_80} minutes.")

Mean time difference: 23.889002182539688
Median time difference: 11.464291666666668
80% of the sample completed within nan minutes.

In [19]:
# Check for NaN values in time_difference
missing_values = last_observation['time_difference'].isnull().sum()
print(f"Missing values in time_difference: {missing_values}")

Missing values in time_difference: 4

In [20]:
# Option 1: Drop NaN values
last_observation_cleaned = last_observation.dropna(subset=['time_difference'])

# Option 2: Fill NaN values with the median
last_observation['time_difference'].fillna(median_time_difference, inplace=True)

In [21]:
# Calculate the 80th percentile again
percentile_80 = np.percentile(last_observation_cleaned['time_difference'], 80)
print(f"80% of the sample completed within {percentile_80} minutes.")

80% of the sample completed within 19.86062333333334 minutes.

In [376]:
np.percentile(last_observation['time_difference'],80)

nan

In [22]:
df[['psid','StartDate_y', 'time_answer']]

,psid,StartDate_y,time_answer
128908,_1KUVoNGiAg-FXLYMSdwbQ**,2024-10-16 11:31:58,2024-10-16T17:33:13.655Z
128921,_1KUVoNGiAg-FXLYMSdwbQ**,2024-10-16 11:31:58,2024-10-16T17:33:18.855Z
128922,_1KUVoNGiAg-FXLYMSdwbQ**,2024-10-16 11:31:58,2024-10-16T17:33:31.925Z
128923,_1KUVoNGiAg-FXLYMSdwbQ**,2024-10-16 11:31:58,2024-10-16T17:33:34.434Z
128924,_1KUVoNGiAg-FXLYMSdwbQ**,2024-10-16 11:31:58,2024-10-16T17:33:36.176Z
...,...,...,...
115269,_1KUVoNGiAjzeHozgt9H4w**,2024-10-15 03:27:43,2024-10-15T09:30:45.238Z
115282,_1KUVoNGiAjzeHozgt9H4w**,2024-10-15 03:27:43,2024-10-15T09:30:47.295Z
115283,_1KUVoNGiAjzeHozgt9H4w**,2024-10-15 03:27:43,2024-10-15T09:30:47.429Z
115284,_1KUVoNGiAjzeHozgt9H4w**,2024-10-15 03:27:43,2024-10-15T09:30:47.580Z
115285,_1KUVoNGiAjzeHozgt9H4w**,2024-10-15 03:27:43,2024-10-15T09:30:47.810Z

In [352]:
import pandas as pd
import pytz

# Convert 'time_answer' to datetime and ensure it's in UTC
# Convert 'time_answer' to UTC
df['time_answer'] = pd.to_datetime(df['time_answer'], errors='coerce', utc=True)

# Define local timezone (CET/CEST)
local_tz = pytz.timezone('Europe/Amsterdam')

# Convert 'StartDate_First' column to datetime object in local time
df['StartDate_First'] = pd.to_datetime(df['StartDate_First'], errors='coerce')
df['StartDate_First_ISO'] = df['StartDate_First'].dt.tz_localize(local_tz)  # Localize to Amsterdam time
df['StartDate_First_ISO'] = df['StartDate_First_ISO'].dt.tz_convert('UTC')  # Convert to UTC

# Show the DataFrame with the new columns
#print(df[['StartDate_First', 'StartDate_First_ISO', 'time_answer']])

# Calculate time difference in seconds
#df['time_difference'] = df['time_answer'] - df['StartDate_First_ISO']

In [330]:
df['time_difference'].mean()

Timedelta('0 days 08:28:24.348904332')

In [356]:
print(df[['StartDate_y', 'time_answer']].head())

           StartDate_y                      time_answer
0  2024-10-14 03:25:32 2024-10-14 09:27:33.757000+00:00
1  2024-10-14 03:26:54 2024-10-14 09:28:10.626000+00:00
2  2024-10-14 03:25:32 2024-10-14 09:27:35.600000+00:00
3  2024-10-14 03:25:32 2024-10-14 09:27:56.518000+00:00
4  2024-10-14 03:25:32 2024-10-14 09:28:02.175000+00:00

In [ ]:
# Step 1: Convert 'time_answer' and 'StartDate_First' columns to datetime objects in UTC
df['time_answer'] = pd.to_datetime(df['time_answer'], errors='coerce', utc=True)
df['StartDate_First'] = pd.to_datetime(df['StartDate_First'], errors='coerce', utc=True)

# Step 2: Calculate the time difference
df['time_difference'] = df['time_answer'] - df['StartDate_First']

# Display the DataFrame with time differences
print(df[['StartDate_First', 'time_answer', 'time_difference']])

In [332]:
# Step 1: Convert 'time_answer' and 'StartDate_First' columns to datetime objects in UTC
df['time_answer'] = pd.to_datetime(df['time_answer'], errors='coerce', utc=True)
df['StartDate_First'] = pd.to_datetime(df['StartDate_First'], errors='coerce', utc=True)

# Step 2: Calculate the time difference
df['time_difference'] = df['time_answer'] - df['StartDate_First']

# Display the DataFrame with time differences
print(df[['StartDate_First', 'time_answer', 'time_difference']])

                 StartDate_First                      time_answer  \
117758 2024-10-16 11:22:46+00:00 2024-10-16 17:33:13.655000+00:00
117771 2024-10-16 11:22:46+00:00 2024-10-16 17:33:18.855000+00:00
117772 2024-10-16 11:22:46+00:00 2024-10-16 17:33:31.925000+00:00
117773 2024-10-16 11:22:46+00:00 2024-10-16 17:33:34.434000+00:00
117774 2024-10-16 11:22:46+00:00 2024-10-16 17:33:36.176000+00:00
...                          ...                              ...
126752                       NaT 2024-10-17 09:48:49.697000+00:00
126753                       NaT 2024-10-17 09:49:08.258000+00:00
126754                       NaT 2024-10-17 09:49:11.106000+00:00
126755                       NaT 2024-10-17 09:49:14.379000+00:00
126756                       NaT 2024-10-17 09:49:16.924000+00:00

              time_difference
117758 0 days 06:10:27.655000
117771 0 days 06:10:32.855000
117772 0 days 06:10:45.925000
117773 0 days 06:10:48.434000
117774 0 days 06:10:50.176000
...                       ...
126752                    NaT
126753                    NaT
126754                    NaT
126755                    NaT
126756                    NaT

[152301 rows x 3 columns]

In [335]:
list(df['time_difference'])

[Timedelta('0 days 06:10:27.655000'),
 Timedelta('0 days 06:10:32.855000'),
 Timedelta('0 days 06:10:45.925000'),
 Timedelta('0 days 06:10:48.434000'),
 Timedelta('0 days 06:10:50.176000'),
 Timedelta('0 days 06:10:51.742000'),
 Timedelta('0 days 06:11:24.630000'),
 Timedelta('0 days 06:11:32.038000'),
 Timedelta('0 days 06:11:35.733000'),
 Timedelta('0 days 06:11:54.613000'),
 Timedelta('0 days 06:11:57.744000'),
 Timedelta('0 days 06:12:32.449000'),
 Timedelta('0 days 06:12:38.565000'),
 Timedelta('0 days 06:12:40.374000'),
 Timedelta('0 days 06:12:42.958000'),
 Timedelta('0 days 06:13:17.801000'),
 Timedelta('0 days 06:13:19.541000'),
 Timedelta('0 days 06:13:20.558000'),
 Timedelta('0 days 06:13:22.472000'),
 Timedelta('0 days 06:13:29.756000'),
 Timedelta('0 days 06:13:31.277000'),
 Timedelta('0 days 06:13:33.799000'),
 Timedelta('0 days 06:13:35.668000'),
 Timedelta('0 days 06:14:06.537000'),
 Timedelta('0 days 06:14:07.811000'),
 Timedelta('0 days 06:14:08.972000'),
 Timedelta('0 days 06:14:10.010000'),
 Timedelta('0 days 06:14:25.070000'),
 Timedelta('0 days 06:14:26.278000'),
 Timedelta('0 days 06:14:26.993000'),
 Timedelta('0 days 06:14:27.862000'),
 Timedelta('0 days 06:15:08.665000'),
 Timedelta('0 days 06:15:12.108000'),
 Timedelta('0 days 06:15:15.683000'),
 Timedelta('0 days 06:15:20.203000'),
 Timedelta('0 days 06:15:34.604000'),
 Timedelta('0 days 06:15:35.605000'),
 Timedelta('0 days 06:15:36.004000'),
 Timedelta('0 days 06:15:37.154000'),
 Timedelta('0 days 06:15:48.581000'),
 Timedelta('0 days 06:15:49.598000'),
 Timedelta('0 days 06:15:50.276000'),
 Timedelta('0 days 06:15:50.644000'),
 Timedelta('0 days 06:16:16.440000'),
 Timedelta('0 days 06:16:18.200000'),
 Timedelta('0 days 06:16:18.989000'),
 Timedelta('0 days 06:16:20.090000'),
 Timedelta('0 days 06:16:41.577000'),
 Timedelta('0 days 06:16:42.953000'),
 Timedelta('0 days 06:16:43.810000'),
 Timedelta('0 days 06:16:45.962000'),
 Timedelta('0 days 06:17:03.638000'),
 Timedelta('0 days 06:17:05.620000'),
 Timedelta('0 days 06:17:07.597000'),
 Timedelta('0 days 06:17:11.428000'),
 Timedelta('0 days 06:17:40.723000'),
 Timedelta('0 days 06:17:43.146000'),
 Timedelta('0 days 06:17:44.020000'),
 Timedelta('0 days 06:17:45.958000'),
 Timedelta('0 days 06:18:11.813000'),
 Timedelta('0 days 06:18:12.695000'),
 Timedelta('0 days 06:18:13.445000'),
 Timedelta('0 days 06:18:14.753000'),
 Timedelta('0 days 06:18:42.354000'),
 Timedelta('0 days 06:18:45.526000'),
 Timedelta('0 days 06:18:48.022000'),
 Timedelta('0 days 06:18:49.238000'),
 Timedelta('0 days 06:19:01.309000'),
 Timedelta('0 days 06:19:01.937000'),
 Timedelta('0 days 06:19:02.389000'),
 Timedelta('0 days 06:19:08.503000'),
 Timedelta('0 days 06:19:24.449000'),
 Timedelta('0 days 06:19:25.744000'),
 Timedelta('0 days 06:19:26.888000'),
 Timedelta('0 days 06:19:28.699000'),
 Timedelta('0 days 06:21:29.581000'),
 Timedelta('0 days 06:21:30.085000'),
 Timedelta('0 days 06:21:30.403000'),
 Timedelta('0 days 06:21:30.661000'),
 Timedelta('0 days 06:22:02.467000'),
 Timedelta('0 days 06:22:05.085000'),
 Timedelta('0 days 06:22:08.016000'),
 Timedelta('0 days 06:22:09.110000'),
 Timedelta('0 days 06:22:24.961000'),
 Timedelta('0 days 06:22:25.381000'),
 Timedelta('0 days 06:22:25.686000'),
 Timedelta('0 days 06:22:26.029000'),
 Timedelta('0 days 06:22:44.240000'),
 Timedelta('0 days 06:22:44.522000'),
 Timedelta('0 days 06:22:44.830000'),
 Timedelta('0 days 06:22:45.074000'),
 Timedelta('0 days 06:22:50.806000'),
 Timedelta('0 days 06:22:52.092000'),
 Timedelta('0 days 06:22:53.531000'),
 Timedelta('0 days 06:22:54.193000'),
 Timedelta('0 days 06:23:09.350000'),
 Timedelta('0 days 06:23:16.818000'),
 Timedelta('0 days 06:23:19.598000'),
 Timedelta('0 days 06:23:19.835000'),
 Timedelta('0 days 06:23:33.249000'),
 Timedelta('0 days 06:23:35.093000'),
 Timedelta('0 days 06:23:36.402000'),
 Timedelta('0 days 06:23:37.611000'),
 Timedelta('0 days 06:23:48.246000'),
 Timedelta('0 days 06:23:48.612000'),
 Timedelta('0 days 06:23:48.891000'),
 Timedelta('0 days 06:23:49.231000'),
 Timedelta('0 days 06:24:12.632000'),
 Timedelta('0 days 06:24:12.950000'),
 Timedelta('0 days 06:24:13.241000'),
 Timedelta('0 days 06:24:13.513000'),
 Timedelta('0 days 06:24:30.547000'),
 Timedelta('0 days 06:24:30.884000'),
 Timedelta('0 days 06:24:31.228000'),
 Timedelta('0 days 06:24:31.581000'),
 Timedelta('0 days 06:24:45.401000'),
 Timedelta('0 days 06:24:46.466000'),
 Timedelta('0 days 06:24:47.533000'),
 Timedelta('0 days 06:24:48.760000'),
 Timedelta('0 days 06:25:05.844000'),
 Timedelta('0 days 06:25:10.854000'),
 Timedelta('0 days 06:25:11.883000'),
 Timedelta('0 days 06:25:13.842000'),
 Timedelta('0 days 06:25:42.537000'),
 Timedelta('0 days 06:25:48.304000'),
 Timedelta('0 days 06:25:50.766000'),
 Timedelta('0 days 06:25:55.210000'),
 Timedelta('0 days 06:26:08.057000'),
 Timedelta('0 days 06:26:09.731000'),
 Timedelta('0 days 06:26:10.268000'),
 Timedelta('0 days 06:26:12.821000'),
 Timedelta('0 days 06:11:37.479000'),
 Timedelta('0 days 06:11:43.338000'),
 Timedelta('0 days 06:12:03.472000'),
 Timedelta('0 days 06:12:13.035000'),
 Timedelta('0 days 06:12:15.069000'),
 Timedelta('0 days 06:12:17.940000'),
 Timedelta('0 days 06:12:45.434000'),
 Timedelta('0 days 06:12:54.618000'),
 Timedelta('0 days 06:13:00.574000'),
 Timedelta('0 days 06:13:07.527000'),
 Timedelta('0 days 06:13:11.067000'),
 Timedelta('0 days 06:14:47.267000'),
 Timedelta('0 days 06:14:50.109000'),
 Timedelta('0 days 06:14:52.359000'),
 Timedelta('0 days 06:14:55.363000'),
 Timedelta('0 days 06:17:08.601000'),
 Timedelta('0 days 06:17:12.834000'),
 Timedelta('0 days 06:17:14.933000'),
 Timedelta('0 days 06:17:19.153000'),
 Timedelta('0 days 06:18:21.792000'),
 Timedelta('0 days 06:18:23.323000'),
 Timedelta('0 days 06:18:24.675000'),
 Timedelta('0 days 06:18:28.356000'),
 Timedelta('0 days 06:18:52.191000'),
 Timedelta('0 days 06:18:53.689000'),
 Timedelta('0 days 06:18:55.163000'),
 Timedelta('0 days 06:18:56.806000'),
 Timedelta('0 days 06:19:34.044000'),
 Timedelta('0 days 06:19:36.679000'),
 Timedelta('0 days 06:19:39.080000'),
 Timedelta('0 days 06:19:40.432000'),
 Timedelta('0 days 08:28:51.204000'),
 Timedelta('0 days 08:28:54.571000'),
 Timedelta('0 days 08:28:56.189000'),
 Timedelta('0 days 08:28:57.676000'),
 Timedelta('0 days 08:29:34.513000'),
 Timedelta('0 days 08:29:37.569000'),
 Timedelta('0 days 08:29:39.852000'),
 Timedelta('0 days 08:29:41.764000'),
 Timedelta('0 days 08:29:58.350000'),
 Timedelta('0 days 08:30:02.481000'),
 Timedelta('0 days 08:30:04.120000'),
 Timedelta('0 days 08:30:06.711000'),
 Timedelta('0 days 08:30:30.090000'),
 Timedelta('0 days 08:30:31.956000'),
 Timedelta('0 days 08:30:33.908000'),
 Timedelta('0 days 08:30:35.324000'),
 Timedelta('0 days 08:31:13.567000'),
 Timedelta('0 days 08:31:15.723000'),
 Timedelta('0 days 08:31:16.819000'),
 Timedelta('0 days 08:31:18.906000'),
 Timedelta('0 days 08:31:44.252000'),
 Timedelta('0 days 08:31:46.319000'),
 Timedelta('0 days 08:31:48.008000'),
 Timedelta('0 days 08:31:49.878000'),
 Timedelta('0 days 08:32:14.745000'),
 Timedelta('0 days 08:32:16.129000'),
 Timedelta('0 days 08:32:17.296000'),
 Timedelta('0 days 08:32:19.831000'),
 Timedelta('0 days 08:32:55.409000'),
 Timedelta('0 days 08:32:57.948000'),
 Timedelta('0 days 08:33:00.718000'),
 Timedelta('0 days 08:33:03.381000'),
 Timedelta('0 days 08:33:30.605000'),
 Timedelta('0 days 08:33:32.374000'),
 Timedelta('0 days 08:33:33.311000'),
 Timedelta('0 days 08:33:35.341000'),
 Timedelta('0 days 08:33:51.462000'),
 Timedelta('0 days 08:33:53.763000'),
 Timedelta('0 days 08:33:55.843000'),
 Timedelta('0 days 08:33:57.043000'),
 Timedelta('0 days 08:34:13.789000'),
 Timedelta('0 days 08:34:17.875000'),
 Timedelta('0 days 08:34:18.794000'),
 Timedelta('0 days 08:34:19.560000'),
 Timedelta('0 days 08:34:38.225000'),
 Timedelta('0 days 08:34:39.543000'),
 Timedelta('0 days 08:34:40.426000'),
 Timedelta('0 days 08:34:41.643000'),
 Timedelta('0 days 08:34:57.619000'),
 Timedelta('0 days 08:34:58.602000'),
 Timedelta('0 days 08:34:59.404000'),
 Timedelta('0 days 08:35:00.484000'),
 Timedelta('0 days 08:35:10.105000'),
 Timedelta('0 days 08:35:11.636000'),
 Timedelta('0 days 08:35:12.955000'),
 Timedelta('0 days 08:35:13.638000'),
 Timedelta('0 days 08:35:28.074000'),
 Timedelta('0 days 08:35:29.879000'),
 Timedelta('0 days 08:35:31.476000'),
 Timedelta('0 days 08:35:33.664000'),
 Timedelta('0 days 08:35:46.427000'),
 Timedelta('0 days 08:35:47.528000'),
 Timedelta('0 days 08:35:48.515000'),
 Timedelta('0 days 08:35:49.174000'),
 Timedelta('0 days 08:36:08.967000'),
 Timedelta('0 days 08:36:10.216000'),
 Timedelta('0 days 08:36:11.403000'),
 Timedelta('0 days 08:36:12.938000'),
 Timedelta('0 days 08:36:26.265000'),
 Timedelta('0 days 08:36:27.483000'),
 Timedelta('0 days 08:36:28.593000'),
 Timedelta('0 days 08:36:29.153000'),
 Timedelta('0 days 08:36:43.599000'),
 Timedelta('0 days 08:36:44.465000'),
 Timedelta('0 days 08:36:46.400000'),
 Timedelta('0 days 08:36:47.722000'),
 Timedelta('0 days 08:37:00.131000'),
 Timedelta('0 days 08:37:01.951000'),
 Timedelta('0 days 08:37:03.037000'),
 Timedelta('0 days 08:37:03.618000'),
 Timedelta('0 days 08:37:16.064000'),
 Timedelta('0 days 08:37:17.347000'),
 Timedelta('0 days 08:37:18.564000'),
 Timedelta('0 days 08:37:19.566000'),
 Timedelta('0 days 08:37:32.383000'),
 Timedelta('0 days 08:37:33.301000'),
 Timedelta('0 days 08:37:34.648000'),
 Timedelta('0 days 08:37:35.269000'),
 Timedelta('0 days 08:37:43.621000'),
 Timedelta('0 days 08:37:44.053000'),
 Timedelta('0 days 08:37:45.575000'),
 Timedelta('0 days 08:37:46.109000'),
 Timedelta('0 days 08:37:57.413000'),
 Timedelta('0 days 08:37:59.544000'),
 Timedelta('0 days 08:38:00.646000'),
 Timedelta('0 days 08:38:01.444000'),
 Timedelta('0 days 08:38:09.235000'),
 Timedelta('0 days 08:38:10.988000'),
 Timedelta('0 days 08:38:12.509000'),
 Timedelta('0 days 08:38:13.141000'),
 Timedelta('0 days 06:15:15.734000'),
 Timedelta('0 days 06:15:21.069000'),
 Timedelta('0 days 06:15:30.277000'),
 Timedelta('0 days 06:15:35.142000'),
 Timedelta('0 days 06:15:40.653000'),
 Timedelta('0 days 06:15:59.301000'),
 Timedelta('0 days 06:16:20.005000'),
 Timedelta('0 days 06:16:37.085000'),
 Timedelta('0 days 06:16:43.622000'),
 Timedelta('0 days 06:16:48.181000'),
 Timedelta('0 days 06:16:51.237000'),
 Timedelta('0 days 06:17:24.007000'),
 Timedelta('0 days 06:17:31.309000'),
 Timedelta('0 days 06:17:39.253000'),
 Timedelta('0 days 06:17:49.397000'),
 Timedelta('0 days 06:18:22.494000'),
 Timedelta('0 days 06:18:25.038000'),
 Timedelta('0 days 06:18:28.133000'),
 Timedelta('0 days 06:18:33.205000'),
 Timedelta('0 days 06:18:49.165000'),
 Timedelta('0 days 06:18:54.245000'),
 Timedelta('0 days 06:18:55.805000'),
 Timedelta('0 days 06:18:57.925000'),
 Timedelta('0 days 06:19:22.381000'),
 Timedelta('0 days 06:19:30.237000'),
 Timedelta('0 days 06:19:36.181000'),
 Timedelta('0 days 06:19:40.573000'),
 Timedelta('0 days 06:19:59.213000'),
 Timedelta('0 days 06:19:59.901000'),
 Timedelta('0 days 06:20:00.757000'),
 Timedelta('0 days 06:20:02.141000'),
 Timedelta('0 days 06:20:28.501000'),
 Timedelta('0 days 06:20:32.125000'),
 Timedelta('0 days 06:20:34.925000'),
 Timedelta('0 days 06:20:39.133000'),
 Timedelta('0 days 06:21:06.182000'),
 Timedelta('0 days 06:21:11.437000'),
 Timedelta('0 days 06:21:16.853000'),
 Timedelta('0 days 06:21:18.070000'),
 Timedelta('0 days 06:21:53.326000'),
 Timedelta('0 days 06:22:02.262000'),
 Timedelta('0 days 06:22:05.901000'),
 Timedelta('0 days 06:22:16.205000'),
 Timedelta('0 days 06:22:35.725000'),
 Timedelta('0 days 06:22:39.397000'),
 Timedelta('0 days 06:22:40.797000'),
 Timedelta('0 days 06:22:46.557000'),
 Timedelta('0 days 06:23:01.117000'),
 Timedelta('0 days 06:23:04.381000'),
 Timedelta('0 days 06:23:08.053000'),
 Timedelta('0 days 06:23:15.661000'),
 Timedelta('0 days 06:23:35.125000'),
 Timedelta('0 days 06:23:38.765000'),
 Timedelta('0 days 06:23:40.133000'),
 Timedelta('0 days 06:23:42.701000'),
 Timedelta('0 days 06:24:04.925000'),
 Timedelta('0 days 06:24:07.989000'),
 Timedelta('0 days 06:24:11.405000'),
 Timedelta('0 days 06:24:15.317000'),
 Timedelta('0 days 06:24:23.597000'),
 Timedelta('0 days 06:24:24.629000'),
 Timedelta('0 days 06:24:27.141000'),
 Timedelta('0 days 06:24:28.621000'),
 Timedelta('0 days 06:24:44.629000'),
 Timedelta('0 days 06:24:48.021000'),
 Timedelta('0 days 06:24:49.077000'),
 Timedelta('0 days 06:24:50.949000'),
 Timedelta('0 days 06:25:06.213000'),
 Timedelta('0 days 06:25:07.197000'),
 Timedelta('0 days 06:25:08.469000'),
 Timedelta('0 days 06:25:09.813000'),
 Timedelta('0 days 06:25:26.789000'),
 Timedelta('0 days 06:25:28.565000'),
 Timedelta('0 days 06:25:30.349000'),
 Timedelta('0 days 06:25:31.485000'),
 Timedelta('0 days 06:25:42.309000'),
 Timedelta('0 days 06:25:45.101000'),
 Timedelta('0 days 06:25:46.261000'),
 Timedelta('0 days 06:25:51.085000'),
 Timedelta('0 days 06:26:21.117000'),
 Timedelta('0 days 06:26:23.004000'),
 Timedelta('0 days 06:26:24.165000'),
 Timedelta('0 days 06:26:30.533000'),
 Timedelta('0 days 06:26:41.860000'),
 Timedelta('0 days 06:26:50.237000'),
 Timedelta('0 days 06:26:52.293000'),
 Timedelta('0 days 06:27:00.093000'),
 Timedelta('0 days 06:27:14.317000'),
 Timedelta('0 days 06:27:16.821000'),
 Timedelta('0 days 06:27:19.341000'),
 Timedelta('0 days 06:27:20.725000'),
 Timedelta('0 days 06:27:37.205000'),
 Timedelta('0 days 06:27:38.709000'),
 Timedelta('0 days 06:27:40.901000'),
 Timedelta('0 days 06:27:41.453000'),
 Timedelta('0 days 06:27:52.141000'),
 Timedelta('0 days 06:27:57.357000'),
 Timedelta('0 days 06:27:57.909000'),
 Timedelta('0 days 06:27:59.516000'),
 Timedelta('0 days 06:28:11.197000'),
 Timedelta('0 days 06:28:13.765000'),
 Timedelta('0 days 06:28:15.061000'),
 Timedelta('0 days 06:28:17.109000'),
 Timedelta('0 days 06:28:35.957000'),
 Timedelta('0 days 06:28:38.973000'),
 Timedelta('0 days 06:28:40.229000'),
 Timedelta('0 days 06:28:43.141000'),
 Timedelta('0 days 06:28:57.117000'),
 Timedelta('0 days 06:28:59.141000'),
 Timedelta('0 days 06:29:03.149000'),
 Timedelta('0 days 06:29:04.813000'),
 Timedelta('0 days 06:29:20.797000'),
 Timedelta('0 days 06:29:22.837000'),
 Timedelta('0 days 06:29:24.429000'),
 Timedelta('0 days 06:29:26.477000'),
 Timedelta('0 days 06:29:40.381000'),
 Timedelta('0 days 06:29:42.629000'),
 Timedelta('0 days 06:29:48.565000'),
 Timedelta('0 days 06:29:51.981000'),
 Timedelta('0 days 06:30:04.749000'),
 Timedelta('0 days 06:30:05.349000'),
 Timedelta('0 days 06:30:06.028000'),
 Timedelta('0 days 06:30:07.308000'),
 Timedelta('0 days 06:30:18.901000'),
 Timedelta('0 days 06:30:19.525000'),
 Timedelta('0 days 06:30:20.381000'),
 Timedelta('0 days 06:30:21.381000'),
 Timedelta('0 days 06:30:34.173000'),
 Timedelta('0 days 06:30:35.140000'),
 Timedelta('0 days 06:30:36.124000'),
 Timedelta('0 days 06:30:37.429000'),
 Timedelta('0 days 06:18:55.949000'),
 Timedelta('0 days 06:19:00.480000'),
 Timedelta('0 days 06:19:11.244000'),
 Timedelta('0 days 06:19:33.134000'),
 Timedelta('0 days 06:19:36.352000'),
 Timedelta('0 days 06:19:49.988000'),
 Timedelta('0 days 06:20:02.668000'),
 Timedelta('0 days 06:20:11.424000'),
 Timedelta('0 days 06:20:13.982000'),
 Timedelta('0 days 06:20:16.994000'),
 Timedelta('0 days 06:20:21.928000'),
 Timedelta('0 days 06:20:44.549000'),
 Timedelta('0 days 06:20:55.898000'),
 Timedelta('0 days 06:20:59.438000'),
 Timedelta('0 days 06:21:06.596000'),
 Timedelta('0 days 06:21:32.056000'),
 Timedelta('0 days 06:21:36.022000'),
 Timedelta('0 days 06:21:39.075000'),
 Timedelta('0 days 06:21:42.691000'),
 Timedelta('0 days 06:21:55.999000'),
 Timedelta('0 days 06:22:00.795000'),
 Timedelta('0 days 06:22:02.805000'),
 Timedelta('0 days 06:22:04.999000'),
 Timedelta('0 days 06:22:17.933000'),
 Timedelta('0 days 06:22:22.915000'),
 Timedelta('0 days 06:22:25.823000'),
 Timedelta('0 days 06:22:28.169000'),
 Timedelta('0 days 06:22:54.164000'),
 Timedelta('0 days 06:23:00.048000'),
 Timedelta('0 days 06:23:02.480000'),
 Timedelta('0 days 06:23:05.110000'),
 Timedelta('0 days 06:23:32.244000'),
 Timedelta('0 days 06:23:35.292000'),
 Timedelta('0 days 06:23:37.234000'),
 Timedelta('0 days 06:23:39.604000'),
 Timedelta('0 days 06:23:54.733000'),
 Timedelta('0 days 06:24:00.014000'),
 Timedelta('0 days 06:24:02.370000'),
 Timedelta('0 days 06:24:05.830000'),
 Timedelta('0 days 06:24:22.034000'),
 Timedelta('0 days 06:24:26.274000'),
 Timedelta('0 days 06:24:27.553000'),
 Timedelta('0 days 06:24:29.270000'),
 Timedelta('0 days 06:24:55.813000'),
 Timedelta('0 days 06:25:02.357000'),
 Timedelta('0 days 06:25:04.527000'),
 Timedelta('0 days 06:25:06.038000'),
 Timedelta('0 days 06:25:13.983000'),
 Timedelta('0 days 06:25:17.251000'),
 Timedelta('0 days 06:25:18.589000'),
 Timedelta('0 days 06:25:20.064000'),
 Timedelta('0 days 06:25:35.832000'),
 Timedelta('0 days 06:25:38.637000'),
 Timedelta('0 days 06:25:40.003000'),
 Timedelta('0 days 06:25:42.257000'),
 Timedelta('0 days 06:25:53.387000'),
 Timedelta('0 days 06:25:58.431000'),
 Timedelta('0 days 06:26:00.699000'),
 Timedelta('0 days 06:26:02.559000'),
 Timedelta('0 days 06:26:25.977000'),
 Timedelta('0 days 06:26:30.495000'),
 Timedelta('0 days 06:26:31.211000'),
 Timedelta('0 days 06:26:32.089000'),
 Timedelta('0 days 06:26:45.159000'),
 Timedelta('0 days 06:26:48.609000'),
 Timedelta('0 days 06:26:52.523000'),
 Timedelta('0 days 06:26:54.339000'),
 Timedelta('0 days 06:27:21.143000'),
 Timedelta('0 days 06:27:23.499000'),
 Timedelta('0 days 06:27:25.879000'),
 Timedelta('0 days 06:27:26.897000'),
 Timedelta('0 days 06:27:38.287000'),
 Timedelta('0 days 06:27:40.551000'),
 Timedelta('0 days 06:27:41.751000'),
 Timedelta('0 days 06:27:43.381000'),
 Timedelta('0 days 06:28:01.471000'),
 Timedelta('0 days 06:28:03.605000'),
 Timedelta('0 days 06:28:05.377000'),
 Timedelta('0 days 06:28:07.101000'),
 Timedelta('0 days 06:28:25.352000'),
 Timedelta('0 days 06:28:28.335000'),
 Timedelta('0 days 06:28:29.390000'),
 Timedelta('0 days 06:28:30.175000'),
 Timedelta('0 days 06:28:40.272000'),
 Timedelta('0 days 06:28:42.483000'),
 Timedelta('0 days 06:28:45.639000'),
 Timedelta('0 days 06:28:47.118000'),
 Timedelta('0 days 06:29:04.933000'),
 Timedelta('0 days 06:29:07.868000'),
 Timedelta('0 days 06:29:09.341000'),
 Timedelta('0 days 06:29:12.003000'),
 Timedelta('0 days 06:29:27.160000'),
 Timedelta('0 days 06:29:29.610000'),
 Timedelta('0 days 06:29:32.300000'),
 Timedelta('0 days 06:29:34.112000'),
 Timedelta('0 days 06:29:52.630000'),
 Timedelta('0 days 06:29:55.795000'),
 Timedelta('0 days 06:29:58.216000'),
 Timedelta('0 days 06:30:01.194000'),
 Timedelta('0 days 06:30:14.596000'),
 Timedelta('0 days 06:30:18.426000'),
 Timedelta('0 days 06:30:20.394000'),
 Timedelta('0 days 06:30:22.234000'),
 Timedelta('0 days 06:30:34.961000'),
 Timedelta('0 days 06:30:40.021000'),
 Timedelta('0 days 06:30:42.380000'),
 Timedelta('0 days 06:30:44.107000'),
 Timedelta('0 days 06:30:59.425000'),
 Timedelta('0 days 06:31:01.471000'),
 Timedelta('0 days 06:31:03.563000'),
 Timedelta('0 days 06:31:05.653000'),
 Timedelta('0 days 06:31:15.169000'),
 Timedelta('0 days 06:31:16.925000'),
 Timedelta('0 days 06:31:18.051000'),
 Timedelta('0 days 06:31:18.935000'),
 Timedelta('0 days 06:31:29.611000'),
 Timedelta('0 days 06:31:32.214000'),
 Timedelta('0 days 06:31:33.773000'),
 Timedelta('0 days 06:31:35.150000'),
 Timedelta('0 days 06:31:58.188000'),
 Timedelta('0 days 06:32:00.318000'),
 Timedelta('0 days 06:32:04.286000'),
 Timedelta('0 days 06:32:05.316000'),
 Timedelta('0 days 06:32:14.005000'),
 Timedelta('0 days 06:32:17.322000'),
 Timedelta('0 days 06:32:18.738000'),
 Timedelta('0 days 06:32:20.324000'),
 Timedelta('0 days 06:32:29.542000'),
 Timedelta('0 days 06:32:32.031000'),
 Timedelta('0 days 06:32:33.599000'),
 Timedelta('0 days 06:32:35.332000'),
 Timedelta('0 days 09:36:08.400000'),
 Timedelta('0 days 09:36:16.289000'),

In [316]:
# Check for any remaining rows with invalid datetime formats
invalid_rows = df[df['time_answer'].isna() | df['StartDate_First_ISO'].isna()]
len(invalid_rows['uid'].unique())

32

In [301]:
df['uid'].unique()

array([267322, 266327, 266481, ..., 267931, 267992, 268054])

In [302]:
df[df['uid'] == 266481]['StartDate_First']
df[df['uid'] == 266481]['time_answer']

6066   2024-10-16 12:38:05.734000+00:00
6067   2024-10-16 12:38:11.069000+00:00
6077   2024-10-16 12:38:20.277000+00:00
6078   2024-10-16 12:38:25.142000+00:00
6079   2024-10-16 12:38:30.653000+00:00
                     ...
6977   2024-10-16 12:53:11.381000+00:00
6982   2024-10-16 12:53:24.173000+00:00
6983   2024-10-16 12:53:25.140000+00:00
6984   2024-10-16 12:53:26.124000+00:00
6985   2024-10-16 12:53:27.429000+00:00
Name: time_answer, Length: 131, dtype: datetime64[ns, UTC]

In [318]:
# Calculate the time difference between the last 'time_question' and 'StartDate_First_ISO'
last_observation['time_difference'] = last_observation['time_answer'] - last_observation['StartDate_First_ISO']

In [319]:
result = last_observation[['psid', 'StartDate_First_ISO','time_answer', 'time_difference']]
result

,psid,StartDate_First_ISO,time_answer,time_difference
0,_1KUVoNGiAg-FXLYMSdwbQ**,2024-10-16 09:22:46+00:00,2024-10-16 17:48:58.821000+00:00,0 days 08:26:12.821000
1,_1KUVoNGiAg-GTXuLE-E1g**,2024-10-15 01:25:35+00:00,2024-10-15 12:03:48.141000+00:00,0 days 10:38:13.141000
2,_1KUVoNGiAg-ODrdbezcMw**,2024-10-16 04:22:50+00:00,2024-10-16 12:53:27.429000+00:00,0 days 08:30:37.429000
3,_1KUVoNGiAg-d35IGIrcEA**,2024-10-16 08:18:03+00:00,2024-10-16 16:50:38.332000+00:00,0 days 08:32:35.332000
4,_1KUVoNGiAg0OjdoLHQ17Q**,2024-10-16 06:24:05+00:00,2024-10-16 18:12:45.130000+00:00,0 days 11:48:40.130000
...,...,...,...,...
1276,_1KUVoNGiAjynt4MFNWj_A**,2024-10-14 01:20:04+00:00,2024-10-14 09:38:55.704000+00:00,0 days 08:18:51.704000
1277,_1KUVoNGiAjyy-x0jm2qrw**,2024-10-16 05:13:33+00:00,2024-10-16 13:37:33.136000+00:00,0 days 08:24:00.136000
1278,_1KUVoNGiAjz-R_IQlXnww**,2024-10-16 12:10:11+00:00,2024-10-16 20:26:47.788000+00:00,0 days 08:16:36.788000
1279,_1KUVoNGiAjz9z84bgIj8Q**,2024-10-16 20:11:46+00:00,2024-10-17 04:34:33.011000+00:00,0 days 08:22:47.011000
1280,_1KUVoNGiAjzeHozgt9H4w**,2024-10-15 01:20:12+00:00,2024-10-15 09:30:47.810000+00:00,0 days 08:10:35.810000

In [ ]:
df = df.sort_values(by=['uid', 'time_question'])