
# 05 — Inter-annotator reliability (final corrected version)

This notebook computes **ordinal Krippendorff's $\alpha$** for the three annotation outcomes on the original 5-point scale, with a coarsened 3-category version as a robustness check.

### Important corrections / final choices

- The working matrix is built as **items × raters** for convenient item-level resampling, but is **transposed to raters × items** whenever it is passed to `krippendorff.alpha()`.
- The point estimate is cross-checked against the package's `value_counts=` interface for every construct/subset.
- Confidence intervals use a **standard item-level nonparametric bootstrap with replacement**, drawing $n$ items from the $n$ observed items in each replicate.
- The main uncertainty interval is the **95% percentile bootstrap CI**. The earlier 80% subsampling / delete-chunk BCa implementation is not used here.
- Items with fewer than two valid ratings within a subset are excluded.
- Exact duplicate item–rater rows are dropped; conflicting duplicate ratings trigger an error rather than being averaged.
- The bootstrap resamples items only and therefore conditions on the observed rater pool. This is appropriate for uncertainty over the sampled tweets; it is not a multiway item-and-rater bootstrap.

The notebook first prints audits and point estimates, then computes the bootstrap CIs, and only uploads output files after a separate explicit upload cell is run.

In [1]:
# -*- coding: utf-8 -*-
# ===========================================================
# 05_IRR_ALPHA — FINAL CORRECTED VERSION
# Krippendorff alpha (ordinal)
# Main: 5-point ratings
# Robustness: soft 3-category ratings (1-2 / 3 / 4-5)
# Uncertainty: full-n item bootstrap WITH replacement
# ===========================================================

import numpy as np
import pandas as pd
import krippendorff
from datetime import datetime
from IPython.display import display

import config
import rd_utils as rd
from rd_utils import webdav_mkdirs, webdav_upload_bytes

# ---------------------------
# Paths (Research Drive)
# ---------------------------
PROJ       = config.PROJECT_ROOT
DATA_DIR   = f"{PROJ}/data"
TABLES_DIR = f"{PROJ}/output/tables"
INPUT_PARQUET = "final_merged_dataset_for_analysis.parquet"

# Keep the established output filenames for the main percentile-CI tables.
OUT_TEX_MAIN_5      = f"{TABLES_DIR}/irr_alpha_table_5pt_percentile.tex"
OUT_CSV_MAIN_5      = f"{TABLES_DIR}/irr_alpha_summary_5pt_percentile.csv"
OUT_TXT_MAIN_5      = f"{TABLES_DIR}/irr_alpha_interpretation_5pt_percentile.txt"
OUT_TEX_OVERVIEW_5  = f"{TABLES_DIR}/irr_alpha_overview_5pt_percentile_apa.tex"
OUT_CSV_OVERVIEW_5  = f"{TABLES_DIR}/irr_alpha_overview_5pt_percentile.csv"

OUT_TEX_MAIN_S3     = f"{TABLES_DIR}/irr_alpha_table_soft3_percentile.tex"
OUT_CSV_MAIN_S3     = f"{TABLES_DIR}/irr_alpha_summary_soft3_percentile.csv"
OUT_TXT_MAIN_S3     = f"{TABLES_DIR}/irr_alpha_interpretation_soft3_percentile.txt"
OUT_TEX_OVERVIEW_S3 = f"{TABLES_DIR}/irr_alpha_overview_soft3_percentile_apa.tex"
OUT_CSV_OVERVIEW_S3 = f"{TABLES_DIR}/irr_alpha_overview_soft3_percentile.csv"

# ---------------------------
# Columns
# ---------------------------
ITEM_COL  = "unit_id"
RATER_COL = "coder"
VAR_COL   = "variable"
SRC_COL   = "source_shown"
INST_COL  = "instruction_type"

# ---------------------------
# Constructs
# ---------------------------
CONSTRUCTS = {
    "stellingen.sentiment":      "Negative Sentiment",
    "stellingen.misinformation": "Misinformation",
    "stellingen.toxic":          "Toxicity",
}
CONSTRUCT_ORDER = ["Negative Sentiment", "Misinformation", "Toxicity"]

# ---------------------------
# Subsets
# ---------------------------
SUBSET_DISPLAY = {
    "Overall": "Overall",
    "source_shown=1": "Source shown",
    "source_shown=0": "Source masked",
    "instruction_type=no instructions": "No instructions",
    "instruction_type=general instructions": "General instructions",
    "instruction_type=tailored instructions": "Tailored instructions",
}
SUBSET_ORDER = [
    "Overall",
    "Source shown", "Source masked",
    "No instructions", "General instructions", "Tailored instructions",
]
SUBSET_SPECS = [
    ("Overall", None, None),
    ("source_shown=1", SRC_COL, 1),
    ("source_shown=0", SRC_COL, 0),
    ("instruction_type=no instructions",       INST_COL, "no instructions"),
    ("instruction_type=general instructions",  INST_COL, "general instructions"),
    ("instruction_type=tailored instructions", INST_COL, "tailored instructions"),
]

# ---------------------------
# Bootstrap config
# ---------------------------
B = 1000
SEED = 123
CI_LEVEL = 0.95

# ===========================================================
# WebDAV helpers
# ===========================================================
def _parent_dir(path: str) -> str:
    parts = path.rsplit("/", 1)
    return parts[0] if len(parts) == 2 else ""


def upload_text(rel_path: str, text: str, content_type: str = "text/plain; charset=utf-8"):
    webdav_mkdirs(_parent_dir(rel_path))
    webdav_upload_bytes(rel_path, text.encode("utf-8"), content_type=content_type)
    print(f"Uploaded {rel_path}")


def upload_bytes(rel_path: str, b: bytes, content_type: str):
    webdav_mkdirs(_parent_dir(rel_path))
    webdav_upload_bytes(rel_path, b, content_type=content_type)
    print(f"Uploaded {rel_path}")

# ===========================================================
# Rating preparation
# ===========================================================
def ensure_rating_1_5(
    df: pd.DataFrame,
    prefer=("value_scaled", "value"),
    label_cols=("value", "answer", "response", "value_label", "code", "rating"),
) -> pd.DataFrame:
    """Create numeric 1..5 column `_rating5` without silently coercing arbitrary values."""
    df = df.copy()

    def try_numeric(col):
        if col not in df.columns:
            return None, None

        x = pd.to_numeric(df[col], errors="coerce")
        nonmissing = x.dropna()
        if nonmissing.empty or x.notna().mean() < 0.80:
            return None, None

        lo, hi = float(nonmissing.min()), float(nonmissing.max())

        # Already on a 1..5 integer grid.
        if 1 - 1e-8 <= lo and hi <= 5 + 1e-8:
            if not np.allclose(nonmissing.to_numpy(), np.round(nonmissing.to_numpy()), atol=1e-8):
                raise ValueError(f"{col} lies in 1..5 but contains non-integer values; inspect before IRR.")
            return x.round(), f"{col} (already 1–5)"

        # 0..1 version of a five-point scale: require quarter-step values.
        if -1e-8 <= lo and hi <= 1 + 1e-8:
            grid = nonmissing.to_numpy() * 4
            if not np.allclose(grid, np.round(grid), atol=1e-8):
                raise ValueError(f"{col} lies in 0..1 but is not on a five-point quarter-step grid.")
            y = 1 + 4 * x
            return y.round(), f"{col} (0–1 -> 1–5)"

        return None, None

    for col in prefer:
        y, msg = try_numeric(col)
        if y is not None:
            df["_rating5"] = y
            print(
                f"[rating] Using {msg}. valid={df['_rating5'].notna().mean():.3f} "
                f"min={df['_rating5'].min()} max={df['_rating5'].max()}"
            )
            return df

    LIKERT_MAP_NL = {
        "Helemaal niet waar":     1,
        "Gedeeltelijk niet waar": 2,
        "Neutraal":               3,
        "Gedeeltelijk waar":      4,
        "Helemaal waar":          5,
    }
    for col in label_cols:
        if col in df.columns and df[col].notna().any():
            s = df[col].astype(str).str.strip()
            m = s.map(LIKERT_MAP_NL)
            if m.notna().mean() >= 0.80:
                df["_rating5"] = m.astype(float)
                print(f"[rating] Using {col} (mapped labels). valid={m.notna().mean():.3f}")
                return df

    raise ValueError(
        "No usable rating column found (need numeric 1–5, a five-point 0–1 grid, or mappable labels)."
    )


def apply_scale(df: pd.DataFrame, scale: str) -> tuple[pd.DataFrame, list[int]]:
    """Add `_rating_work` and return the fixed ordinal value domain."""
    df = df.copy()

    if scale == "5pt":
        df["_rating_work"] = df["_rating5"]
        return df, [1, 2, 3, 4, 5]

    if scale == "soft3":
        x = pd.to_numeric(df["_rating5"], errors="coerce")
        y = pd.Series(np.nan, index=df.index, dtype=float)
        y[(x >= 1) & (x <= 2)] = 1
        y[x == 3] = 2
        y[(x >= 4) & (x <= 5)] = 3
        df["_rating_work"] = y
        return df, [1, 2, 3]

    raise ValueError("scale must be '5pt' or 'soft3'.")

# ===========================================================
# Matrix building + audits
# ===========================================================
def pivot_items_raters(dfc: pd.DataFrame, rating_col="_rating_work", min_k=2):
    """
    Build an ITEMS x RATERS matrix for item-level resampling.

    IMPORTANT: `krippendorff.alpha(reliability_data=...)` expects RATERS x ITEMS,
    so this matrix is transposed only at the alpha call.
    """
    if dfc.empty:
        return None, [], 0, {"duplicate_pairs": 0, "conflicting_pairs": 0}

    use = dfc[[ITEM_COL, RATER_COL, rating_col]].copy()
    use[rating_col] = pd.to_numeric(use[rating_col], errors="coerce")
    use = use.dropna(subset=[ITEM_COL, RATER_COL, rating_col])
    if use.empty:
        return None, [], 0, {"duplicate_pairs": 0, "conflicting_pairs": 0}

    # Duplicate audit. Do not average conflicting ratings.
    pair_sizes = use.groupby([ITEM_COL, RATER_COL], dropna=False).size()
    duplicate_pairs = int((pair_sizes > 1).sum())

    pair_nunique = use.groupby([ITEM_COL, RATER_COL], dropna=False)[rating_col].nunique(dropna=True)
    conflicting_pairs = int((pair_nunique > 1).sum())
    if conflicting_pairs:
        bad = pair_nunique[pair_nunique > 1].head(10)
        raise ValueError(
            f"Found {conflicting_pairs} item-rater pairs with conflicting ratings. "
            f"Examples:\n{bad}"
        )

    # Exact repeated rows/pairs carry no new information.
    use = use.drop_duplicates(subset=[ITEM_COL, RATER_COL], keep="first")

    # Keep items with at least min_k distinct raters inside this subset.
    k = use.groupby(ITEM_COL)[RATER_COL].nunique()
    keep_items = k[k >= min_k].index
    use = use[use[ITEM_COL].isin(keep_items)]
    if use.empty:
        return None, [], 0, {
            "duplicate_pairs": duplicate_pairs,
            "conflicting_pairs": conflicting_pairs,
        }

    pivot = use.pivot(index=ITEM_COL, columns=RATER_COL, values=rating_col)
    M = pivot.to_numpy(dtype=float)  # items x raters

    return (
        M,
        list(pivot.index),
        int(pivot.columns.size),
        {
            "duplicate_pairs": duplicate_pairs,
            "conflicting_pairs": conflicting_pairs,
        },
    )

# ===========================================================
# Krippendorff alpha + independent representation cross-check
# ===========================================================
def alpha_ordinal(M: np.ndarray, domain: list[int]) -> float:
    if M is None or M.shape[0] == 0:
        return np.nan
    # Correct orientation for the package: RATERS x ITEMS.
    return float(
        krippendorff.alpha(
            reliability_data=M.T,
            value_domain=domain,
            level_of_measurement="ordinal",
        )
    )


def alpha_ordinal_from_counts(M: np.ndarray, domain: list[int]) -> float:
    """Same alpha through the package's item x category count representation."""
    if M is None or M.shape[0] == 0:
        return np.nan
    counts = np.column_stack([np.sum(M == v, axis=1) for v in domain])
    return float(
        krippendorff.alpha(
            value_counts=counts,
            value_domain=domain,
            level_of_measurement="ordinal",
        )
    )


def checked_alpha(M: np.ndarray, domain: list[int], atol=1e-12) -> tuple[float, float]:
    a_matrix = alpha_ordinal(M, domain)
    a_counts = alpha_ordinal_from_counts(M, domain)
    if not np.isclose(a_matrix, a_counts, atol=atol, rtol=0, equal_nan=True):
        raise AssertionError(
            f"Alpha representation cross-check failed: matrix={a_matrix}, counts={a_counts}"
        )
    return a_matrix, a_counts

# ===========================================================
# Standard item bootstrap WITH replacement
# ===========================================================
def bootstrap_alphas(M: np.ndarray, domain: list[int], B=B, seed=SEED) -> np.ndarray:
    """
    Nonparametric item bootstrap: sample n items WITH replacement from the n observed items.
    Raters are not resampled; inference is conditional on the observed rater pool.
    """
    n = M.shape[0]
    rng = np.random.default_rng(seed)
    boots = np.full(B, np.nan, dtype=float)

    for b in range(B):
        sel = rng.integers(0, n, size=n)
        try:
            boots[b] = alpha_ordinal(M[sel], domain)
        except Exception:
            boots[b] = np.nan

    return boots


def percentile_ci(boots: np.ndarray, ci_level=CI_LEVEL) -> tuple[float, float]:
    boots = np.asarray(boots, dtype=float)
    valid = boots[np.isfinite(boots)]
    if valid.size == 0:
        return np.nan, np.nan
    tail = (1.0 - ci_level) / 2.0
    lo, hi = np.quantile(valid, [tail, 1.0 - tail])
    return float(lo), float(hi)


def alpha_point_and_ci(M, domain, B=B, seed=SEED):
    if M is None or M.shape[0] == 0:
        return np.nan, (np.nan, np.nan), {
            "alpha_counts": np.nan,
            "crosscheck_absdiff": np.nan,
            "boot_valid": 0,
            "boot_total": B,
        }

    a_hat, a_counts = checked_alpha(M, domain)
    boots = bootstrap_alphas(M, domain, B=B, seed=seed)
    lo, hi = percentile_ci(boots, ci_level=CI_LEVEL)

    diag = {
        "alpha_counts": a_counts,
        "crosscheck_absdiff": abs(a_hat - a_counts),
        "boot_valid": int(np.isfinite(boots).sum()),
        "boot_total": int(B),
    }
    return a_hat, (lo, hi), diag

# ===========================================================
# Summary computation
# ===========================================================
def run_irr_summary(df_annot: pd.DataFrame, scale: str, progress=True) -> pd.DataFrame:
    df = ensure_rating_1_5(df_annot, prefer=("value_scaled", "value"))
    df, domain = apply_scale(df, scale=scale)

    rows = []
    total = len(CONSTRUCTS) * len(SUBSET_SPECS)
    counter = 0

    for var_key, display_name in CONSTRUCTS.items():
        base = df.loc[df[VAR_COL] == var_key].copy()

        for code, col, val in SUBSET_SPECS:
            counter += 1
            subset_name = SUBSET_DISPLAY.get(code, code)
            if progress:
                print(f"[{scale}] {counter}/{total}: {display_name} — {subset_name}", flush=True)

            block = base if col is None else base.loc[base[col] == val]
            M, items_used, raters_used, matrix_audit = pivot_items_raters(
                block, rating_col="_rating_work", min_k=2
            )

            # A different deterministic stream for each result.
            result_seed = SEED + counter
            a_hat, (ci_low, ci_high), diag = alpha_point_and_ci(
                M, domain=domain, B=B, seed=result_seed
            )

            if progress:
                print(
                    f"    alpha={a_hat:.3f} | 95% bootstrap CI "
                    f"[{ci_low:.3f}, {ci_high:.3f}] | "
                    f"items={len(items_used):,} | raters={raters_used:,} | "
                    f"valid boots={diag['boot_valid']}/{diag['boot_total']}",
                    flush=True,
                )

            rows.append({
                "construct": display_name,
                "subset_code": code,
                "subset_disp": subset_name,
                "alpha": a_hat,
                "ci_low": ci_low,
                "ci_high": ci_high,
                "items": int(len(items_used)),
                "raters_used": int(raters_used),
                "boot_valid": int(diag["boot_valid"]),
                "boot_total": int(diag["boot_total"]),
                "alpha_counts": diag["alpha_counts"],
                "crosscheck_absdiff": diag["crosscheck_absdiff"],
                "duplicate_pairs": int(matrix_audit["duplicate_pairs"]),
                "conflicting_pairs": int(matrix_audit["conflicting_pairs"]),
                "scale": scale,
            })

    out = pd.DataFrame(rows)
    out["construct"] = pd.Categorical(
        out["construct"], categories=CONSTRUCT_ORDER, ordered=True
    )
    out["subset_disp"] = pd.Categorical(
        out["subset_disp"], categories=SUBSET_ORDER, ordered=True
    )
    return out.sort_values(["construct", "subset_disp"]).reset_index(drop=True)

# ===========================================================
# Formatting / export helpers
# ===========================================================
def _fmt_int_ltx(n: int) -> str:
    return f"{int(n):,}".replace(",", "{,}")


def latex_table_long(summary_df: pd.DataFrame, label: str, caption: str, scale_note="") -> str:
    lines = [
        r"\begin{table}[tbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabularx}{\linewidth}{l l c c c c}",
        r"\toprule",
        r"\textbf{Construct} & \textbf{Subset} & $\boldsymbol{\alpha}$ & \textbf{95\% CI} & \textbf{Items} & \textbf{Raters} \\",
        r"\midrule",
    ]

    for _, r in summary_df.iterrows():
        a = "NA" if pd.isna(r["alpha"]) else f"{r['alpha']:.3f}"
        lo = "NA" if pd.isna(r["ci_low"]) else f"{r['ci_low']:.3f}"
        hi = "NA" if pd.isna(r["ci_high"]) else f"{r['ci_high']:.3f}"
        lines.append(
            f"{r['construct']} & {r['subset_disp']} & {a} & [{lo}, {hi}] & "
            f"{_fmt_int_ltx(r['items'])} & {_fmt_int_ltx(r['raters_used'])} \\\\"
        )

    note = (
        r"\par\vspace{0.5ex}\parbox{\linewidth}{\footnotesize\emph{Note}. "
        r"Values are ordinal Krippendorff's $\alpha$." + scale_note +
        rf" Confidence intervals are {int(CI_LEVEL*100)}\% percentile intervals from a nonparametric item bootstrap "
        rf"with replacement ($n$ items per replicate; $B={B}$). "
        r"The item bootstrap conditions on the observed rater pool. Items with fewer than two valid ratings "
        r"within a subset are excluded.}"
    )

    lines += [
        r"\bottomrule",
        r"\end{tabularx}",
        note,
        r"\end{table}",
    ]
    return "\n".join(lines)


def build_overview_df(summary_df: pd.DataFrame) -> pd.DataFrame:
    df = summary_df.copy()

    def cell(r):
        if pd.isna(r["alpha"]) or pd.isna(r["ci_low"]) or pd.isna(r["ci_high"]):
            return "NA"
        return f"{r['alpha']:.3f} [{r['ci_low']:.3f}, {r['ci_high']:.3f}]"

    df["cell"] = df.apply(cell, axis=1)
    df = df[df["subset_disp"].isin(SUBSET_ORDER)].copy()
    df["subset_disp"] = pd.Categorical(df["subset_disp"], categories=SUBSET_ORDER, ordered=True)

    wide = (
        df.pivot_table(index="construct", columns="subset_disp", values="cell", aggfunc="first", observed=False)
          .reindex(index=CONSTRUCT_ORDER, columns=SUBSET_ORDER)
          .reset_index()
    )
    wide.columns.name = None
    return wide


def overview_counts(summary_df: pd.DataFrame) -> pd.DataFrame:
    """Return one Items/Raters count per subset, but fail if counts differ across constructs."""
    rows = []
    for subset in SUBSET_ORDER:
        s = summary_df.loc[summary_df["subset_disp"] == subset]
        if s.empty:
            continue

        if s["items"].nunique() != 1 or s["raters_used"].nunique() != 1:
            raise ValueError(
                f"Counts differ across constructs for '{subset}'. "
                "Do not print a single overview count without resolving this first."
            )
        rows.append({
            "subset_disp": subset,
            "items": int(s["items"].iloc[0]),
            "raters_used": int(s["raters_used"].iloc[0]),
        })
    return pd.DataFrame(rows)


def latex_overview_table_apa_grouped(wide_df, counts_df, label, caption, scale_note="") -> str:
    cols = ["construct"] + SUBSET_ORDER
    df = wide_df.copy()
    for c in cols:
        if c not in df.columns:
            df[c] = "NA"
    df = df[cols]

    counts = counts_df.set_index("subset_disp")

    def fmt_n(x):
        return f"{int(x):,}".replace(",", "{,}")

    def n_items(col):
        return "NA" if col not in counts.index else fmt_n(counts.loc[col, "items"])

    def n_raters(col):
        return "NA" if col not in counts.index else fmt_n(counts.loc[col, "raters_used"])

    lines = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\begin{threeparttable}",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{tabularx}{\linewidth}{>{\raggedright\arraybackslash}l *{6}{>{\centering\arraybackslash}X}}",
        r"\toprule",
        r"\textbf{Construct} & \textbf{Overall} & \multicolumn{2}{c}{\textbf{Source visibility}} & \multicolumn{3}{c}{\textbf{Instruction type}} \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-7}",
        r" &  & \textbf{Shown} & \textbf{Masked} & \textbf{None} & \textbf{General} & \textbf{Tailored} \\",
        r"\midrule",
        r"\textit{Items} ($n$) & " + n_items("Overall") + " & " + n_items("Source shown") + " & " + n_items("Source masked")
        + " & " + n_items("No instructions") + " & " + n_items("General instructions") + " & " + n_items("Tailored instructions") + r" \\",
        r"\textit{Raters} ($n$) & " + n_raters("Overall") + " & " + n_raters("Source shown") + " & " + n_raters("Source masked")
        + " & " + n_raters("No instructions") + " & " + n_raters("General instructions") + " & " + n_raters("Tailored instructions") + r" \\",
        r"\addlinespace[0.35em]",
    ]

    for _, r in df.iterrows():
        lines.append(
            f"\\textbf{{{r['construct']}}} & {r['Overall']} & {r['Source shown']} & {r['Source masked']} & "
            f"{r['No instructions']} & {r['General instructions']} & {r['Tailored instructions']} \\\\"
        )

    note = (
        r"\emph{Note}. Cells report ordinal Krippendorff's $\alpha$ with "
        rf"{int(CI_LEVEL*100)}\% percentile confidence intervals from a nonparametric item bootstrap "
        rf"with replacement ($n$ items per replicate; $B={B}$)." + scale_note +
        r" The item bootstrap conditions on the observed rater pool."
    )

    lines += [
        r"\bottomrule",
        r"\end{tabularx}",
        r"\begin{tablenotes}[flushleft]",
        r"\footnotesize",
        rf"\item {note}",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ]
    return "\n".join(lines)


def interpretation_text(summary_df: pd.DataFrame, scale_label: str) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    parts = [
        f"Inter-annotator agreement (ordinal Krippendorff's alpha; {scale_label}).",
        f"Generated: {ts}",
        f"95% percentile CI from full-n item bootstrap with replacement; B={B}.",
        "Bootstrap resamples tweets/items only and conditions on the observed rater pool.",
        "",
    ]

    for cons in CONSTRUCT_ORDER:
        sub = summary_df.loc[summary_df["construct"] == cons]
        if sub.empty:
            continue
        parts.append(cons + ":")
        for subset in SUBSET_ORDER:
            row = sub.loc[sub["subset_disp"] == subset]
            if row.empty:
                continue
            r = row.iloc[0]
            parts.append(
                f"  - {subset}: alpha={r['alpha']:.3f} [{r['ci_low']:.3f}, {r['ci_high']:.3f}] "
                f"(items={int(r['items'])}, raters={int(r['raters_used'])}, "
                f"bootstrap valid={int(r['boot_valid'])}/{int(r['boot_total'])})"
            )
        parts.append("")
    return "\n".join(parts)


def export_scale(summary: pd.DataFrame, scale: str):
    webdav_mkdirs(TABLES_DIR)

    cols = [
        "construct", "subset_code", "subset_disp", "alpha", "ci_low", "ci_high",
        "items", "raters_used", "boot_valid", "boot_total",
        "alpha_counts", "crosscheck_absdiff", "duplicate_pairs", "conflicting_pairs",
    ]

    if scale == "5pt":
        out_tex_main, out_csv_main, out_txt_main = OUT_TEX_MAIN_5, OUT_CSV_MAIN_5, OUT_TXT_MAIN_5
        out_tex_over, out_csv_over = OUT_TEX_OVERVIEW_5, OUT_CSV_OVERVIEW_5
        caption = "Inter-annotator agreement (Krippendorff's $\\alpha$, ordinal; 5-point scale)."
        label = "tab:irr_alpha_5pt_percentile"
        over_caption = "Inter-annotator agreement overview (Krippendorff's $\\alpha$, ordinal; 5-point scale)."
        over_label = "tab:irr_alpha_overview_5pt_percentile"
        scale_note = ""
    elif scale == "soft3":
        out_tex_main, out_csv_main, out_txt_main = OUT_TEX_MAIN_S3, OUT_CSV_MAIN_S3, OUT_TXT_MAIN_S3
        out_tex_over, out_csv_over = OUT_TEX_OVERVIEW_S3, OUT_CSV_OVERVIEW_S3
        caption = "Inter-annotator agreement (Krippendorff's $\\alpha$, ordinal; coarsened 3-category scale)."
        label = "tab:irr_alpha_soft3_percentile"
        over_caption = "Inter-annotator agreement overview (Krippendorff's $\\alpha$, ordinal; coarsened 3-category scale)."
        over_label = "tab:irr_alpha_overview_soft3_percentile"
        scale_note = " Coarsened scale: 1--2 (low), 3 (neutral), 4--5 (high), treated as ordinal."
    else:
        raise ValueError("scale must be '5pt' or 'soft3'.")

    upload_bytes(
        out_csv_main,
        summary[cols].to_csv(index=False).encode("utf-8"),
        content_type="text/csv; charset=utf-8",
    )
    upload_text(
        out_tex_main,
        latex_table_long(summary, label=label, caption=caption, scale_note=scale_note),
        content_type="text/x-tex; charset=utf-8",
    )
    upload_text(
        out_txt_main,
        interpretation_text(summary, "5-point" if scale == "5pt" else "soft 3-category"),
        content_type="text/plain; charset=utf-8",
    )

    wide = build_overview_df(summary)
    counts = overview_counts(summary)
    upload_bytes(
        out_csv_over,
        wide.to_csv(index=False).encode("utf-8"),
        content_type="text/csv; charset=utf-8",
    )
    upload_text(
        out_tex_over,
        latex_overview_table_apa_grouped(
            wide, counts, label=over_label, caption=over_caption, scale_note=scale_note
        ),
        content_type="text/x-tex; charset=utf-8",
    )


## Load data and run pre-analysis audits

This cell does **not** upload anything. It checks required columns, reports the rating distribution for the three constructs, and verifies the experimental subset labels that the IRR analysis expects.

In [2]:
print("[Load] Reading merged dataset from Research Drive...")
df_annot = rd.read_parquet(f"{DATA_DIR}/{INPUT_PARQUET}")
print(f"[Load] rows={df_annot.shape[0]:,} | cols={df_annot.shape[1]:,}")

required = {ITEM_COL, RATER_COL, VAR_COL, SRC_COL, INST_COL}
missing = sorted(required - set(df_annot.columns))
if missing:
    raise KeyError(f"Missing required columns: {missing}")

if not (("value_scaled" in df_annot.columns) or ("value" in df_annot.columns)):
    raise KeyError("Need rating column 'value_scaled' or 'value'.")

# Prepare once for transparent audits.
df_audit = ensure_rating_1_5(df_annot, prefer=("value_scaled", "value"))
relevant = df_audit[df_audit[VAR_COL].isin(CONSTRUCTS.keys())].copy()

print("\n[Audit] Relevant construct rows and valid ratings:")
audit_construct = (
    relevant.groupby(VAR_COL, dropna=False)
    .agg(
        rows=(ITEM_COL, "size"),
        items=(ITEM_COL, "nunique"),
        raters=(RATER_COL, "nunique"),
        valid_ratings=("_rating5", lambda s: int(s.notna().sum())),
    )
)
audit_construct["valid_fraction"] = audit_construct["valid_ratings"] / audit_construct["rows"]
display(audit_construct)

print("\n[Audit] 5-point rating frequencies among relevant rows:")
display(
    relevant.groupby(VAR_COL)["_rating5"]
    .value_counts(dropna=False)
    .rename("n")
    .to_frame()
)

print("\n[Audit] Source visibility values:")
print(relevant[SRC_COL].value_counts(dropna=False))

print("\n[Audit] Instruction values:")
print(relevant[INST_COL].value_counts(dropna=False))

print("\n[Audit complete] No files have been uploaded.")

[Load] Reading merged dataset from Research Drive...
[Load] rows=153,674 | cols=203
[rating] Using value_scaled (already 1–5). valid=0.906 min=1.0 max=5.0

[Audit] Relevant construct rows and valid ratings:

                            rows  items  raters  valid_ratings  valid_fraction
variable
stellingen.misinformation  34811   1826    1248          34811             1.0
stellingen.sentiment       34808   1826    1248          34808             1.0
stellingen.toxic           34809   1826    1248          34809             1.0

[Audit] 5-point rating frequencies among relevant rows:

                                        n
variable                  _rating5
stellingen.misinformation 3.0       11993
                          1.0        8484
                          4.0        5754
                          2.0        5023
                          5.0        3557
stellingen.sentiment      3.0        9590
                          1.0        7482
                          4.0        7422
                          5.0        5321
                          2.0        4993
stellingen.toxic          3.0       10609
                          1.0        9744
                          4.0        5764
                          2.0        5063
                          5.0        3629

[Audit] Source visibility values:
source_shown
0    52761
1    51667
Name: count, dtype: int64

[Audit] Instruction values:
instruction_type
general instructions     35587
no instructions          34599
tailored instructions    34242
Name: count, dtype: int64

[Audit complete] No files have been uploaded.


## Quick corrected point-estimate preview

This computes the corrected $\alpha$ values **without bootstrap CIs**. It is useful for verifying that the point estimates match the corrected analysis before spending time on resampling.

In [3]:

def quick_alpha_preview(df_annot: pd.DataFrame, scale: str) -> pd.DataFrame:
    df = ensure_rating_1_5(df_annot, prefer=("value_scaled", "value"))
    df, domain = apply_scale(df, scale=scale)

    rows = []
    print(f"\n========== {scale.upper()} CORRECTED POINT ESTIMATES ==========")

    for var_key, display_name in CONSTRUCTS.items():
        base = df.loc[df[VAR_COL] == var_key].copy()

        for code, col, val in SUBSET_SPECS:
            block = base if col is None else base.loc[base[col] == val]
            M, items_used, raters_used, matrix_audit = pivot_items_raters(
                block, rating_col="_rating_work", min_k=2
            )
            a, a_counts = checked_alpha(M, domain)

            row = {
                "construct": display_name,
                "subset": SUBSET_DISPLAY.get(code, code),
                "alpha": a,
                "alpha_counts": a_counts,
                "crosscheck_absdiff": abs(a - a_counts),
                "items": len(items_used),
                "raters": raters_used,
                "duplicate_pairs": matrix_audit["duplicate_pairs"],
            }
            rows.append(row)

            print(
                f"{display_name:20s} | {row['subset']:20s} | "
                f"alpha={a:.6f} | items={len(items_used):,} | raters={raters_used:,} | "
                f"crosscheck diff={row['crosscheck_absdiff']:.2e}"
            )

    result = pd.DataFrame(rows)
    result["construct"] = pd.Categorical(
        result["construct"], categories=CONSTRUCT_ORDER, ordered=True
    )
    result["subset"] = pd.Categorical(
        result["subset"], categories=SUBSET_ORDER, ordered=True
    )
    result = result.sort_values(["construct", "subset"]).reset_index(drop=True)

    print(f"\n{scale.upper()} overview:")
    wide = result.pivot(index="construct", columns="subset", values="alpha")
    wide = wide.reindex(index=CONSTRUCT_ORDER, columns=SUBSET_ORDER)
    display(wide.round(3))
    return result

quick_5 = quick_alpha_preview(df_annot, "5pt")
quick_s3 = quick_alpha_preview(df_annot, "soft3")

print("\n[Quick preview complete] No files have been uploaded.")

[rating] Using value_scaled (already 1–5). valid=0.906 min=1.0 max=5.0

========== 5PT CORRECTED POINT ESTIMATES ==========
Negative Sentiment   | Overall              | alpha=0.203121 | items=1,826 | raters=1,248 | crosscheck diff=0.00e+00
Negative Sentiment   | Source shown         | alpha=0.184196 | items=1,826 | raters=615 | crosscheck diff=0.00e+00
Negative Sentiment   | Source masked        | alpha=0.225866 | items=1,826 | raters=633 | crosscheck diff=0.00e+00
Negative Sentiment   | No instructions      | alpha=0.222524 | items=1,826 | raters=413 | crosscheck diff=0.00e+00
Negative Sentiment   | General instructions | alpha=0.197788 | items=1,826 | raters=420 | crosscheck diff=0.00e+00
Negative Sentiment   | Tailored instructions | alpha=0.175814 | items=1,826 | raters=415 | crosscheck diff=0.00e+00
Misinformation       | Overall              | alpha=0.088192 | items=1,826 | raters=1,248 | crosscheck diff=0.00e+00
Misinformation       | Source shown         | alpha=0.093363 | items=1,826 | raters=615 | crosscheck diff=0.00e+00
Misinformation       | Source masked        | alpha=0.096024 | items=1,826 | raters=633 | crosscheck diff=0.00e+00
Misinformation       | No instructions      | alpha=0.114875 | items=1,826 | raters=413 | crosscheck diff=0.00e+00
Misinformation       | General instructions | alpha=0.078175 | items=1,826 | raters=420 | crosscheck diff=0.00e+00
Misinformation       | Tailored instructions | alpha=0.070427 | items=1,826 | raters=415 | crosscheck diff=0.00e+00
Toxicity             | Overall              | alpha=0.139237 | items=1,826 | raters=1,248 | crosscheck diff=0.00e+00
Toxicity             | Source shown         | alpha=0.126821 | items=1,826 | raters=615 | crosscheck diff=0.00e+00
Toxicity             | Source masked        | alpha=0.158140 | items=1,826 | raters=633 | crosscheck diff=0.00e+00
Toxicity             | No instructions      | alpha=0.154313 | items=1,826 | raters=413 | crosscheck diff=0.00e+00
Toxicity             | General instructions | alpha=0.124870 | items=1,826 | raters=420 | crosscheck diff=0.00e+00
Toxicity             | Tailored instructions | alpha=0.129083 | items=1,826 | raters=415 | crosscheck diff=0.00e+00

5PT overview:

subset,Overall,Source shown,Source masked,No instructions,General instructions,Tailored instructions
construct,,,,,,
Negative Sentiment,0.203,0.184,0.226,0.223,0.198,0.176
Misinformation,0.088,0.093,0.096,0.115,0.078,0.070
Toxicity,0.139,0.127,0.158,0.154,0.125,0.129

[rating] Using value_scaled (already 1–5). valid=0.906 min=1.0 max=5.0

========== SOFT3 CORRECTED POINT ESTIMATES ==========
Negative Sentiment   | Overall              | alpha=0.176656 | items=1,826 | raters=1,248 | crosscheck diff=0.00e+00
Negative Sentiment   | Source shown         | alpha=0.158020 | items=1,826 | raters=615 | crosscheck diff=0.00e+00
Negative Sentiment   | Source masked        | alpha=0.197370 | items=1,826 | raters=633 | crosscheck diff=0.00e+00
Negative Sentiment   | No instructions      | alpha=0.197283 | items=1,826 | raters=413 | crosscheck diff=0.00e+00
Negative Sentiment   | General instructions | alpha=0.172917 | items=1,826 | raters=420 | crosscheck diff=0.00e+00
Negative Sentiment   | Tailored instructions | alpha=0.148027 | items=1,826 | raters=415 | crosscheck diff=0.00e+00
Misinformation       | Overall              | alpha=0.075436 | items=1,826 | raters=1,248 | crosscheck diff=0.00e+00
Misinformation       | Source shown         | alpha=0.081307 | items=1,826 | raters=615 | crosscheck diff=0.00e+00
Misinformation       | Source masked        | alpha=0.082717 | items=1,826 | raters=633 | crosscheck diff=0.00e+00
Misinformation       | No instructions      | alpha=0.104141 | items=1,826 | raters=413 | crosscheck diff=0.00e+00
Misinformation       | General instructions | alpha=0.066023 | items=1,826 | raters=420 | crosscheck diff=0.00e+00
Misinformation       | Tailored instructions | alpha=0.057502 | items=1,826 | raters=415 | crosscheck diff=0.00e+00
Toxicity             | Overall              | alpha=0.120285 | items=1,826 | raters=1,248 | crosscheck diff=0.00e+00
Toxicity             | Source shown         | alpha=0.105864 | items=1,826 | raters=615 | crosscheck diff=0.00e+00
Toxicity             | Source masked        | alpha=0.139744 | items=1,826 | raters=633 | crosscheck diff=0.00e+00
Toxicity             | No instructions      | alpha=0.140801 | items=1,826 | raters=413 | crosscheck diff=0.00e+00
Toxicity             | General instructions | alpha=0.103242 | items=1,826 | raters=420 | crosscheck diff=0.00e+00
Toxicity             | Tailored instructions | alpha=0.111920 | items=1,826 | raters=415 | crosscheck diff=0.00e+00

SOFT3 overview:

subset,Overall,Source shown,Source masked,No instructions,General instructions,Tailored instructions
construct,,,,,,
Negative Sentiment,0.177,0.158,0.197,0.197,0.173,0.148
Misinformation,0.075,0.081,0.083,0.104,0.066,0.058
Toxicity,0.120,0.106,0.140,0.141,0.103,0.112

[Quick preview complete] No files have been uploaded.


## Full bootstrap confidence intervals

This is the computationally expensive step. Each result uses `B = 1000` full-size item bootstrap samples **with replacement**. No files are uploaded here.

In [4]:

print("\n[Compute] Full 5-point alpha + standard item-bootstrap CIs...")
summary_5 = run_irr_summary(df_annot, scale="5pt", progress=True)

display(summary_5[[
    "construct", "subset_disp", "alpha", "ci_low", "ci_high",
    "items", "raters_used", "boot_valid", "boot_total", "crosscheck_absdiff"
]])

print("\n5-point APA-style overview:")
display(build_overview_df(summary_5))

print("\n[Compute] Soft 3-category robustness alpha + standard item-bootstrap CIs...")
summary_s3 = run_irr_summary(df_annot, scale="soft3", progress=True)

display(summary_s3[[
    "construct", "subset_disp", "alpha", "ci_low", "ci_high",
    "items", "raters_used", "boot_valid", "boot_total", "crosscheck_absdiff"
]])

print("\nSoft-3 APA-style overview:")
display(build_overview_df(summary_s3))

print("\n[Full computation complete] Nothing has been uploaded yet.")
print("Inspect the results above before running the upload cell.")

[Compute] Full 5-point alpha + standard item-bootstrap CIs...
[rating] Using value_scaled (already 1–5). valid=0.906 min=1.0 max=5.0
[5pt] 1/18: Negative Sentiment — Overall
    alpha=0.203 | 95% bootstrap CI [0.192, 0.214] | items=1,826 | raters=1,248 | valid boots=1000/1000
[5pt] 2/18: Negative Sentiment — Source shown
    alpha=0.184 | 95% bootstrap CI [0.170, 0.198] | items=1,826 | raters=615 | valid boots=1000/1000
[5pt] 3/18: Negative Sentiment — Source masked
    alpha=0.226 | 95% bootstrap CI [0.211, 0.240] | items=1,826 | raters=633 | valid boots=1000/1000
[5pt] 4/18: Negative Sentiment — No instructions
    alpha=0.223 | 95% bootstrap CI [0.203, 0.242] | items=1,826 | raters=413 | valid boots=1000/1000
[5pt] 5/18: Negative Sentiment — General instructions
    alpha=0.198 | 95% bootstrap CI [0.181, 0.214] | items=1,826 | raters=420 | valid boots=1000/1000
[5pt] 6/18: Negative Sentiment — Tailored instructions
    alpha=0.176 | 95% bootstrap CI [0.158, 0.192] | items=1,826 | raters=415 | valid boots=1000/1000
[5pt] 7/18: Misinformation — Overall
    alpha=0.088 | 95% bootstrap CI [0.081, 0.096] | items=1,826 | raters=1,248 | valid boots=1000/1000
[5pt] 8/18: Misinformation — Source shown
    alpha=0.093 | 95% bootstrap CI [0.082, 0.104] | items=1,826 | raters=615 | valid boots=1000/1000
[5pt] 9/18: Misinformation — Source masked
    alpha=0.096 | 95% bootstrap CI [0.083, 0.107] | items=1,826 | raters=633 | valid boots=1000/1000
[5pt] 10/18: Misinformation — No instructions
    alpha=0.115 | 95% bootstrap CI [0.099, 0.131] | items=1,826 | raters=413 | valid boots=1000/1000
[5pt] 11/18: Misinformation — General instructions
    alpha=0.078 | 95% bootstrap CI [0.063, 0.093] | items=1,826 | raters=420 | valid boots=1000/1000
[5pt] 12/18: Misinformation — Tailored instructions
    alpha=0.070 | 95% bootstrap CI [0.056, 0.085] | items=1,826 | raters=415 | valid boots=1000/1000
[5pt] 13/18: Toxicity — Overall
    alpha=0.139 | 95% bootstrap CI [0.129, 0.149] | items=1,826 | raters=1,248 | valid boots=1000/1000
[5pt] 14/18: Toxicity — Source shown
    alpha=0.127 | 95% bootstrap CI [0.113, 0.139] | items=1,826 | raters=615 | valid boots=1000/1000
[5pt] 15/18: Toxicity — Source masked
    alpha=0.158 | 95% bootstrap CI [0.144, 0.173] | items=1,826 | raters=633 | valid boots=1000/1000
[5pt] 16/18: Toxicity — No instructions
    alpha=0.154 | 95% bootstrap CI [0.137, 0.173] | items=1,826 | raters=413 | valid boots=1000/1000
[5pt] 17/18: Toxicity — General instructions
    alpha=0.125 | 95% bootstrap CI [0.109, 0.140] | items=1,826 | raters=420 | valid boots=1000/1000
[5pt] 18/18: Toxicity — Tailored instructions
    alpha=0.129 | 95% bootstrap CI [0.112, 0.145] | items=1,826 | raters=415 | valid boots=1000/1000

,construct,subset_disp,alpha,ci_low,ci_high,items,raters_used,boot_valid,boot_total,crosscheck_absdiff
0,Negative Sentiment,Overall,0.203121,0.192252,0.213693,1826,1248,1000,1000,0.0
1,Negative Sentiment,Source shown,0.184196,0.169951,0.197700,1826,615,1000,1000,0.0
2,Negative Sentiment,Source masked,0.225866,0.210761,0.240077,1826,633,1000,1000,0.0
3,Negative Sentiment,No instructions,0.222524,0.202732,0.242151,1826,413,1000,1000,0.0
4,Negative Sentiment,General instructions,0.197788,0.181044,0.214487,1826,420,1000,1000,0.0
5,Negative Sentiment,Tailored instructions,0.175814,0.158338,0.191980,1826,415,1000,1000,0.0
6,Misinformation,Overall,0.088192,0.080633,0.096148,1826,1248,1000,1000,0.0
7,Misinformation,Source shown,0.093363,0.081732,0.104185,1826,615,1000,1000,0.0
8,Misinformation,Source masked,0.096024,0.082958,0.107187,1826,633,1000,1000,0.0
9,Misinformation,No instructions,0.114875,0.098951,0.131274,1826,413,1000,1000,0.0
10,Misinformation,General instructions,0.078175,0.063395,0.093111,1826,420,1000,1000,0.0
11,Misinformation,Tailored instructions,0.070427,0.055776,0.084544,1826,415,1000,1000,0.0
12,Toxicity,Overall,0.139237,0.128875,0.148968,1826,1248,1000,1000,0.0
13,Toxicity,Source shown,0.126821,0.113151,0.138854,1826,615,1000,1000,0.0
14,Toxicity,Source masked,0.158140,0.144366,0.172655,1826,633,1000,1000,0.0
15,Toxicity,No instructions,0.154313,0.136587,0.173084,1826,413,1000,1000,0.0
16,Toxicity,General instructions,0.124870,0.108825,0.139557,1826,420,1000,1000,0.0
17,Toxicity,Tailored instructions,0.129083,0.112494,0.145074,1826,415,1000,1000,0.0

5-point APA-style overview:

,construct,Overall,Source shown,Source masked,No instructions,General instructions,Tailored instructions
0,Negative Sentiment,"0.203 [0.192, 0.214]","0.184 [0.170, 0.198]","0.226 [0.211, 0.240]","0.223 [0.203, 0.242]","0.198 [0.181, 0.214]","0.176 [0.158, 0.192]"
1,Misinformation,"0.088 [0.081, 0.096]","0.093 [0.082, 0.104]","0.096 [0.083, 0.107]","0.115 [0.099, 0.131]","0.078 [0.063, 0.093]","0.070 [0.056, 0.085]"
2,Toxicity,"0.139 [0.129, 0.149]","0.127 [0.113, 0.139]","0.158 [0.144, 0.173]","0.154 [0.137, 0.173]","0.125 [0.109, 0.140]","0.129 [0.112, 0.145]"

[Compute] Soft 3-category robustness alpha + standard item-bootstrap CIs...
[rating] Using value_scaled (already 1–5). valid=0.906 min=1.0 max=5.0
[soft3] 1/18: Negative Sentiment — Overall
    alpha=0.177 | 95% bootstrap CI [0.166, 0.187] | items=1,826 | raters=1,248 | valid boots=1000/1000
[soft3] 2/18: Negative Sentiment — Source shown
    alpha=0.158 | 95% bootstrap CI [0.144, 0.171] | items=1,826 | raters=615 | valid boots=1000/1000
[soft3] 3/18: Negative Sentiment — Source masked
    alpha=0.197 | 95% bootstrap CI [0.183, 0.211] | items=1,826 | raters=633 | valid boots=1000/1000
[soft3] 4/18: Negative Sentiment — No instructions
    alpha=0.197 | 95% bootstrap CI [0.178, 0.217] | items=1,826 | raters=413 | valid boots=1000/1000
[soft3] 5/18: Negative Sentiment — General instructions
    alpha=0.173 | 95% bootstrap CI [0.157, 0.189] | items=1,826 | raters=420 | valid boots=1000/1000
[soft3] 6/18: Negative Sentiment — Tailored instructions
    alpha=0.148 | 95% bootstrap CI [0.132, 0.163] | items=1,826 | raters=415 | valid boots=1000/1000
[soft3] 7/18: Misinformation — Overall
    alpha=0.075 | 95% bootstrap CI [0.069, 0.083] | items=1,826 | raters=1,248 | valid boots=1000/1000
[soft3] 8/18: Misinformation — Source shown
    alpha=0.081 | 95% bootstrap CI [0.071, 0.091] | items=1,826 | raters=615 | valid boots=1000/1000
[soft3] 9/18: Misinformation — Source masked
    alpha=0.083 | 95% bootstrap CI [0.071, 0.093] | items=1,826 | raters=633 | valid boots=1000/1000
[soft3] 10/18: Misinformation — No instructions
    alpha=0.104 | 95% bootstrap CI [0.089, 0.120] | items=1,826 | raters=413 | valid boots=1000/1000
[soft3] 11/18: Misinformation — General instructions
    alpha=0.066 | 95% bootstrap CI [0.053, 0.081] | items=1,826 | raters=420 | valid boots=1000/1000
[soft3] 12/18: Misinformation — Tailored instructions
    alpha=0.058 | 95% bootstrap CI [0.044, 0.071] | items=1,826 | raters=415 | valid boots=1000/1000
[soft3] 13/18: Toxicity — Overall
    alpha=0.120 | 95% bootstrap CI [0.111, 0.129] | items=1,826 | raters=1,248 | valid boots=1000/1000
[soft3] 14/18: Toxicity — Source shown
    alpha=0.106 | 95% bootstrap CI [0.093, 0.117] | items=1,826 | raters=615 | valid boots=1000/1000
[soft3] 15/18: Toxicity — Source masked
    alpha=0.140 | 95% bootstrap CI [0.126, 0.154] | items=1,826 | raters=633 | valid boots=1000/1000
[soft3] 16/18: Toxicity — No instructions
    alpha=0.141 | 95% bootstrap CI [0.123, 0.160] | items=1,826 | raters=413 | valid boots=1000/1000
[soft3] 17/18: Toxicity — General instructions
    alpha=0.103 | 95% bootstrap CI [0.088, 0.118] | items=1,826 | raters=420 | valid boots=1000/1000
[soft3] 18/18: Toxicity — Tailored instructions
    alpha=0.112 | 95% bootstrap CI [0.095, 0.128] | items=1,826 | raters=415 | valid boots=1000/1000

,construct,subset_disp,alpha,ci_low,ci_high,items,raters_used,boot_valid,boot_total,crosscheck_absdiff
0,Negative Sentiment,Overall,0.176656,0.166362,0.186642,1826,1248,1000,1000,0.0
1,Negative Sentiment,Source shown,0.158020,0.144427,0.171107,1826,615,1000,1000,0.0
2,Negative Sentiment,Source masked,0.197370,0.183282,0.211421,1826,633,1000,1000,0.0
3,Negative Sentiment,No instructions,0.197283,0.177644,0.216504,1826,413,1000,1000,0.0
4,Negative Sentiment,General instructions,0.172917,0.157262,0.188583,1826,420,1000,1000,0.0
5,Negative Sentiment,Tailored instructions,0.148027,0.131882,0.163462,1826,415,1000,1000,0.0
6,Misinformation,Overall,0.075436,0.068615,0.083104,1826,1248,1000,1000,0.0
7,Misinformation,Source shown,0.081307,0.070728,0.091392,1826,615,1000,1000,0.0
8,Misinformation,Source masked,0.082717,0.070908,0.093017,1826,633,1000,1000,0.0
9,Misinformation,No instructions,0.104141,0.089050,0.119723,1826,413,1000,1000,0.0
10,Misinformation,General instructions,0.066023,0.052964,0.080627,1826,420,1000,1000,0.0
11,Misinformation,Tailored instructions,0.057502,0.043920,0.071257,1826,415,1000,1000,0.0
12,Toxicity,Overall,0.120285,0.111066,0.129110,1826,1248,1000,1000,0.0
13,Toxicity,Source shown,0.105864,0.092817,0.117324,1826,615,1000,1000,0.0
14,Toxicity,Source masked,0.139744,0.125921,0.153773,1826,633,1000,1000,0.0
15,Toxicity,No instructions,0.140801,0.122877,0.160129,1826,413,1000,1000,0.0
16,Toxicity,General instructions,0.103242,0.087667,0.118044,1826,420,1000,1000,0.0
17,Toxicity,Tailored instructions,0.111920,0.095223,0.127988,1826,415,1000,1000,0.0

Soft-3 APA-style overview:

,construct,Overall,Source shown,Source masked,No instructions,General instructions,Tailored instructions
0,Negative Sentiment,"0.177 [0.166, 0.187]","0.158 [0.144, 0.171]","0.197 [0.183, 0.211]","0.197 [0.178, 0.217]","0.173 [0.157, 0.189]","0.148 [0.132, 0.163]"
1,Misinformation,"0.075 [0.069, 0.083]","0.081 [0.071, 0.091]","0.083 [0.071, 0.093]","0.104 [0.089, 0.120]","0.066 [0.053, 0.081]","0.058 [0.044, 0.071]"
2,Toxicity,"0.120 [0.111, 0.129]","0.106 [0.093, 0.117]","0.140 [0.126, 0.154]","0.141 [0.123, 0.160]","0.103 [0.088, 0.118]","0.112 [0.095, 0.128]"

[Full computation complete] Nothing has been uploaded yet.
Inspect the results above before running the upload cell.


## Upload checked output files

Run this cell **only after inspecting** the point estimates, bootstrap CIs, counts, and cross-check diagnostics above.

In [5]:

if "summary_5" not in globals() or "summary_s3" not in globals():
    raise RuntimeError("Run the full bootstrap-CI cell first.")

# Safety checks before writing files.
for name, s in [("5pt", summary_5), ("soft3", summary_s3)]:
    if (s["crosscheck_absdiff"] > 1e-10).any():
        raise AssertionError(f"{name}: alpha cross-check discrepancy detected; not uploading.")
    if (s["conflicting_pairs"] > 0).any():
        raise AssertionError(f"{name}: conflicting duplicate item-rater ratings detected; not uploading.")
    if (s["boot_valid"] < s["boot_total"]).any():
        print(f"[Warning] {name}: at least one result has failed bootstrap replicates; inspect before publication.")

print("[Upload] Writing checked 5-point outputs...")
export_scale(summary_5, scale="5pt")

print("\n[Upload] Writing checked soft-3 robustness outputs...")
export_scale(summary_s3, scale="soft3")

print("\n[Done] Uploaded final corrected IRR outputs to Research Drive.")

[Upload] Writing checked 5-point outputs...
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_summary_5pt_percentile.csv
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_table_5pt_percentile.tex
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_interpretation_5pt_percentile.txt
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_overview_5pt_percentile.csv
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_overview_5pt_percentile_apa.tex

[Upload] Writing checked soft-3 robustness outputs...
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_summary_soft3_percentile.csv
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_table_soft3_percentile.tex
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_interpretation_soft3_percentile.txt
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_overview_soft3_percentile.csv
Uploaded ASCOR-FMG-4394-AnNoBias (Projectfolder)/output/tables/irr_alpha_overview_soft3_percentile_apa.tex

[Done] Uploaded final corrected IRR outputs to Research Drive.